### ISSUE TITLE
您好，我一直在用的一个签到云函数，前端时间突然不能用了，感觉是网页后台改参数了，能帮我看下吗，谢谢！

### ISSUE THREAD

**Issue by wy1ng** [Sitoi/DailyCheckIn#1]
[https://github.com/wy1ng/opsignin/blob/main/index.py](url)

**Comment by Sitoi** [comment]
参考你的文件已经添加到这个项目中了，你可以尝试一下，我没有加油，测试不了抽奖。
如果没问题的话，顺便把这个 issue 关闭了吧，谢谢！！

**Comment by wy1ng** [comment]
> 参考你的文件已经添加到这个项目中了，你可以尝试一下，我没有加油，测试不了抽奖。
> 如果没问题的话，顺便把这个 issue 关闭了吧，谢谢！！

程序跑起来没啥问题，不过抽奖最后的结果貌似不对，10次抽奖，每次消耗10加油，所以最后的结果还要减100

**Comment by Sitoi** [comment]
好的 已经更新了！

**Comment by wy1ng** [comment]
![image](https://user-images.githubusercontent.com/46668637/102718666-4591d180-4324-11eb-9971-d025f5dedad6.png)
刚发现，最后计算结果不对

**Comment by Sitoi** [comment]
> ![image](https://user-images.githubusercontent.com/46668637/102718666-4591d180-4324-11eb-9971-d025f5dedad6.png)
> 刚发现，最后计算结果不对

看最后一个就好了，抽奖状态的 8 加油 是最有一次抽奖的信息，我有空完善一下

**Comment by wy1ng** [comment]
> 好的 已经更新了！

斜体加粗大写英文字母 表示 GitHub Actions Secrets 环境变量名称，内容直接复制 斜体加粗大写英文字母 key 对应的 value 是 List 格式的直接复制全部 List 内容

这句话怎么断句？没理解。。。
这个一加签到的secret Name是ONEPLUSBBS_COOKIE_LIST吗？Value怎么填，需要把整个都复制进去？
{"ONEPLUSBBS_COOKIE_LIST": [
    {
      "oneplusbbs_cookie": "帐号1 cookie"
    },
    {
      "oneplusbbs_cookie": "帐号2 cookie"
    }
  ]
}

**Comment by Sitoi** [comment]
> > 好的 已经更新了！
> 
> 斜体加粗大写英文字母 表示 GitHub Actions Secrets 环境变量名称，内容直接复制 斜体加粗大写英文字母 key 对应的 value 是 List 格式的直接复制全部 List 内容
> 
> 这句话怎么断句？没理解。。。
> 这个一加签到的secret Name是ONEPLUSBBS_COOKIE_LIST吗？Value怎么填，需要把整个都复制进去？
> {"ONEPLUSBBS_COOKIE_LIST": [
> {
> "oneplusbbs_cookie": "帐号1 cookie"
> },
> {
> "oneplusbbs_cookie": "帐号2 cookie"
> }
> ]
> }

https://sitoi.github.io/dailycheckin/github-actions/#secrets

**Comment by wy1ng** [comment]
> https://sitoi.github.io/dailycheckin/github-actions/#secrets

##***group***Run python3 index.py
***36;1mpython3 index.py***0m
shell: /bin/bash -e ***0***
env:
  pythonLocation: /opt/hostedtoolcache/Python/3.7.9/x64
  IS_GITHUB_ACTION: true
  DINGTALK_SECRET: 
  DINGTALK_ACCESS_TOKEN: 
  SCKEY: ***
  QMSG_KEY: 
  TG_BOT_TOKEN: 
  TG_USER_ID: 
  COOLPUSHSKEY: 
  COOLPUSHQQ: 
  COOLPUSHWX: 
  COOLPUSHEMAIL: 
  CITY_NAME_LIST: 
  MOTTO: 
  IQIYI_COOKIE_LIST: 
  VQQ_COOKIE_LIST: 
  YOUDAO_COOKIE_LIST: 
  KGQQ_COOKIE_LIST: 
  MUSIC163_ACCOUNT_LIST: 
  ONEPLUSBBS_COOKIE_LIST: ***
  FMAPP_ACCOUNT_LIST: 
  BAIDU_URL_SUBMIT_LIST: 
  TIEBA_COOKIE_LIST: 
  BILIBILI_COOKIE_LIST: 
  LIANTONG_ACCOUNT_LIST: 
##***endgroup***
Traceback (most recent call last):
  File "index.py", line 270, in <module>
    main_handler(event=event, context=None)
  File "index.py", line 198, in main_handler
    msg_list = OnePlusBBSCheckIn(oneplusbbs_cookie_list=oneplusbbs_cookie_list).main()
  File "/home/runner/work/dailycheckin/dailycheckin/oneplusbbs/oneplusbbs.py", line 97, in main
    bbs_uname = re.findall(r"bbs_uname=(.*?);", oneplusbbs_cookie)***0***.split("%7C")***0***
IndexError: list index out of range
##***error***Process completed with exit code 1.

**Comment by wy1ng** [comment]
![image](https://user-images.githubusercontent.com/46668637/104141203-8e531c80-53f0-11eb-998b-5017281b5a0b.png)

**Comment by Sitoi** [comment]
我修复一下吧，从 cookie 获取用户信息有点问题

**Comment by Sitoi** [comment]
可以了 应该

**Comment by wy1ng** [comment]
ok了，但是没有log输出

##***group***Run python3 index.py
***36;1mpython3 index.py***0m
shell: /bin/bash -e ***0***
env:
  pythonLocation: /opt/hostedtoolcache/Python/3.7.9/x64
  IS_GITHUB_ACTION: true
  DINGTALK_SECRET: 
  DINGTALK_ACCESS_TOKEN: 
  SCKEY: ***
  QMSG_KEY: 
  TG_BOT_TOKEN: 
  TG_USER_ID: 
  COOLPUSHSKEY: 
  COOLPUSHQQ: 
  COOLPUSHWX: 
  COOLPUSHEMAIL: 
  CITY_NAME_LIST: 
  MOTTO: 
  IQIYI_COOKIE_LIST: 
  VQQ_COOKIE_LIST: 
  YOUDAO_COOKIE_LIST: 
  KGQQ_COOKIE_LIST: 
  MUSIC163_ACCOUNT_LIST: 
  ONEPLUSBBS_COOKIE_LIST: ***
  FMAPP_ACCOUNT_LIST: 
  BAIDU_URL_SUBMIT_LIST: 
  TIEBA_COOKIE_LIST: 
  BILIBILI_COOKIE_LIST: 
  LIANTONG_ACCOUNT_LIST: 
  V2EX_COOKIE_LIST: 
  WWW2NZZ_COOKIE_LIST: 
  SMZDM_COOKIE_LIST: 
##***endgroup***
list index out of range
当前时间: 2021-01-11 09:52:35.538316
-----------------------------

本次任务使用时间: 0.0015783309936523438 秒
server 酱推送开始

**Comment by Sitoi** [comment]
> ok了，但是没有log输出
> 
> ## ##_**group**_Run python3 index.py
> �_**36;1mpython3 index.py�**_0m
> shell: /bin/bash -e _**0**_
> env:
> pythonLocation: /opt/hostedtoolcache/Python/3.7.9/x64
> IS_GITHUB_ACTION: true
> DINGTALK_SECRET:
> DINGTALK_ACCESS_TOKEN:
> SCKEY: ***
> QMSG_KEY:
> TG_BOT_TOKEN:
> TG_USER_ID:
> COOLPUSHSKEY:
> COOLPUSHQQ:
> COOLPUSHWX:
> COOLPUSHEMAIL:
> CITY_NAME_LIST:
> MOTTO:
> IQIYI_COOKIE_LIST:
> VQQ_COOKIE_LIST:
> YOUDAO_COOKIE_LIST:
> KGQQ_COOKIE_LIST:
> MUSIC163_ACCOUNT_LIST:
> ONEPLUSBBS_COOKIE_LIST: ***
> FMAPP_ACCOUNT_LIST:
> BAIDU_URL_SUBMIT_LIST:
> TIEBA_COOKIE_LIST:
> BILIBILI_COOKIE_LIST:
> LIANTONG_ACCOUNT_LIST:
> V2EX_COOKIE_LIST:
> WWW2NZZ_COOKIE_LIST:
> SMZDM_COOKIE_LIST:
> ##_**endgroup**_
> list index out of range
> 当前时间: 2021-01-11 09:52:35.538316
> 本次任务使用时间: 0.0015783309936523438 秒
> server 酱推送开始

是我这边没修复好 ，现在应该好了

**Comment by wy1ng** [comment]
![image](https://user-images.githubusercontent.com/46668637/104252569-51992b00-54ad-11eb-9d1f-25ac855f6ef3.png)
![image](https://user-images.githubusercontent.com/46668637/104252581-578f0c00-54ad-11eb-97d5-00ff300fe2cd.png)
![image](https://user-images.githubusercontent.com/46668637/104252597-5e1d8380-54ad-11eb-93cd-a8c2387dc14e.png)
实测确实是已抽奖，但是没有签到...

**Comment by Sitoi** [comment]
> ![image](https://user-images.githubusercontent.com/46668637/104252569-51992b00-54ad-11eb-9d1f-25ac855f6ef3.png)
> ![image](https://user-images.githubusercontent.com/46668637/104252581-578f0c00-54ad-11eb-97d5-00ff300fe2cd.png)
> ![image](https://user-images.githubusercontent.com/46668637/104252597-5e1d8380-54ad-11eb-93cd-a8c2387dc14e.png)
> 实测确实是已抽奖，但是没有签到...

cookie 过期了应该是，获取新的 cookie 就行
