### ISSUE TITLE
【GitHub 被封】

### ISSUE THREAD

**Issue by Sitoi** [Sitoi/dailycheckin#1]
由于 GitHub 仓库被封，更新了项目更新的方式，使用 Pypi 的方式进行更新

> Pypi 地址: https://pypi.org/project/dailycheckin/

- 移除了 GitHub actions 的运行方式
- 腾讯云函数教程  https://sitoi.gitee.io/dailycheckin/tencent-scf/，更新代码的方式见文档
- docker 如需自动更新，请手动拉取最新的 docker 镜像，教程基本不变

新的仓库以后只会发布教程，不影响正常使用！

其余问题见群公告！！！！

**Comment by wangyunqing198801** [comment]
是否可以增加众邦银行答题，现在微信公众号也能答题了，每天签到答题1块1的众邦豆子，可以兑换话费E卡什么的

**Comment by VwEl** [comment]
每天都是
【哔咔漫画】签到状态: 重复签到
进APP也没有打哔咔
