### ISSUE TITLE
能否将crontab文件映射本地文件

### ISSUE THREAD

**Issue by zhuyaozi** [Sitoi/dailycheckin#10]
## 期望增加的功能

A：
能否将crontab文件映射本地文件

## 入口

A：
能否将crontab文件映射本地文件，每次容器重启后cron任务就复位了。。。

**Comment by Sitoi** [comment]
> ## 期望增加的功能
> A：
> 能否将crontab文件映射本地文件
> 
> ## 入口
> A：
> 能否将crontab文件映射本地文件，每次容器重启后cron任务就复位了。。。

晚上我添加一下

**Comment by Sitoi** [comment]
> > ## 期望增加的功能
> > A：
> > 能否将crontab文件映射本地文件
> > ## 入口
> > A：
> > 能否将crontab文件映射本地文件，每次容器重启后cron任务就复位了。。。
> 
> 晚上我添加一下

https://github.com/Sitoi/dailycheckin/tree/main/docker/example

参考这里的文件配置一下吧，本地做了简单的测试
记得先更新下 docker。

**Comment by zhuyaozi** [comment]
> > > ## 期望增加的功能
> > > A：
> > > 能否将crontab文件映射本地文件
> > > ## 入口
> > > A：
> > > 能否将crontab文件映射本地文件，每次容器重启后cron任务就复位了。。。
> > 
> > 
> > 晚上我添加一下
> 
> https://github.com/Sitoi/dailycheckin/tree/main/docker/example
> 
> 参考这里的文件配置一下吧，本地做了简单的测试
> 记得先更新下 docker。

配置过了，正常运转中，感谢！
