### ISSUE TITLE
能否把https://github.com/GeorgeLxw/sspauto的机场签到加进去

### ISSUE THREAD

**Issue by E2077** [Sitoi/dailycheckin#100]
能否把https://github.com/GeorgeLxw/sspauto的机场签到加进去
这个项目,修改或增加账号都要去打开secrets中修改MYKEY的值,非常不便,还不支持电报推送
,每天要登录一个个看是否成功

创建secrets 名字：MYKEY 内容的写法：
机场的名字(方便自己看)|机场的网址(https:www.xxxx...)|第一个邮箱(用户名),密码;第二个邮箱,密码;...

列:
莉莉VPN1|https://lilyco.cc|123@gmail.com,qq123123;456@gmail.com,qq123123
OK加速|https://ok.okjiasu.com|123@gmail.com,qq123456
MiCloud|https://aoog.me|123@gmail.com,qq123123;456@gmail.com,qq123123
可莉云|https://xn--jprs12i.com|123@qq.com,qq123123

**Comment by E2077** [comment]
机场首页下拉, 最下面有Powered by SSPANEL • Theme by editXY 的都支持用这个签到,差不多市面上90%的机场都能用这个签到

**Comment by Sitoi** [comment]
这两天会支持这个功能
