### ISSUE TITLE
【repo-sync.yml】repo-sync error

### ISSUE THREAD

**Issue by RockZhou8** [Sitoi/dailycheckin#105]
## 1.关于你要提交的问题

Q：是否搜索了 issue（包括已关闭的issue）

- [ x] 没有类似的 issue 

Q：是否仔细阅读了教程

- [ x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装 Python
- [ ] 方法二：Docker
- [ ] 方法三：腾讯云函数
- [X ] 方法四：GitHub Actions

### (1) 具体问题

A：repo-sync error
配置了全权限的PAT 并且加入到secrets （Name: PAT Value:xxxxxxxxxxx）还是无法同步，还有哪些需要注意的？

### (2) 详细日志

A：Run repo-sync/github-sync@v2
/usr/bin/docker run --name ghcrioreposyncgithubsyncv230_a05a91 --label 5588e4 --workdir /github/workspace --rm -e PAT -e INPUT_SOURCE_REPO -e INPUT_SOURCE_BRANCH -e INPUT_DESTINATION_BRANCH -e INPUT_GITHUB_TOKEN -e INPUT_SYNC_TAGS -e GITHUB_TOKEN -e SYNC_TAGS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/dailycheckin/dailycheckin":"/github/workspace" ghcr.io/repo-sync/github-sync:v2.3.0  "https://github.com/Sitoi/dailycheckin.git" "main:main"
UPSTREAM_REPO=https://github.com/Sitoi/dailycheckin.git
BRANCHES=main:main
Resetting origin to: https://RockZhou8:*** @github.com/RockZhou8/dailycheckin
Adding tmp_upstream https://github.com/Sitoi/dailycheckin.git
Fetching tmp_upstream
origin	https://RockZhou8:*** @github.com/RockZhou8/dailycheckin (fetch)
origin	https://RockZhou8:*** @github.com/RockZhou8/dailycheckin (push)
tmp_upstream	https://github.com/Sitoi/dailycheckin.git (fetch)
tmp_upstream	https://github.com/Sitoi/dailycheckin.git (push)
Pushing changings from tmp_upstream to origin
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/RockZhou8/dailycheckin/'

**Comment by Sitoi** [comment]
PAT 有问题吧
