### ISSUE TITLE
【xmly.py】喜马拉雅万能卡自动兑换

### ISSUE THREAD

**Issue by qilin7** [Sitoi/dailycheckin#106]
## 1.关于你要提交的问题

Q：是否搜索了 issue（包括已关闭的issue）

- [x] 没有类似的 issue 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装 Python
- [ ] 方法二：Docker
- [x] 方法三：腾讯云函数
- [ ] 方法四：GitHub Actions

### (1) 具体问题

A：喜马拉雅万能卡自动兑换稀有卡报错

### (2) 详细日志

A：截取日志如下：
```
可以兑换

Starting new HTTPS connection (1): m.ximalaya.com:443

https://m.ximalaya.com:443 "POST /speed/web-earn/card/exchangeCard HTTP/1.1" 200 None
```

**Comment by qilin7** [comment]
十几个万能卡了，一直没兑换

**Comment by Sitoi** [comment]
不用管
