### ISSUE TITLE
【一加】cookie中的qKc3_0e8d_noticeTitle找不着

### ISSUE THREAD

**Issue by spiritLHL** [Sitoi/dailycheckin#108]
## 1.关于你要提交的问题

Q：是否搜索了 issue（包括已关闭的issue）

- [x] 没有类似的 issue 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装 Python
- [ ] 方法二：Docker
- [ ] 方法三：腾讯云函数
- [x] 方法四：GitHub Actions

## 3. 详细叙述
cookie中对应的值无法找到
qKc3_0e8d_noticeTitle
### (1) 具体问题

A：cookie中有一段无法找到qKc3_0e8d_noticeTitle

### (2) 详细日志

A：----------已检测到正确的配置，并开始执行 ONEPLUSBBS_COOKIE_LIST 签到----------
抽奖状态: 成功抽奖 0 次
抽奖结果: 获得 0 加油

**Comment by Sitoi** [comment]
看文档

**Comment by spiritLHL** [comment]
> 看文档

"ONEPLUSBBS_COOKIE_LIST": [
    {
      "oneplusbbs_cookie": "acw_tc=xxxxxx; qKc3_0e8d_saltkey=xxxxxx; qKc3_0e8d_lastvisit=xxxxxx; bbs_avatar=xxxxxx; qKc3_0e8d_sendmail=xxxxxx; opcid=xxxxxx; opcct=xxxxxx; oppt=xxxxxx; opsid=xxxxxx; opsct=xxxxxx; opbct=xxxxxx; UM_distinctid=xxxxxx; CNZZDATA1277373783=xxxxxx; www_clear=xxxxxx; ONEPLUSID=xxxxxx; qKc3_0e8d_sid=xxxxxx; bbs_uid=xxxxxx; bbs_uname=xxxxxx; bbs_grouptitle=xxxxxx; opuserid=xxxxxx; bbs_sign=xxxxxx; bbs_formhash=xxxxxx; qKc3_0e8d_ulastactivity=xxxxxx; opsertime=xxxxxx; qKc3_0e8d_lastact=xxxxxx; qKc3_0e8d_checkpm=xxxxxx; ```qKc3_0e8d_noticeTitle```=xxxxxx; optime_browser=xxxxxx; opnt=xxxxxx; opstep=xxxxxx; opstep_event=xxxxxx; fp=xxxxxx;"
    },
    {
      "oneplusbbs_cookie": "多账号 cookie 填写，请参考上面，cookie 以实际获取为准（遇到特殊字符如双引号\" 请加反斜杠转义）"
    }
qKc3_0e8d_noticeTitle这个真的找不着，我看到签到签了，抽奖是我没够等级
![](https://pic.liesio.com/2021/03/12/3f874ab39a653.png)

**Comment by Sitoi** [comment]
以你实际获取到的 cookie 为准 上面只是案例

**Comment by spiritLHL** [comment]
> 以你实际获取到的 cookie 为准 上面只是案例

明白了，谢谢
