### ISSUE TITLE
[需求]QMSG的推送考虑增加一个是否推送到群里的参数配置

### ISSUE THREAD

**Issue by BillScott1024** [Sitoi/dailycheckin#109]
可以在配置中选择是否推送到群里
![image](https://user-images.githubusercontent.com/22955480/111016152-3b451800-83e7-11eb-9afa-b3b5f2d7dcf0.png)

文档链接:
[QMSG API 文档](https://qmsg.zendee.cn/api.html)

**Comment by Sitoi** [comment]
已添加
