### ISSUE TITLE
网易云音乐签到出错

### ISSUE THREAD

**Issue by Anda319** [Sitoi/dailycheckin#110]
----------开始执行「网易云音乐」签到----------

Starting new HTTPS connection (1): music.163.com:443

https://music.163.com:443 "POST /weapi/login/cellphone HTTP/1.1" 200 85

第 1 个账号: ❌❌❌❌❌

not enough values to unpack (expected 7, got 5)

**Comment by Anda319** [comment]
使用的是腾讯云函数

**Comment by Sitoi** [comment]
腾讯云函数可能是地区ban了网易云

**Comment by Anda319** [comment]
好的，感谢解答
