### ISSUE TITLE
【网易云音乐】刷歌成功，但是实际播放歌曲数目并没有增加

### ISSUE THREAD

**Issue by an0na** [Sitoi/dailycheckin#113]
## 1.关于你要提交的问题

Q：是否搜索了 issue（包括已关闭的issue）

- [x] 没有类似的 issue 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装 Python
- [ ] 方法二：Docker
- [ ] 方法三：腾讯云函数
- [x] 方法四：GitHub Actions

### (1) 具体问题

A：网易云每日刷歌显示310首成功，但是实际去查看官网播放歌曲数并没有增加（已经观察差不多一星期了）

### (2) 详细日志

A：

**Comment by Sitoi** [comment]
可否加我微信给个账号测试？

**Comment by an0na** [comment]
MORESTONE

我的微信号，谢谢。

发自地球
