### ISSUE TITLE
在 Docker 中 start.sh 存在的问题

### ISSUE THREAD

**Issue by WuYehow** [Sitoi/dailycheckin#115]
## 1.关于你要提交的问题

Q：是否搜索了 issue（包括已关闭的issue）

- [x] 没有类似的 issue 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装 Python
- [x] 方法二：Docker
- [ ] 方法三：腾讯云函数
- [ ] 方法四：GitHub Actions

### (1) 具体问题

A：在Docker启动过程中，若无法拉取最新的源码，将导致计划任务cron添加失败。导致签到无法正常进行。建议在start.sh中增加判断。

### (2) 详细日志

A：

**Comment by Sitoi** [comment]
拉取代码失败的话 还 gitee tag 的 docker 吧
