### ISSUE TITLE
爱奇艺签到不成功

### ISSUE THREAD

**Issue by a644326772** [Sitoi/dailycheckin#115]
已经更新到最新版，青龙面板下运行无报错，浏览热门任务可以成功运行，但是不签到。现在用的是网页cookie。请问是什么问题。

**Comment by MulderLiu** [comment]
我也遇到了

**Comment by ASFLY61** [comment]
一样的问题，不签到

**Comment by imdingji** [comment]
我还以为就我这样

**Comment by Aexus** [comment]
web重新抓取cookie可以正常签到了

**Comment by ASFLY61** [comment]
> web重新抓取cookie可以正常签到了

我也重新抓了，还是无法签到啊

**Comment by Aexus** [comment]
> 
复制的时候用Ctrl + c.然后粘贴试试.代码更新下,应没问题

**Comment by Sitoi** [comment]
已更新
