### ISSUE TITLE
【docker】拉取的latest镜像是2个月前的(sitoi/dailycheckin      latest              bc71d98b3900        2 months ago        404MB)

### ISSUE THREAD

**Issue by RockZhou8** [Sitoi/dailycheckin#116]
## 1.关于你要提交的问题

Q：是否搜索了 issue（包括已关闭的issue）

- [X ] 没有类似的 issue 

Q：是否仔细阅读了教程

- [ X] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装 Python
- [X ] 方法二：Docker
- [ ] 方法三：腾讯云函数
- [ ] 方法四：GitHub Actions

### (1) 具体问题

A：
w无论是
`
docker pull sitoi/dailycheckin
`

还是

`
docker pull sitoi/dailycheckin:latest
`

都拉取到标签为 latest的镜像，都是2个月前的版本，与https://hub.docker.com/r/sitoi/dailycheckin 上显示的latest版本不符。
REPOSITORY           TAG                 IMAGE ID            CREATED             SIZE
sitoi/dailycheckin      latest              bc71d98b3900        2 months ago        404MB

如果手动拉取 gitee版本，是正常的
REPOSITORY           TAG                 IMAGE ID            CREATED             SIZE
sitoi/dailycheckin   gitee               dc5607be0efe        12 days ago         398MB

希望把gitee版本的 也能更新吧
### (2) 详细日志

A：

**Comment by Sitoi** [comment]
两个月前应该也不影响正常使用吧

**Comment by RockZhou8** [comment]
结果是latest 和 gitee 的docker版都无法启动，卡在无限重启，相关文件夹已设置777权限
