### ISSUE TITLE
云函数不能使用

### ISSUE THREAD

**Issue by ioi32666** [Sitoi/dailycheckin#12]
## 1.关于你要提交的问题

Q：是否搜索了 issue（包括已关闭的issue）

- [x] 没有类似的 issue 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装 Python
- [ ] 方法二：Docker
- [x] 方法三：腾讯云函数
- [ ] 方法四：GitHub Actions

### (1) 具体问题

A：按照教程部署后运行失败

### (2) 详细日志

A：{"errorCode":-1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/index.py\", line 132, in main_handler\n    data = json.loads(f.read())\n  File \"/var/lang/python3/lib/python3.6/json/__init__.py\", line 354, in loads\n    return _default_decoder.decode(s)\n  File \"/var/lang/python3/lib/python3.6/json/decoder.py\", line 339, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/var/lang/python3/lib/python3.6/json/decoder.py\", line 355, in raw_decode\n    obj, end = self.scan_once(s, idx)\njson.decoder.JSONDecodeError: Expecting ',' delimiter: line 9 column 1492 (char 1614)","statusCode":430}

**Comment by Sitoi** [comment]
你是不是 config.josn 文件没配置啊，或者 json 格式检查过吗

**Comment by ioi32666** [comment]
> 你是不是 config.josn 文件没配置啊，或者 json 格式检查过吗

根据config.template.json进行配置和修改的

**Comment by Sitoi** [comment]
你检查下。config.json 格式是否规范

**Comment by ioi32666** [comment]
> 你检查下。config.json 格式是否规范

重新配置了依旧不行

**Comment by Sitoi** [comment]
> > 你检查下。config.json 格式是否规范
> 
> 
> 
> 重新配置了依旧不行

脱敏贴一下配置文件吧
