### ISSUE TITLE
腾讯视频和v2ex签到报错

### ISSUE THREAD

**Issue by FairyWorld** [Sitoi/dailycheckin#123]
#### 收到的错误信息:
![image](https://user-images.githubusercontent.com/32956212/112597403-0bb2f880-8e48-11eb-90d4-bead79494472.png)

#### 收到的错误信息:
![image](https://user-images.githubusercontent.com/32956212/112597463-1cfc0500-8e48-11eb-9abc-d76bc905c1e2.png)

**Comment by Sitoi** [comment]
大概率是你配置文件写得有问题
