### ISSUE TITLE
依赖安装失败，两种方法都装不上，求大佬解决下

### ISSUE THREAD

**Issue by avinrock** [Sitoi/dailycheckin#127]
**方法1：**
root@QL:/ql $ apk add --no-cache gcc g++ python python-dev py-pip mysql-dev linux-headers libffi-dev openssl-dev
fetch http://mirrors.tuna.tsinghua.edu.cn/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://mirrors.tuna.tsinghua.edu.cn/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
ERROR: unable to select packages:
  bizCode (no such package):
    required by: world[bizCode]
  bizMsg (no such package):
    required by: world[bizMsg]
  lxml (no such package):
    required by: world[lxml]
  python (no such package):
    required by: world[python]
  python-dev (no such package):
    required by: world[python-dev]

**方法2**
root@QL:/ql $ apk add --no-cache --virtual .build-deps gcc musl-dev python2-dev python3-dev libffi libffi-dev openssl openssl-dev
fetch http://mirrors.tuna.tsinghua.edu.cn/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://mirrors.tuna.tsinghua.edu.cn/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
ERROR: unable to select packages:
  bizCode (no such package):
    required by: world[bizCode]
  bizMsg (no such package):
    required by: world[bizMsg]
  lxml (no such package):
    required by: world[lxml]

**Comment by d8899p** [comment]
我也是青龙面板中Linux相应依赖安装不上？其余nodejs和python3上的都可以，请问是怎么解决的呀？

**Comment by xiaobaitoudaima** [comment]
一样的问题，都是liunx的依赖安装不上

**Comment by TheKing1991** [comment]
我也是linux的安装不上  不知道咋回事

**Comment by chancat87** [comment]
linux下只成功安装了个Gcc

**Comment by zhang-lanlan** [comment]
so
