### ISSUE TITLE
大佬，顺丰app签到能搞吗？

### ISSUE THREAD

**Issue by lxr760** [Sitoi/dailycheckin#128]
隔壁看到有顺丰签到的脚本，不知道这个能否做进dailycheckin里面

如果可以，非常感谢了

**Comment by github-9233** [comment]
> 隔壁看到有顺丰签到的脚本，不知道这个能否做进dailycheckin里面
> 
> 
> 
> 
> 
> 如果可以，非常感谢了

隔壁在哪里？

**Comment by lxr760** [comment]
> > 隔壁看到有顺丰签到的脚本，不知道这个能否做进dailycheckin里面
> > 如果可以，非常感谢了
> 
> 隔壁在哪里？

https://github.com/chavyleung/scripts/tree/master/sfexpress

**Comment by github-9233** [comment]
> > > 隔壁看到有顺丰签到的脚本，不知道这个能否做进dailycheckin里面
> > > 如果可以，非常感谢了
> > 
> > 
> > 隔壁在哪里？
> 
> https://github.com/chavyleung/scripts/tree/master/sfexpress

这个我用不了。。
