### ISSUE TITLE
喜马拉雅通知建议

### ISSUE THREAD

**Issue by Arrogance-H** [Sitoi/dailycheckin#13]
## 期望增加的功能

A：建议在通知的时候显示账号昵称或者账号设备信息，不然多账号看通知有点乱。
类似这样：
⏰ 喜马拉雅极速版
【设备】| 当前剩余 | 今天| 历史| 连续签到
[iPhoneXS ]: 3.08   (＋0.79) 23.08   23\30
[iPhone12 ]: 5.12   (＋0.93) 35.12   28\30
[iPhone6Plus]: 6.14   (＋0.99) 6.14    5\30
[iPadPro(10.5-inch)]: 1.47   (＋0.96) 1.47    2\30
⭕tips:第30天需要手动签到 by zero_s1, (*^_^*)欢迎打赏 

## 入口

A：

**Comment by Sitoi** [comment]
已添加设备信息
