### ISSUE TITLE
https://ikuuu.co这个机场签到不了

### ISSUE THREAD

**Issue by Dlian-Zero** [Sitoi/dailycheckin#130]
「SSPANEL」
帐号信息: [XXXXXX@qq.com](mailto:xxxxx@qq.com)
签到信息: 签到失败

**Comment by Dlian-Zero** [comment]
2022 © iKuuu VPN  Powered by [SSPANEL](https://ikuuu.co/staff)  Theme by [editXY](https://t.me/editXY)

**Comment by Wyatt323** [comment]
https://ggok.xyz/这个也签到不了

**Comment by Dlian-Zero** [comment]
「SSPANEL」
帐号信息: [XXXX@qq.com](mailto:XXXX@qq.com)
签到信息: 你获得了 2828 MB流量

**Comment by Wyatt323** [comment]
兄弟，你怎么解决的
