### ISSUE TITLE
多看阅读cookie问题

### ISSUE THREAD

**Issue by leic4u** [Sitoi/dailycheckin#131]
我用httpcanary抓取的cookie与配置里面的好像不一样，样例中的 `user_gender` `short_version` 我这都没有，我直接复制整个cookie到配置文件中，运行脚本时还是提示`未检测到正确的配置，并跳过执行 DUOKAN_COOKIE_LIST 签到` （JSON语法没有问题）

请问一下应该怎么配置这个cookie呢？

![image.png](https://i.loli.net/2021/04/05/Aq9WsEgOpGrlu8v.png)

**Comment by Sitoi** [comment]
默认是2个账号 你你检查自己账号是否获取到书豆即可

**Comment by leic4u** [comment]
> 默认是2个账号 你你检查自己账号是否获取到书豆即可

没有获取到书豆，应该是没有跑起来，初步估计是COOKIE的问题，但是目前不知道是具体是啥问题

**Comment by Sitoi** [comment]
cookie 是你自己拼接的吗？需要一个完整的 并且符合cookie的标准格式

**Comment by leic4u** [comment]
> cookie 是你自己拼接的吗？需要一个完整的 并且符合cookie的标准格式

不是拼的，是直接复制的httpcanary抓到的一整条cookie，但是我看了一下，抓到的cookie里面没有样例中给出的几个参数

**Comment by Sitoi** [comment]
加微信 私聊我吧 微信在文档

**Comment by leic4u** [comment]
> 加微信 私聊我吧 微信在文档

已加，感谢开发者大佬
