### ISSUE TITLE
网易云失效

### ISSUE THREAD

**Issue by shilinjin** [Sitoi/dailycheckin#132]
网易云不好用了，一天执行好多次也没用

**Comment by shilinjin** [comment]
今天已经正常了

**Comment by KafCoppelia** [comment]
网易云音乐今日刷歌、签到失效

**Comment by shilinjin** [comment]
是的，原来有时候不涨听歌数，现在直接乱码了。。。

**Comment by WangWenBin2017** [comment]
如果是云函数，有的云函数IP被网易云拉黑了，所以会出现此情况（如果不经配置的话，每次云函数的出口IP不同，而云函数的IP属于是万人骑的，所以有的IP数据异常被网易云拉黑了，但有的还能用）。

**Comment by KafCoppelia** [comment]
错误信息是：
`not enought values to unpack(excepted 7, got 5)`

**Comment by WangWenBin2017** [comment]
> 错误信息是： `not enought values to unpack(excepted 7, got 5)`

是的，曾经我也是这个提示，换地域治标不治本，所以到后面改成本地定时执行了
