### ISSUE TITLE
联通沃邮箱签到不行了

### ISSUE THREAD

**Issue by lxr760** [Sitoi/dailycheckin#133]
昨天还签到成功 而且满21天给了5块钱话费     今天就报错了

配置没动过        进去看了   cookie信息在   json格式也没问题

![image](https://user-images.githubusercontent.com/8476457/156283001-dbbeab8f-5e5c-46d7-a23b-458fc1d5df3e.png)

**Comment by shencore** [comment]
今天在微信开了一下，应该是彻底关了旧签到系统，全面转到新签到系统了。新系统好像没有话费奖励了，价值不大。
