### ISSUE TITLE
【腾讯视频】'NoneType' object has no attribute group

### ISSUE THREAD

**Issue by xuyuanliangcha** [Sitoi/dailycheckin#133]
## 1.关于你要提交的问题

Q：是否搜索了 issue（包括已关闭的issue）

- [x] 没有类似的 issue 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装 Python
- [ ] 方法二：Docker
- [x] 方法三：腾讯云函数
- [ ] 方法四：GitHub Actions

### (1) 具体问题

A：腾讯视频签到后推送结果显示'NoneType' object has no attribute group

### (2) 详细日志

A：START RequestId:def9a1ac-ae66-4b0a-9091-d0a45e67c9f5

----------已检测到正确的配置，并开始执行 IQIYI_COOKIE_LIST 签到----------

Starting new HTTPS connection (1): tc.vip.iqiyi.com:443

https://tc.vip.iqiyi.com:443 "GET /taskCenter/task/queryUserTask?P00001=e820tuseCNEOy2CX3CUaypzrreLLeBPm1iQcpm21m2pQgqt3B24UiEhcCT2bLGsLVRlK6d3&autoSign=yes HTTP/1.1" 200 None

'data'

Starting new HTTPS connection (1): iface2.iqiyi.com:443

https://iface2.iqiyi.com:443 "GET /aggregate/3.0/lottery_activity?lottery_chance=1&app_k=b398b8ccbaeacca840073a7ee9b7e7e6&app_v=11.6.5&platform_id=10&dev_os=8.0.0&dev_ua=FRD-AL10&net_sts=1&qyid=2655b332a116d2247fac3dd66a5285011102&psp_uid=2393377894&psp_cki=e820tuseCNEOy2CX3CUaypzrreLLeBPm1iQcpm21m2pQgqt3B24UiEhcCT2bLGsLVRlK6d3&psp_status=3&secure_v=1&secure_p=GPhone&req_sn=1617779991863 HTTP/1.1" 200 61

Starting new HTTPS connection (1): tc.vip.iqiyi.com:443

https://tc.vip.iqiyi.com:443 "GET /taskCenter/task/queryUserTask?P00001=e820tuseCNEOy2CX3CUaypzrreLLeBPm1iQcpm21m2pQgqt3B24UiEhcCT2bLGsLVRlK6d3 HTTP/1.1" 200 None

Starting new HTTPS connection (1): tc.vip.iqiyi.com:443

https://tc.vip.iqiyi.com:443 "GET /taskCenter/task/joinTask?P00001=e820tuseCNEOy2CX3CUaypzrreLLeBPm1iQcpm21m2pQgqt3B24UiEhcCT2bLGsLVRlK6d3&taskCode=a7f02e895ccbf416&platform=bb136ff4276771f3&lang=zh_CN HTTP/1.1" 200 None

Starting new HTTPS connection (1): tc.vip.iqiyi.com:443

https://tc.vip.iqiyi.com:443 "GET /taskCenter/task/joinTask?P00001=e820tuseCNEOy2CX3CUaypzrreLLeBPm1iQcpm21m2pQgqt3B24UiEhcCT2bLGsLVRlK6d3&taskCode=b6e688905d4e7184&platform=bb136ff4276771f3&lang=zh_CN HTTP/1.1" 200 None

Starting new HTTPS connection (1): tc.vip.iqiyi.com:443

https://tc.vip.iqiyi.com:443 "GET /taskCenter/task/queryUserTask?P00001=e820tuseCNEOy2CX3CUaypzrreLLeBPm1iQcpm21m2pQgqt3B24UiEhcCT2bLGsLVRlK6d3 HTTP/1.1" 200 None

Starting new HTTPS connection (1): tc.vip.iqiyi.com:443

https://tc.vip.iqiyi.com:443 "GET /taskCenter/task/joinTask?P00001=e820tuseCNEOy2CX3CUaypzrreLLeBPm1iQcpm21m2pQgqt3B24UiEhcCT2bLGsLVRlK6d3&taskCode=a7f02e895ccbf416&platform=bb136ff4276771f3&lang=zh_CN HTTP/1.1" 200 None

Starting new HTTPS connection (1): tc.vip.iqiyi.com:443

https://tc.vip.iqiyi.com:443 "GET /taskCenter/task/joinTask?P00001=e820tuseCNEOy2CX3CUaypzrreLLeBPm1iQcpm21m2pQgqt3B24UiEhcCT2bLGsLVRlK6d3&taskCode=b6e688905d4e7184&platform=bb136ff4276771f3&lang=zh_CN HTTP/1.1" 200 None

Starting new HTTPS connection (1): tc.vip.iqiyi.com:443

https://tc.vip.iqiyi.com:443 "GET /taskCenter/task/queryUserTask?P00001=e820tuseCNEOy2CX3CUaypzrreLLeBPm1iQcpm21m2pQgqt3B24UiEhcCT2bLGsLVRlK6d3 HTTP/1.1" 200 None

Starting new HTTPS connection (1): tc.vip.iqiyi.com:443

https://tc.vip.iqiyi.com:443 "GET /taskCenter/task/joinTask?P00001=e820tuseCNEOy2CX3CUaypzrreLLeBPm1iQcpm21m2pQgqt3B24UiEhcCT2bLGsLVRlK6d3&taskCode=a7f02e895ccbf416&platform=bb136ff4276771f3&lang=zh_CN HTTP/1.1" 200 None

Starting new HTTPS connection (1): tc.vip.iqiyi.com:443

https://tc.vip.iqiyi.com:443 "GET /taskCenter/task/joinTask?P00001=e820tuseCNEOy2CX3CUaypzrreLLeBPm1iQcpm21m2pQgqt3B24UiEhcCT2bLGsLVRlK6d3&taskCode=b6e688905d4e7184&platform=bb136ff4276771f3&lang=zh_CN HTTP/1.1" 200 None

Starting new HTTPS connection (1): tc.vip.iqiyi.com:443

https://tc.vip.iqiyi.com:443 "GET /taskCenter/task/queryUserTask?P00001=e820tuseCNEOy2CX3CUaypzrreLLeBPm1iQcpm21m2pQgqt3B24UiEhcCT2bLGsLVRlK6d3 HTTP/1.1" 200 None

Starting new HTTPS connection (1): tc.vip.iqiyi.com:443

https://tc.vip.iqiyi.com:443 "GET /taskCenter/task/joinTask?P00001=e820tuseCNEOy2CX3CUaypzrreLLeBPm1iQcpm21m2pQgqt3B24UiEhcCT2bLGsLVRlK6d3&taskCode=a7f02e895ccbf416&platform=bb136ff4276771f3&lang=zh_CN HTTP/1.1" 200 None

Starting new HTTPS connection (1): tc.vip.iqiyi.com:443

https://tc.vip.iqiyi.com:443 "GET /taskCenter/task/joinTask?P00001=e820tuseCNEOy2CX3CUaypzrreLLeBPm1iQcpm21m2pQgqt3B24UiEhcCT2bLGsLVRlK6d3&taskCode=b6e688905d4e7184&platform=bb136ff4276771f3&lang=zh_CN HTTP/1.1" 200 None

Starting new HTTPS connection (1): tc.vip.iqiyi.com:443

https://tc.vip.iqiyi.com:443 "GET /taskCenter/task/queryUserTask?P00001=e820tuseCNEOy2CX3CUaypzrreLLeBPm1iQcpm21m2pQgqt3B24UiEhcCT2bLGsLVRlK6d3 HTTP/1.1" 200 None

Starting new HTTPS connection (1): tc.vip.iqiyi.com:443

https://tc.vip.iqiyi.com:443 "GET /taskCenter/task/joinTask?P00001=e820tuseCNEOy2CX3CUaypzrreLLeBPm1iQcpm21m2pQgqt3B24UiEhcCT2bLGsLVRlK6d3&taskCode=a7f02e895ccbf416&platform=bb136ff4276771f3&lang=zh_CN HTTP/1.1" 200 None

Starting new HTTPS connection (1): tc.vip.iqiyi.com:443

https://tc.vip.iqiyi.com:443 "GET /taskCenter/task/joinTask?P00001=e820tuseCNEOy2CX3CUaypzrreLLeBPm1iQcpm21m2pQgqt3B24UiEhcCT2bLGsLVRlK6d3&taskCode=b6e688905d4e7184&platform=bb136ff4276771f3&lang=zh_CN HTTP/1.1" 200 None

Starting new HTTPS connection (1): tc.vip.iqiyi.com:443

https://tc.vip.iqiyi.com:443 "GET /taskCenter/task/queryUserTask?P00001=e820tuseCNEOy2CX3CUaypzrreLLeBPm1iQcpm21m2pQgqt3B24UiEhcCT2bLGsLVRlK6d3 HTTP/1.1" 200 None

Starting new HTTPS connection (1): tc.vip.iqiyi.com:443

https://tc.vip.iqiyi.com:443 "GET /taskCenter/task/joinTask?P00001=e820tuseCNEOy2CX3CUaypzrreLLeBPm1iQcpm21m2pQgqt3B24UiEhcCT2bLGsLVRlK6d3&taskCode=a7f02e895ccbf416&platform=bb136ff4276771f3&lang=zh_CN HTTP/1.1" 200 None

Starting new HTTPS connection (1): tc.vip.iqiyi.com:443

https://tc.vip.iqiyi.com:443 "GET /taskCenter/task/joinTask?P00001=e820tuseCNEOy2CX3CUaypzrreLLeBPm1iQcpm21m2pQgqt3B24UiEhcCT2bLGsLVRlK6d3&taskCode=b6e688905d4e7184&platform=bb136ff4276771f3&lang=zh_CN HTTP/1.1" 200 None

Starting new HTTP connection (1): serv.vip.iqiyi.com:80

http://serv.vip.iqiyi.com:80 "GET /vipgrowth/query.action?P00001=e820tuseCNEOy2CX3CUaypzrreLLeBPm1iQcpm21m2pQgqt3B24UiEhcCT2bLGsLVRlK6d3 HTTP/1.1" 200 None

检测【爱奇艺】脚本到配置文件包含模板配置,进行跳过

----------已检测到正确的配置，并开始执行 VQQ_COOKIE_LIST 签到----------

Starting new HTTPS connection (1): access.video.qq.com:443

https://access.video.qq.com:443 "GET /user/auth_refresh?vappid=11059694&vsecret=fdf61a6be0aad57132bc5cdf78ac30145b6cd2c1470b0cfe&type=qq&g_tk=&g_vstk=554474756&g_actk=203302171&callback=jQuery191021155823210844815_1617779459182&_=1617779459183 HTTP/1.1" 200 275

Starting new HTTP connection (1): v.qq.com:80

http://v.qq.com:80 "GET /x/bu/mobile_checkin?isDarkMode=0&uiType=REGULAR HTTP/1.1" 200 7988

Starting new HTTPS connection (1): vip.video.qq.com:443

https://vip.video.qq.com:443 "GET /fcgi-bin/comm_cgi?name=hierarchical_task_system&cmd=2&_=1617780061094 HTTP/1.1" 200 46

腾讯视频 'NoneType' object has no attribute 'group'

检测【腾讯视频】脚本到配置文件包含模板配置,进行跳过

----------已检测到正确的配置，并开始执行 MGTV_PARAMS_LIST 签到----------

检测【芒果TV】脚本到配置文件包含模板配置,进行跳过

检测【芒果TV】脚本到配置文件包含模板配置,进行跳过

----------已检测到正确的配置，并开始执行 KGQQ_COOKIE_LIST 签到----------

检测【全民K歌】脚本到配置文件包含模板配置,进行跳过

检测【全民K歌】脚本到配置文件包含模板配置,进行跳过

----------已检测到正确的配置，并开始执行 MUSIC163_ACCOUNT_LIST 签到----------

检测【网易云音乐】脚本到配置文件包含模板配置,进行跳过

检测【网易云音乐】脚本到配置文件包含模板配置,进行跳过

----------已检测到正确的配置，并开始执行 BILIBILI_COOKIE_LIST 签到----------

检测【Bilibili】脚本到配置文件包含模板配置,进行跳过

检测【Bilibili】脚本到配置文件包含模板配置,进行跳过

----------已检测到正确的配置，并开始执行 YOUDAO_COOKIE_LIST 签到----------

检测【有道云笔记】脚本到配置文件包含模板配置,进行跳过

检测【有道云笔记】脚本到配置文件包含模板配置,进行跳过

----------已检测到正确的配置，并开始执行 FMAPP_ACCOUNT_LIST 签到----------

检测【Fa米家 APP】脚本到配置文件包含模板配置,进行跳过

检测【Fa米家 APP】脚本到配置文件包含模板配置,进行跳过

----------已检测到正确的配置，并开始执行 BAIDU_URL_SUBMIT_LIST 签到----------

检测【百度站点提交】脚本到配置文件包含模板配置,进行跳过

检测【百度站点提交】脚本到配置文件包含模板配置,进行跳过

----------已检测到正确的配置，并开始执行 LIANTONG_ACCOUNT_LIST 签到----------

检测【联通营业厅】脚本到配置文件包含模板配置,进行跳过

检测【联通营业厅】脚本到配置文件包含模板配置,进行跳过

----------已检测到正确的配置，并开始执行 ONEPLUSBBS_COOKIE_LIST 签到----------

检测【一加手机社区官方论坛】脚本到配置文件包含模板配置,进行跳过

检测【一加手机社区官方论坛】脚本到配置文件包含模板配置,进行跳过

----------已检测到正确的配置，并开始执行 SMZDM_COOKIE_LIST 签到----------

检测【什么值得买】脚本到配置文件包含模板配置,进行跳过

检测【什么值得买】脚本到配置文件包含模板配置,进行跳过

----------已检测到正确的配置，并开始执行 TIEBA_COOKIE_LIST 签到----------

检测【百度贴吧】脚本到配置文件包含模板配置,进行跳过

检测【百度贴吧】脚本到配置文件包含模板配置,进行跳过

----------已检测到正确的配置，并开始执行 V2EX_COOKIE_LIST 签到----------

检测【V2EX 论坛】脚本到配置文件包含模板配置,进行跳过

检测【V2EX 论坛】脚本到配置文件包含模板配置,进行跳过

----------已检测到正确的配置，并开始执行 WWW2NZZ_COOKIE_LIST 签到----------

检测【咔叽网单】脚本到配置文件包含模板配置,进行跳过

检测【咔叽网单】脚本到配置文件包含模板配置,进行跳过

----------已检测到正确的配置，并开始执行 ACFUN_ACCOUNT_LIST 签到----------

检测【AcFun】脚本到配置文件包含模板配置,进行跳过

检测【AcFun】脚本到配置文件包含模板配置,进行跳过

----------已检测到正确的配置，并开始执行 MIMOTION_ACCOUNT_LIST 签到----------

检测【小米运动】脚本到配置文件包含模板配置,进行跳过

检测【小米运动】脚本到配置文件包含模板配置,进行跳过

----------已检测到正确的配置，并开始执行 CLOUD189_ACCOUNT_LIST 签到----------

检测【天翼云盘】脚本到配置文件包含模板配置,进行跳过

检测【天翼云盘】脚本到配置文件包含模板配置,进行跳过

----------已检测到正确的配置，并开始执行 WPS_COOKIE_LIST 签到----------

检测【WPS】脚本到配置文件包含模板配置,进行跳过

检测【WPS】脚本到配置文件包含模板配置,进行跳过

----------已检测到正确的配置，并开始执行 POJIE_COOKIE_LIST 签到----------

检测【吾爱破解】脚本到配置文件包含模板配置,进行跳过

检测【吾爱破解】脚本到配置文件包含模板配置,进行跳过

----------已检测到正确的配置，并开始执行 MEIZU_COOKIE_LIST 签到----------

检测【MEIZU社区】脚本到配置文件包含模板配置,进行跳过

检测【MEIZU社区】脚本到配置文件包含模板配置,进行跳过

----------已检测到正确的配置，并开始执行 PICACOMIC_ACCOUNT_LIST 签到----------

检测【哔咔漫画】脚本到配置文件包含模板配置,进行跳过

检测【哔咔漫画】脚本到配置文件包含模板配置,进行跳过

----------已检测到正确的配置，并开始执行 CAIYUN_COOKIE_LIST 签到----------

检测【和彩云】脚本到配置文件包含模板配置,进行跳过

检测【和彩云】脚本到配置文件包含模板配置,进行跳过

----------已检测到正确的配置，并开始执行 ZHIYOO_COOKIE_LIST 签到----------

检测【智友邦】脚本到配置文件包含模板配置,进行跳过

检测【智友邦】脚本到配置文件包含模板配置,进行跳过

----------已检测到正确的配置，并开始执行 WEIBO_COOKIE_LIST 签到----------

检测【微博】脚本到配置文件包含模板配置,进行跳过

检测【微博】脚本到配置文件包含模板配置,进行跳过

----------已检测到正确的配置，并开始执行 DUOKAN_COOKIE_LIST 签到----------

检测【多看阅读】脚本到配置文件包含模板配置,进行跳过

检测【多看阅读】脚本到配置文件包含模板配置,进行跳过

----------已检测到正确的配置，并开始执行 CSDN_COOKIE_LIST 签到----------

检测【CSDN】脚本到配置文件包含模板配置,进行跳过

检测【CSDN】脚本到配置文件包含模板配置,进行跳过

----------已检测到正确的配置，并开始执行 WZYD_DATA_LIST 签到----------

检测【王者营地】脚本到配置文件包含模板配置,进行跳过

检测【王者营地】脚本到配置文件包含模板配置,进行跳过

----------已检测到正确的配置，并开始执行 CITY_NAME_LIST 签到----------

Starting new HTTP connection (1): t.weather.itboy.net:80

http://t.weather.itboy.net:80 "GET /api/weather/city/101280101 HTTP/1.1" 200 None

Starting new HTTP connection (1): open.iciba.com:80

http://open.iciba.com:80 "GET /dsapi HTTP/1.1" 301 162

http://open.iciba.com:80 "GET /dsapi/ HTTP/1.1" 200 None

Starting new HTTPS connection (1): api.github.com:443

https://api.github.com:443 "GET /repos/Sitoi/dailycheckin/issues?state=open&labels=%E9%80%9A%E7%9F%A5 HTTP/1.1" 200 2

server 酱推送开始

Starting new HTTPS connection (1): sc.ftqq.com:443

https://sc.ftqq.com:443 "POST /SCU144141Ta2e0e29a42e2c5d2cb5fd8f788c1acd65ff187da464c4.send HTTP/1.1" 609 1293

Pushplus 推送开始

Starting new HTTP connection (1): www.pushplus.plus:80

http://www.pushplus.plus:80 "POST /send HTTP/1.1" 200 None

Response RequestId:def9a1ac-ae66-4b0a-9091-d0a45e67c9f5 RetMsg:null

END RequestId:def9a1ac-ae66-4b0a-9091-d0a45e67c9f5

Report RequestId:def9a1ac-ae66-4b0a-9091-d0a45e67c9f5 Duration:71658ms Memory:128MB MemUsage:17.425781MB

**Comment by Sitoi** [comment]
可能是你 cookie 有问题把
