### ISSUE TITLE
多看阅读能否增加自动延期功能

### ISSUE THREAD

**Issue by ChellyL** [Sitoi/dailycheckin#136]
如题，多看的豆子7天到期后可以延期一次，能不能增加 检测当日是否有到期的豆子并延期 的功能？

**Comment by cnwxi** [comment]
同需求，不过自己实现了
![344f9b6e722cea8d2cd89270e33e29a](https://user-images.githubusercontent.com/45331556/157443590-f829d14d-2d8e-44f0-9707-8631602b19a7.jpg)

**Comment by cnwxi** [comment]
> 如题，多看的豆子7天到期后可以延期一次，能不能增加 检测当日是否有到期的豆子并延期 的功能？
同需求，自己改了改，能在原项目实现最好
![344f9b6e722cea8d2cd89270e33e29a](https://user-images.githubusercontent.com/45331556/157443881-c0151d34-b10b-480c-9c45-c5ad899fdd81.jpg)

**Comment by Sitoi** [comment]
已添加
