### ISSUE TITLE
安装依赖时报错 no such package

### ISSUE THREAD

**Issue by GameOverUI** [Sitoi/dailycheckin#138]
ERROR: unable to select packages:
  bizCode (no such package):
    required by: world[bizCode]
  bizMsg (no such package):
    required by: world[bizMsg]
  lxml (no such package):
    required by: world[lxml]

缺少bizCode、bizMsg、lxml
尝试过修改apk软件源的版本号，切换了多个版本仍显示同样的问题

**Comment by GameOverUI** [comment]
这次安装的环境与我前几次安装的环境一模一样，我最后一次是在去年下半年安装的，不知为何这次就不行了

**Comment by Sitoi** [comment]
最新青龙文档解决办法已更新

**Comment by Sitoi** [comment]
https://blog.csdn.net/u013557771/article/details/121601973

**Comment by TheKing1991** [comment]
你解决了吗？

**Comment by zero617** [comment]
请问解决了吗？
