### ISSUE TITLE
更新最新版本后 多看阅读 任务 腾讯云超时

### ISSUE THREAD

**Issue by wzgrx** [Sitoi/dailycheckin#139]
https://www.duokan.com:443 "POST /events/common_task_gift HTTP/1.1" 200 None

Starting new HTTPS connection (1): www.duokan.com:443

ERROR RequestId:917cb212-eab9-4721-b451-44184aaa0d49 Result:{"errorCode":-1,"errorMessage":"Invoking task timed out after 900 seconds","statusCode":433}

END RequestId:917cb212-eab9-4721-b451-44184aaa0d49

Report RequestId:917cb212-eab9-4721-b451-44184aaa0d49 Duration:900000ms Memory:128MB MemUsage:22.948471MB

最多900秒

**Comment by hhtnFxQVwQntBLkULKjy** [comment]
本人也有这个问题
