### ISSUE TITLE
爱奇艺签到启动失败

### ISSUE THREAD

**Issue by NoString** [Sitoi/dailycheckin#139]
## 1.关于你要提交的问题

Q：是否搜索了 issue（包括已关闭的issue）

- [x] 没有类似的 issue 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [x] 方法一：本地安装 Python
- [ ] 方法二：Docker
- [ ] 方法三：腾讯云函数
- [ ] 方法四：GitHub Actions

## 3. 详细叙述

config目录：https://gitee.com/zhssss/image/raw/master/img/20210411202408.png

### (1) 具体问题
A：
爱奇艺按照提供的格式来配置，报错，使用JSON在线解析提示28行有解析错误，但是从爱奇艺获取的cookie就是这样，不知怎么改。
这是具体配置文件：https://gitee.com/zhssss/image/raw/master/img/20210411203010.json
JSON报错：https://gitee.com/zhssss/image/raw/master/img/20210411203139.png
by the way
json里面用不到的签到是不是可以删掉
例如，我用不到CSDN，是不是可以直接删掉
`  "CSDN_COOKIE_LIST": [
    {
      "csdn_cookie": "uuid_tt_dd=xxxxxx; _ga=xxxxxx; UserName=xxxxxx; UserInfo=xxxxxx; UserToken=xxxxxx; UserNick=xxxxxx; AU=768; UN=xxxxxx; BT=xxxxxx; p_uid=xxxxxx; Hm_up_6bcd52f51e9b3dce32bec4a3997715ac=xxxxxx; Hm_ct_6bcd52f51e9b3dce32bec4a3997715ac=xxxxxx; Hm_lvt_6bcd52f51e9b3dce32bec4a3997715ac=xxxxxx dc_sid=xxxxxx; c_segment=xxxxxx; dc_session_id=xxxxxx; csrfToken=xxxxxx; c_first_ref=xxxxxx; c_first_page=xxxxxx; c_page_id=xxxxxx; announcement-new=xxxxxx; log_Id_click=xxxxxx; c_pref=xxxxxx; c_ref=xxxxxx; dc_tos=xxxxxx; log_Id_pv=xxxxxx; log_Id_view=xxxxxx"
    },
    {
      "csdn_cookie": "多账号 cookie 填写，请参考上面，cookie 以实际获取为准（遇到特殊字符如双引号\" 请加反斜杠转义）"
    }
  ],`
### (2) 详细日志

A：
[root@trojan dailycheckin]# python3 index.py
Traceback (most recent call last):
  File "index.py", line 59, in <module>
    main_handler(event=None, context=None)
  File "index.py", line 19, in main_handler
    data = json.loads(f.read())
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 28 column 197 (char 713)

**Comment by Sitoi** [comment]
报的错是不符合json 规范 需要把 cookie 转义一下
