### ISSUE TITLE
【最新代码贴吧签到失败】BUG

### ISSUE THREAD

**Issue by tanzl** [Sitoi/dailycheckin#140]
## 1.关于你要提交的问题

Q：是否搜索了 issue（包括已关闭的issue）

- [x] 没有类似的 issue 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装 Python
- [ ] 方法二：Docker
- [ ] 方法三：腾讯云函数
- [x] 方法四：GitHub Actions

### (1) 具体问题

A：之前签到没问题的，最新的代码就报错了。我看到有人提[腾讯视频](https://github.com/Sitoi/dailycheckin/issues/133)
也是这个问题，我都换了几次cookie了还是一样
### (2) 详细日志

A：
----------执行失败 【百度贴吧】签到 : 错误日志如下:----------
'NoneType' object has no attribute 'group'

**Comment by Sitoi** [comment]
看不出什么信息 ，加微信私聊吧

**Comment by Sitoi** [comment]
已解决，原因是贴吧数量太少导致的。
