### ISSUE TITLE
多看阅读建议

### ISSUE THREAD

**Issue by shilinjin** [Sitoi/dailycheckin#142]
多看那里很感谢作者加入了新的功能，我还有一个建议。能不能加一个变量，可以选择是否免费领取每天的书。

**Comment by wzgrx** [comment]
楼主是用什么抓的多看cookie啊

**Comment by shilinjin** [comment]
用电脑抓的。手机有小黄鸟我用不习惯。

**Comment by wzgrx** [comment]
> 用电脑抓的。手机有小黄鸟我用不习惯。

好的，谢谢
