### ISSUE TITLE
iqiyi相关问题

### ISSUE THREAD

**Issue by feishi12121** [Sitoi/dailycheckin#143]
爱奇艺是web端cookie还能用嘛？教程里又是将iqiyi归于web端，又是要求抓app的header的token，Readme里又归类成app端。。。app端请求多，随便一个链接点进去找不到请求头的token字段，这边要抓的token是一系列参数的集合？还是单独一个字段？能否把教程的iqiyi网页端cookie抓取换成app端？
![QQ图片20220322225740](https://user-images.githubusercontent.com/31927191/159511826-010e67b5-bfed-4a7e-b437-39ab8317e60c.jpg)

**Comment by Sitoi** [comment]
web 也可以
