### ISSUE TITLE
B站银瓜子兑换功能有问题

### ISSUE THREAD

**Issue by github-h** [Sitoi/dailycheckin#149]
版本为 0.3.7
我并不想开启银瓜子兑换功能

所以我的配置文件为
`"silver2coin": false`

但签到的时候就会报错
```
「Bilibili」
local variable 's2c_msg' referenced before assignment
```

**Comment by cnwxi** [comment]
> 版本为 0.3.7
> 我并不想开启银瓜子兑换功能
> 
> 所以我的配置文件为
> `"silver2coin": false`
> 
> 但签到的时候就会报错
> ```
> 「Bilibili」
> local variable 's2c_msg' referenced before assignment
> ```

![Screenshot_20220411-102300_Samsung Internet.jpg](https://user-images.githubusercontent.com/45331556/162654564-cabe67ec-9a58-4020-a941-e60b9c4f8091.jpg)
自己改一下。

**Comment by github-h** [comment]
感谢！
