### ISSUE TITLE
【Fa米家和v2ex】没有cookie和cookie失效

### ISSUE THREAD

**Issue by Shen-Yu** [Sitoi/dailycheckin#149]
## 1.关于你要提交的问题

Q：是否搜索了 issue（包括已关闭的issue）

- [x] 没有类似的 issue 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装 Python
- [ ] 方法二：Docker
- [ ] 方法三：腾讯云函数
- [x] 方法四：GitHub Actions

### (1) 具体问题

A：安卓版的Fa米家接口好像并没有传cookie，另外v2ex一直报cookie失效，不知是否和目前DNS污染被墙了有关系。

### (2) 详细日志

A：

**Comment by Shen-Yu** [comment]
多看阅读签到报错：`Expecting value: line 1 column 1 (char 0)`

**Comment by Sitoi** [comment]
fa 米家 签到一次就有 cookie了
