### ISSUE TITLE
全民k歌好像不行，请大佬查看一下吧

### ISSUE THREAD

**Issue by DUKISS** [Sitoi/dailycheckin#15]
## 1.关于你要提交的问题

Q：是否搜索了 issue（包括已关闭的issue）

- [ ] 没有类似的 issue 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装 Python
- [ ] 方法二：Docker
- [x] 方法三：腾讯云函数
- [ ] 方法四：GitHub Actions

### (1) 具体问题

A：

### (2) 详细日志

A：

**Comment by DUKISS** [comment]
全民k歌不能签到

**Comment by Sitoi** [comment]
报错信息
