### ISSUE TITLE
pushplus请求地址已改

### ISSUE THREAD

**Issue by CitrusFlavored** [Sitoi/dailycheckin#150]
作者还没有更新，可以自行修改utils/message.py 的121行，把地址改为 http://pushplus.hxtrip.com/send 即可。
我使用的是docker版，进入容器：docker exec -it dailycheckin sh，修改 vi /dailycheckin/utils/message.py

**Comment by Agameadream** [comment]
> 作者还没有更新，可以自行修改utils/message.py 的121行，把地址改为 http://pushplus.hxtrip.com/send 即可。
> 我使用的是docker版，进入容器：docker exec -it dailycheckin sh，修改 vi /dailycheckin/utils/message.py

https://www.pushplus.plus/这是新版的地址吧，你那个是之前的。

**Comment by CitrusFlavored** [comment]
> > 作者还没有更新，可以自行修改utils/message.py 的121行，把地址改为 http://pushplus.hxtrip.com/send 即可。
> > 我使用的是docker版，进入容器：docker exec -it dailycheckin sh，修改 vi /dailycheckin/utils/message.py
> 
> [https://www.pushplus.plus/这是新版的地址吧，你那个是之前的。](https://www.pushplus.plus/%E8%BF%99%E6%98%AF%E6%96%B0%E7%89%88%E7%9A%84%E5%9C%B0%E5%9D%80%E5%90%A7%EF%BC%8C%E4%BD%A0%E9%82%A3%E4%B8%AA%E6%98%AF%E4%B9%8B%E5%89%8D%E7%9A%84%E3%80%82)

有可能，我直接右键搜索的pushplus，进去的就是http://pushplus.hxtrip.com/这个地址，然后得到Token后填入发现收不到推送，然后看的文档的地址是那个，就改成了那个。
