### ISSUE TITLE
【WPS】邀请用户失败

### ISSUE THREAD

**Issue by pucqx** [Sitoi/dailycheckin#151]
## 1.关于你要提交的问题

Q：是否搜索了 issue（包括已关闭的issue）

- [x] 没有类似的 issue 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [x] 方法一：本地安装 Python
- [ ] 方法二：Docker
- [ ] 方法三：腾讯云函数
- [ ] 方法四：GitHub Actions

### (1) 具体问题

A：WPS邀请用户失败，全都返回error，最后结果说邀请10人，实则都没邀请到，小程序里面也显示已邀请0人

### (2) 详细日志

A：邀请对象ID=01, Result: error
邀请对象ID=02, Result: error
邀请对象ID=03, Result: error
邀请对象ID=04, Result: error
邀请对象ID=05, Result: error
邀请对象ID=06, Result: error
邀请对象ID=07, Result: error
邀请对象ID=08, Result: error
邀请对象ID=09, Result: error
邀请对象ID=10, Result: error
用户名称: 朴尘轻轩
会员积分: 0
稻米数量: 19
稻壳会员: 2021-04-29 06:07:02
WPS会员: 2021-06-23 17:48:13
网页签到: 今日已完成签到
稻壳签到: 重复签到
本期连续签到: 13 天
拥有补签卡: 0 张
已领取礼物: 3天稻壳会员 
礼物信息: None
小程序签到: ParamData Empty
邀请用户: 成功邀请 10 人

**Comment by Alan996** [comment]
全网都不行了，

**Comment by cyczq11** [comment]
我也不行了~~

**Comment by Inliang** [comment]
今天邀请了五个

**Comment by leic4u** [comment]
能把小号的sid也设置到secrets里面吗，这样大家可以自己配自己申请的小号
