### ISSUE TITLE
多看阅读签到报错

### ISSUE THREAD

**Issue by ChellyL** [Sitoi/dailycheckin#151]
用小黄鸟抓的多看cookie，今天运行脚本时会提示

----------开始执行「多看阅读」签到----------
第 1 个账号: ❌❌❌❌❌
Expecting value: line 1 column 1 (char 0)

但是IOS的账号可以正常签到

**Comment by cnwxi** [comment]
> 用小黄鸟抓的多看cookie，今天运行脚本时会提示
> 
> ----------开始执行「多看阅读」签到---------- 第 1 个账号: ❌❌❌❌❌ Expecting value: line 1 column 1 (char 0)
> 
> 但是IOS的账号可以正常签到

用小黄鸟抓包结果中 cookie 各字段之间是用 ";"（半角分号）隔开的，但是在这个项目中解析cookie是按”; “（半角分号+空格）进行分割，请自行将小黄鸟抓包结果中";"替换为"; "。
`duokan_cookie = {item.split("=")[0]: item.split("=")[1] for item in self.check_item.get("cookie").split("; ")}`

**Comment by ChellyL** [comment]
非常感谢，问题解决了
