### ISSUE TITLE
多看签到失败

### ISSUE THREAD

**Issue by avbnmz** [Sitoi/dailycheckin#152]
### 多看版本：6.6.0.20
![image](https://user-images.githubusercontent.com/102004512/162988704-48d9ef4b-f350-4f71-b817-fdf3c723ca8b.png)
![image](https://user-images.githubusercontent.com/102004512/162989718-4b8a0a3e-1193-4699-9c0c-4f534f103ffc.png)

### config.json文件已经使用https://www.json.cn/检查过了，没有问题
![屏幕截图 2022-04-12 224454](https://user-images.githubusercontent.com/102004512/162989172-739b7f74-2e50-410b-831b-f0d2bc61d155.png)

**Comment by cnwxi** [comment]
> ### 部署方式：Docker
> ### dailycheckin 0.3.7
> ### 使用小黄鸟抓的包
> ### 多看版本：6.6.0.20
> ![image](https://user-images.githubusercontent.com/102004512/162988704-48d9ef4b-f350-4f71-b817-fdf3c723ca8b.png) ![image](https://user-images.githubusercontent.com/102004512/162989718-4b8a0a3e-1193-4699-9c0c-4f534f103ffc.png)
> 
> ### config.json文件已经使用[https://www.json.cn/检查过了，没有问题](https://www.json.cn/%E6%A3%80%E6%9F%A5%E8%BF%87%E4%BA%86%EF%BC%8C%E6%B2%A1%E6%9C%89%E9%97%AE%E9%A2%98)
> ![屏幕截图 2022-04-12 224454](https://user-images.githubusercontent.com/102004512/162989172-739b7f74-2e50-410b-831b-f0d2bc61d155.png)

 看[这条issue](https://github.com/Sitoi/dailycheckin/issues/151)

**Comment by avbnmz** [comment]
感谢已经解决，我发现安卓抓的包cookie内容和ios抓取的不一样（里面会有安卓没有的键值对，比如user_name），安卓抓的cookie按照要求修改后不会报错，但是一直运行不出结果，只能手动停止，但是ios抓的cookie直接就可以用，最后我直接抓的ios的cookie解决的。
![image](https://user-images.githubusercontent.com/102004512/163114774-2de6ed91-14b9-4057-a723-c0f4dece896a.png)

**Comment by avbnmz** [comment]
> > ### 部署方式：Docker
> > ### dailycheckin 0.3.7
> > ### 使用小黄鸟抓的包
> > ### 多看版本：6.6.0.20
> > ![image](https://user-images.githubusercontent.com/102004512/162988704-48d9ef4b-f350-4f71-b817-fdf3c723ca8b.png) ![image](https://user-images.githubusercontent.com/102004512/162989718-4b8a0a3e-1193-4699-9c0c-4f534f103ffc.png)
> > ### config.json文件已经使用[https://www.json.cn/检查过了，没有问题](https://www.json.cn/%E6%A3%80%E6%9F%A5%E8%BF%87%E4%BA%86%EF%BC%8C%E6%B2%A1%E6%9C%89%E9%97%AE%E9%A2%98)
> > ![屏幕截图 2022-04-12 224454](https://user-images.githubusercontent.com/102004512/162989172-739b7f74-2e50-410b-831b-f0d2bc61d155.png)
> 
> 看[这条issue](https://github.com/Sitoi/dailycheckin/issues/151)

感谢，
