### ISSUE TITLE
B站签到无法获得全部经验

### ISSUE THREAD

**Issue by NOwin111** [Sitoi/dailycheckin#153]
目前每天签到只有5经验,有经验的只有分享视频成功。docker和青龙，结果一样

推送：
漫画签到: 签到成功
直播签到: 签到成功，3000点用户经验,2根辣条，特别信息:再签到7天可以获得50根辣条，本月已签到13天
登陆任务: 今日已登陆
观看视频: 任务失败
分享任务: 分享《从世界前五到厕所都修不起？印度到底经历了什么？（下）》成功
瓜子兑换: 银瓜子余额不足
投币任务: 今日成功投币0/5个
今日经验: 5
当前经验: 16479
升级还需: 2464天
硬币数量: 839
金瓜子数: 0
银瓜子数: 496

设置：
      "coin_num": 5,
      "coin_type": 1,
      "silver2coin": true

**Comment by NOwin111** [comment]
>

**Comment by mayjack0312** [comment]
我一天是15经验（币没满的情况下）
「Bilibili」
帐号信息: xxxx
漫画签到: 今天已经签到过了
直播签到: 今日已签到过,无法重复签到
登陆任务: 今日已登陆
观看视频: 任务失败
分享任务: 分享《【4月】恋爱游戏世界对路人角色很不友好 02【独家正版】》成功
瓜子兑换: 银瓜子余额不足
投币任务: 今日成功投币1/5个
今日经验: 15
当前经验: 17221
升级还需: 771天
硬币数量: 0
金瓜子数: 0
银瓜子数: 264
我是直接用的云函数

**Comment by cnwxi** [comment]
https://github.com/cnwxi/DaliyCheckin_PersonalModifed/blob/main/bilibili/main.py
