### ISSUE TITLE
报错信息

### ISSUE THREAD

**Issue by DUKISS** [Sitoi/dailycheckin#16]
报错信息

_Originally posted by @Sitoi in https://github.com/Sitoi/dailycheckin/issues/15#issuecomment-753588339_
填了cookie后没有任何反应，没有相关日志也没有报错信息。而cookie没问题，在以前的云函数里可以正常签到的。

**Comment by Sitoi** [comment]
没有任何报错信息的话 检查下配置文件吧

**Comment by niumingyuan** [comment]
希望加个截图例子 ，很错
