### ISSUE TITLE
网易云音乐和百度贴吧失效

### ISSUE THREAD

**Issue by ghost** [Sitoi/dailycheckin#161]
![11](https://user-images.githubusercontent.com/52023234/165225915-002434cd-33b5-4d57-868c-2e882def98ff.png)

**Comment by cnwxi** [comment]
> ![11](https://user-images.githubusercontent.com/52023234/165225915-002434cd-33b5-4d57-868c-2e882def98ff.png)

网易云早寄了，NeteaseCloudMusicTasks项目都建议不要继续使用了。
贴吧是因为api从http改成https了，你可以自己改一下。

**Comment by Sitoi** [comment]
ok
