### ISSUE TITLE
【docker】执行失败

### ISSUE THREAD

**Issue by HarrisonQi** [Sitoi/dailycheckin#162]
## 1.关于你要提交的问题

Q：是否搜索了 issue（包括已关闭的issue）

- [x] #93 尚未解决 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装 Python
- [x] 方法二：Docker
- [ ] 方法三：腾讯云函数
- [ ] 方法四：GitHub Actions

### (1) 具体问题

这个问题现在仍然存在, 使用命令
```bash
curl https://raw.githubusercontent.com/Sitoi/dailycheckin/main/docker_start.sh | bash
```

后执行
```bash
docker exec dailycheckin python3 index.py
```

会报错
```bash
Traceback (most recent call last):
  File "index.py", line 59, in <module>
    main_handler(event=None, context=None)
  File "index.py", line 18, in main_handler
    with open(os.path.join(os.path.dirname(__file__), "config/config.json"), "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'config/config.json'
```

期间没有其他操作, 仅执行了上述两行命令

### (2) 详细日志

A：报错日志:
```bash
Traceback (most recent call last):
  File "index.py", line 59, in <module>
    main_handler(event=None, context=None)
  File "index.py", line 18, in main_handler
    with open(os.path.join(os.path.dirname(__file__), "config/config.json"), "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'config/config.json'
```

**Comment by HarrisonQi** [comment]
发现生成的目录路径不是 `./config/config.json`, 而是 `./config.json`:
![image](https://user-images.githubusercontent.com/33210899/116064825-f801e880-a6b8-11eb-982f-76e49cf06010.png)


但是脚本读取的位置是 `./config/config.json`, 所以会出现找不到文件的情况. 

我手动将`config.json`移动至 `/config` 下成功, 

以下两种方式其一可解决该问题:
1. 调整下`https://raw.githubusercontent.com/Sitoi/dailycheckin/main/docker_start.sh`, 使`config.json`生成在正确的目录
2. 在文档中标注需要手动将`config.json`移动至`/config`下

**Comment by Sitoi** [comment]
已修复
