### ISSUE TITLE
用几天会停止自动签到

### ISSUE THREAD

**Issue by gqs4352** [Sitoi/dailycheckin#162]
我是使用docker 方式一安装，启动后用几天会停止自动签到，消息不推送了
![4b3f9d035d3aebb1ceda2c5b22456c4](https://user-images.githubusercontent.com/56287218/165277173-4e7ded46-d87d-47b5-9113-c4e970ff1938.jpg)
比如今天26号早上就没有推送消息， 然后我发现后又手动执行脚本
`docker exec -it dailycheckin dailycheckin`   
一般执行这个脚本后  会好几天，几天后又停止签到了

**Comment by gqs4352** [comment]
或者也可能是实际签到过了 只是没有推送

**Comment by Sitoi** [comment]
重启下容器
