### ISSUE TITLE
Bilibili s2c_msg在定义前引用

### ISSUE THREAD

**Issue by jzksnsjswkw** [Sitoi/dailycheckin#163]
bilibili line 324 定义 s2c_msg，若未开启银瓜子兑换则会在line 344报未定义
![image](https://user-images.githubusercontent.com/69855421/165328616-1d55c5e3-60af-4205-993b-9bb80b10a8d7.png)

**Comment by cnwxi** [comment]
因为作者是拿了我改的 我个人需求是开启硬币兑银瓜子，我后续修改了这部分 作者暂未修改
