### ISSUE TITLE
Action被GitHub给禁了怎么办？怎么恢复

### ISSUE THREAD

**Issue by hassanblog** [Sitoi/dailycheckin#165]

**Comment by verglas** [comment]
同。

**Comment by chern91552** [comment]
+1

**Comment by leechuy** [comment]
![image](https://user-images.githubusercontent.com/79011908/116782631-f66f6080-aabc-11eb-9019-97381318b163.png)
ni'm你们的是这样的吗 我也不行了

**Comment by Sitoi** [comment]
换方式
