### ISSUE TITLE
腾讯云函数不提供免费额度了 使用阿里云函数报错

### ISSUE THREAD

**Issue by Silentely** [Sitoi/dailycheckin#166]
因为云函数5月开始就不提供免费额度了，想转阿里云函数，但是我按照云函数的配置方法，配置好后测试函数提示以下错误，已经配置好了config.json    
`2022-04-29 00:11:31 6c5be911-9009-483a-bb07-480f02d841ec [ERROR] {'errorMessage': "Unable to import module 'index'", 'errorType': 'ImportModuleError', 'stackTrace': ["ImportError: No module named 'index'"]}
FC Invoke End RequestId: 6c5be911-9009-483a-bb07-480f02d841ec, Error: Unhandled function error`

**Comment by cnwxi** [comment]
![image](https://user-images.githubusercontent.com/45331556/165935251-57c4f13a-3367-4a05-a343-f86bb692eb81.png)
我试了下，没啥问题
检查下你的index.py文件呗
阿里云函数部署的时候没有这一步，直接用的默认的样例
![image](https://user-images.githubusercontent.com/45331556/165935745-c03de5d6-10d9-4e45-97a7-916ff38409c6.png)
你是不是删了忘记加了，对了阿里云和腾讯云的默认入口函数名称不一样

**Comment by Silentely** [comment]
我将腾讯云函数里的打包下载再上传到阿里云就可以运行了，我好像知道哪里错了  没有cd src，这一步  直接在根目录下pip3 install dailycheckin --upgrade -t .
