### ISSUE TITLE
'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by LeLeLittleBear** [Sitoi/dailycheckin#168]
## 1.关于你要提交的问题

Q：是否搜索了 issue（包括已关闭的issue）

- [ ] 没有类似的 issue 

Q：是否仔细阅读了教程

- [ ] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装 Python
- [1 ] 方法二：Docker
- [ ] 方法三：腾讯云函数
- [ ] 方法四：GitHub Actions

### (1) 具体问题

A：
执行报错，无日志输出
'str' object has no attribute 'get'
### (2) 详细日志

A：
----------已检测到正确的配置，并开始执行【爱奇艺】签到----------
----------开始执行【爱奇艺】签到 : 第 1 个账号----------
----------执行失败 【爱奇艺】签到 : 错误日志如下:----------
'str' object has no attribute 'get'
----------已检测到正确的配置，并开始执行【腾讯视频】签到----------
----------开始执行【腾讯视频】签到 : 第 1 个账号----------
----------执行失败 【腾讯视频】签到 : 错误日志如下:----------
'str' object has no attribute 'get'
----------开始执行【腾讯视频】签到 : 第 2 个账号----------
----------执行失败 【腾讯视频】签到 : 错误日志如下:----------
'str' object has no attribute 'get'
----------未检测到正确的配置，并跳过执行【芒果TV】签到----------
----------未检测到正确的配置，并跳过执行【全民K歌】签到----------
----------未检测到正确的配置，并跳过执行【网易云音乐】签到----------
----------已检测到正确的配置，并开始执行【Bilibili】签到----------
----------开始执行【Bilibili】签到 : 第 1 个账号----------
----------执行失败 【Bilibili】签到 : 错误日志如下:----------
'str' object has no attribute 'get'
----------开始执行【Bilibili】签到 : 第 2 个账号----------
----------执行失败 【Bilibili】签到 : 错误日志如下:----------
'str' object has no attribute 'get'
----------开始执行【Bilibili】签到 : 第 3 个账号----------
----------执行失败 【Bilibili】签到 : 错误日志如下:----------
'str' object has no attribute 'get'
----------开始执行【Bilibili】签到 : 第 4 个账号----------
----------执行失败 【Bilibili】签到 : 错误日志如下:----------
'str' object has no attribute 'get'
----------已检测到正确的配置，并开始执行【有道云笔记】签到----------
----------开始执行【有道云笔记】签到 : 第 1 个账号----------
----------执行失败 【有道云笔记】签到 : 错误日志如下:----------
'str' object has no attribute 'get'
----------未检测到正确的配置，并跳过执行【Fa米家 APP】签到----------
----------未检测到正确的配置，并跳过执行【百度站点提交】签到----------
----------已检测到正确的配置，并开始执行【联通营业厅】签到----------
----------开始执行【联通营业厅】签到 : 第 1 个账号----------
----------执行失败 【联通营业厅】签到 : 错误日志如下:----------
'str' object has no attribute 'get'
----------未检测到正确的配置，并跳过执行【一加手机社区官方论坛】签到----------
----------未检测到正确的配置，并跳过执行【什么值得买】签到----------
----------已检测到正确的配置，并开始执行【百度贴吧】签到----------
----------开始执行【百度贴吧】签到 : 第 1 个账号----------
----------执行失败 【百度贴吧】签到 : 错误日志如下:----------
'str' object has no attribute 'get'
----------未检测到正确的配置，并跳过执行【V2EX 论坛】签到----------
----------未检测到正确的配置，并跳过执行【咔叽网单】签到----------
----------未检测到正确的配置，并跳过执行【AcFun】签到----------
----------已检测到正确的配置，并开始执行【小米运动】签到----------
----------开始执行【小米运动】签到 : 第 1 个账号----------
----------执行失败 【小米运动】签到 : 错误日志如下:----------
'str' object has no attribute 'get'
----------开始执行【小米运动】签到 : 第 2 个账号----------
----------执行失败 【小米运动】签到 : 错误日志如下:----------
'str' object has no attribute 'get'
----------开始执行【小米运动】签到 : 第 3 个账号----------
----------执行失败 【小米运动】签到 : 错误日志如下:----------
'str' object has no attribute 'get'
----------开始执行【小米运动】签到 : 第 4 个账号----------
----------执行失败 【小米运动】签到 : 错误日志如下:----------
'str' object has no attribute 'get'
----------未检测到正确的配置，并跳过执行【天翼云盘】签到----------
----------已检测到正确的配置，并开始执行【WPS】签到----------
----------开始执行【WPS】签到 : 第 1 个账号----------
----------执行失败 【WPS】签到 : 错误日志如下:----------
'str' object has no attribute 'get'
----------已检测到正确的配置，并开始执行【吾爱破解】签到----------
----------开始执行【吾爱破解】签到 : 第 1 个账号----------
----------执行失败 【吾爱破解】签到 : 错误日志如下:----------
'str' object has no attribute 'get'
----------未检测到正确的配置，并跳过执行【MEIZU社区】签到----------
----------未检测到正确的配置，并跳过执行【哔咔漫画】签到----------
----------未检测到正确的配置，并跳过执行【智友邦】签到----------
----------已检测到正确的配置，并开始执行【微博】签到----------
----------开始执行【微博】签到 : 第 1 个账号----------
----------执行失败 【微博】签到 : 错误日志如下:----------
'str' object has no attribute 'get'
----------未检测到正确的配置，并跳过执行【多看阅读】签到----------
----------已检测到正确的配置，并开始执行【CSDN】签到----------
----------开始执行【CSDN】签到 : 第 1 个账号----------
----------执行失败 【CSDN】签到 : 错误日志如下:----------
'str' object has no attribute 'get'
----------未检测到正确的配置，并跳过执行【王者营地】签到----------
----------未检测到正确的配置，并跳过执行【沃邮箱】签到----------
----------已检测到正确的配置，并开始执行【天气预报】签到----------
----------开始执行【天气预报】签到 : 第 1 个账号----------
----------执行完成 【天气预报】签到 : 第 1 个账号----------
----------开始执行【天气预报】签到 : 第 2 个账号----------
----------执行完成 【天气预报】签到 : 第 2 个账号----------
Bark 推送开始

**Comment by Sitoi** [comment]
配置文件有问题吧
