### ISSUE TITLE
爱奇艺的ck在线json解析错误

### ISSUE THREAD

**Issue by VermouthEki** [Sitoi/dailycheckin#168]
在网页上获取了ck
但是在线json解析错误
网页上的ck不行吗?还是什么没做对

**Comment by lxr760** [comment]
要转义

**Comment by VermouthEki** [comment]
> 要转义

请教如何转义

**Comment by lxr760** [comment]
> > 要转义
> 
> 请教如何转义

https://www.json.cn/json/jsonzip.html
