### ISSUE TITLE
哔哩哔哩凉了

### ISSUE THREAD

**Issue by shilinjin** [Sitoi/dailycheckin#170]
哔哩哔哩凉了么？？？这两天都是签到失败，更新ck也没用

**Comment by acetaffy** [comment]
如果报错为 `local variable 's2c_msg' referenced before assignment` 可以尝试在 `src/dailycheckin/bilbili/main.py` 中删去第 344 行附近的 `{"name": "瓜子兑换", "value": s2c_msg},` ，可以使返回值正常。

在 v0.3.8 版本中测试。

**Comment by VermouthEki** [comment]
我也是.
请问你解决了吗

**Comment by shilinjin** [comment]
并没有，我是0.3.7。升级38一直失败，就没管。所以哔哩哔哩凉了我也不知道是版本问题还是咋

**Comment by NOwin111** [comment]
我昨天开始的B站签到提示这个
第 1 个账号: ❌❌❌❌❌
Expecting value: line 1 column 1 (char 0)
更新了cookie也不行

**Comment by shilinjin** [comment]
我提示none，更新ck随后测试能行，第二天自动就凉了。

**Comment by VermouthEki** [comment]
> 我昨天开始的B站签到提示这个 第1个账号：❌❌❌❌❌ 期望值：line 1 column 1 (char 0) 更新了cookie也不行

我跟你一样的问题.3天了
换了ck也不行

**Comment by github-h** [comment]
看了一下，之前获取各种任务结果的一个接口被B站删了

`https://account.bilibili.com/home/reward`

任务其实是都做了的，但最后的抓取日志失败了

等作者找找新接口吧

**Comment by Elletear** [comment]
可以尝试将获取B站经验信息部分中：
`https://account.bilibili.com/home/reward`
修改为：
`https://api.bilibili.com/x/member/web/exp/reward`
经测试，目前状态可用。

**Comment by ItzJuny** [comment]
> 可以尝试将获取B站经验信息部分中： `https://account.bilibili.com/home/reward` 修改为： `https://api.bilibili.com/x/member/web/exp/reward` 经测试，目前状态可用。

改成这个接口后又报错：unsupported operand type(s) for //: 'NoneType' and 'int'

**Comment by FairyWorld** [comment]
> 

可以了，谢谢大佬

**Comment by Edisonmai** [comment]
> 可以尝试将获取B站经验信息部分中： `https://account.bilibili.com/home/reward` 修改为： `https://api.bilibili.com/x/member/web/exp/reward` 经测试，目前状态可用。

这个去哪里改呢

**Comment by github-h** [comment]
> https://api.bilibili.com/x/member/web/exp/reward

这个接口有问题吧？会报错的吧
unsupported operand type(s) for //: 'NoneType' and 'int'

**Comment by NOwin111** [comment]
https://api.bilibili.com/x/member/web/exp/reward
这个接口我这里显示
{"code":0,"message":"0","ttl":1,"data":{"login":true,"watch":true,"coins":0,"share":false,"email":true,"tel":true,"safe_question":true,"identify_card":false}}
不过在哪里改？？？

**Comment by FairyWorld** [comment]
> 

https://api.bilibili.com/x/member/web/exp/reward这个接口返回的数据是错的

**Comment by NOwin111** [comment]
unsupported operand type(s) for //: 'NoneType' and 'int'
修改后也是这个提示

**Comment by github-h** [comment]
https://github.com/yuxian158/check/pull/15

https://github.com/yuxian158/check/pull/15/commits/97599602f981aba2263f6fe4b326647d3fa9c535
亲测可用，建议有问题的手动替换一下

感谢修复

**Comment by pretenderlu** [comment]
> [yuxian158/check#15](https://github.com/yuxian158/check/pull/15)
> 
> [yuxian158/check@9759960](https://github.com/yuxian158/check/commit/97599602f981aba2263f6fe4b326647d3fa9c535) 亲测可用，建议有问题的手动替换一下
> 
> 感谢修复

我是小白，用群晖在运行，这个我要怎么进行修改呢~~

**Comment by 9k001** [comment]
> [yuxian158/check#15](https://github.com/yuxian158/check/pull/15)
> 
> [yuxian158/check@9759960](https://github.com/yuxian158/check/commit/97599602f981aba2263f6fe4b326647d3fa9c535) 亲测可用，建议有问题的手动替换一下
> 
> 感谢修复

感谢修复。

**Comment by Dlian-Zero** [comment]
青龙面板这个到那里修改

> 可以尝试将获取B站经验信息部分中： `https://account.bilibili.com/home/reward` 修改为： `https://api.bilibili.com/x/member/web/exp/reward` 经测试，目前状态可用。
