### ISSUE TITLE
建议增加一个 小黑盒 APP 签到和分享任务自动完成

### ISSUE THREAD

**Issue by AkimotoPh** [Sitoi/dailycheckin#171]
可以获得的 H 币，用于兑换 Steam 游戏

小黑盒 官网 [小黑盒官网](https://xiaoheihe.cn/home)

**Comment by AkimotoPh** [comment]
_有类似的仓库，但是年久不维护了： https://github.com/chr233/xhh_auto_

**Comment by Sitoi** [comment]
移步https://github.com/Sitoi/dailycheckin/discussions/77
