### ISSUE TITLE
部署到腾讯云函数任务失败

### ISSUE THREAD

**Issue by chern91552** [Sitoi/dailycheckin#173]
两个secret都填写了，运行多次都是失败

**Comment by chern91552** [comment]
使用上传文件夹方法也是失败
返回结果

Text
{"errorCode":-1,"errorMessage":"user code exception caught","requestId":"c4e70518-775f-4a08-b512-c9a6e73d3d9e","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/index.py\", line 18, in main_handler\n    with open(os.path.join(os.path.dirname(__file__), \"config/config.json\"), \"r\", encoding=\"utf-8\") as f:\nFileNotFoundError: [Errno 2] No such file or directory: '/var/user/config/config.json'","statusCode":430}

执行日志

UTF-8
START RequestId: c4e70518-775f-4a08-b512-c9a6e73d3d9e

Event RequestId: c4e70518-775f-4a08-b512-c9a6e73d3d9e


END RequestId: c4e70518-775f-4a08-b512-c9a6e73d3d9e

Report RequestId: c4e70518-775f-4a08-b512-c9a6e73d3d9e Duration:1ms Memory:128MB MemUsage:17.0859MB

**Comment by Sitoi** [comment]
配置文件不存在
