### ISSUE TITLE
青龙安装提示警告出错

### ISSUE THREAD

**Issue by wyfang** [Sitoi/dailycheckin#174]
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

已尝试：
apk add --no-cache --virtual .build-deps gcc musl-dev python2-dev python3-dev libffi libffi-dev openssl openssl-dev
pip3 install pip setuptools --upgrade
pip3 install cryptography~=3.2.1

依然提示：WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

**Comment by sorakiseki24** [comment]
同样的问题，关注

**Comment by wyfang** [comment]
> 同样的问题，关注

其他地方找到说明了，无视即可，实测也正常使用，这个更像是警告，但是实际安装上了。
