### ISSUE TITLE
【建议】Telegram推送可增加一个TG_API_HOST的变量

### ISSUE THREAD

**Issue by 5sir** [Sitoi/dailycheckin#175]
## 1.关于你要提交的问题

Q：是否搜索了 issue（包括已关闭的issue）

- [x] 没有类似的 issue 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装 Python
- [x] 方法二：Docker
- [ ] 方法三：腾讯云函数
- [ ] 方法四：GitHub Actions

### (1) 具体问题

A：期望TG推送中能增加一个TG_API_HOST的变量，国内机子无需代理即可正常推送到TG了

### (2) 详细日志

A：原理就是利用了CloudFlare的Worker来实现的中转  这个文档内有教程https://shimo.im/docs/JD38CJDQtYy3yTd8

**Comment by Sitoi** [comment]
已添加 请测试后给个反馈

**Comment by 5sir** [comment]
已测试 感谢作者添加 使用自定义api后可正常推送了
