### ISSUE TITLE
【建议】telegram推送

### ISSUE THREAD

**Issue by tangli159** [Sitoi/dailycheckin#176]
## 1.关于你要提交的问题

Q：是否搜索了 issue（包括已关闭的issue）

- [x] 没有类似的 issue 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装 Python
- [x] 方法二：Docker
- [ ] 方法三：腾讯云函数
- [ ] 方法四：GitHub Actions

### (1) 具体问题

A：因为近期github actions被封号，转而在群晖本地部署docker。本人习惯使用telegram bot推送信息，现在在群晖跑没办法解决网络推送问题，能否在配置文件中增加自己添加http或者socks5代理的功能？或者我看到现在还在open的issue里面也有人提出不需要代理就可以推送的方案。麻烦您了

**Comment by Sitoi** [comment]
已添加 请测试后给个反馈

**Comment by tangli159** [comment]
> 已添加 请测试后给个反馈

已测试，http代理使用成功，socks5不成功。谢谢。另外，最近联通营业厅签到抓包数据是否有问题？我对比了之前抓包使用成功的数据，就一两个项目的顺序发生了变化而已。看起来是抓包的数据出现了问题，但是我就是把sim开头直至结尾的所有内容填写进去的，json格式也检查正确。日志登录提示
````
----------开始执行【联通营业厅】签到 : 第 1 个账号----------

{'respCode': '0001', 'respDesc': '未登录'}

----------执行失败 【联通营业厅】签到 : 错误日志如下:----------

'int' object has no attribute 'get'

----------开始执行【联通营业厅】签到 : 第 2 个账号----------

{'respCode': '0001', 'respDesc': '未登录'}

----------执行失败 【联通营业厅】签到 : 错误日志如下:----------

'int' object has no attribute 'get'
