### ISSUE TITLE
【多看阅读签到】脚本失效

### ISSUE THREAD

**Issue by leic4u** [Sitoi/dailycheckin#177]
## 1.关于你要提交的问题

Q：是否搜索了 issue（包括已关闭的issue）

- [x] 没有类似的 issue 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装 Python
- [ ] 方法二：Docker
- [ ] 方法三：腾讯云函数
- [x] 方法四：GitHub Actions

### (1) 具体问题

A：多看阅读签到失效

### (2) 详细日志

A：
`----------执行失败 【多看阅读】签到 : 错误日志如下:----------`
`'NoneType' object has no attribute 'get'`

**Comment by Sitoi** [comment]
检查自己的配置

**Comment by leic4u** [comment]
> 检查自己的配置

前天是正常的，昨天突然就报这个了，已经测试过重新抓cookie来进行配置，cookie中的分号也测试过后面带空格和不带空格两种，最后一个值也试过带分号和不带分号两种，都是报错。

**Comment by Sitoi** [comment]
配置发我微信

**Comment by sofs2005** [comment]
我也是报这个错误，楼主怎么解决的？我看了是有token的
