### ISSUE TITLE
青龙运行脚本报错

### ISSUE THREAD

**Issue by justin0705** [Sitoi/dailycheckin#178]
已经按照文档输入正确的cookie和帐号密码，但是B站和天翼云盘都会报错
`----------开始执行「Bilibili」签到----------
第 1 个账号: ❌❌❌❌❌
Expecting value: line 1 column 1 (char 0)
----------开始执行「天翼云盘」签到----------
第 1 个账号: ❌❌❌❌❌
can only concatenate list (not "dict") to list`

另外，task dailycheckin --include命令不可用，青龙提示没有include命令，报错如下
`grep: unrecognized option: include
Unrecognized switch: --include  (-h will show valid options).
BusyBox v1.34.1 (2022-04-04 10:19:27 UTC) multi-call binary.

Usage: grep [-HhnlLoqvsrRiwFE] [-m N] [-A|B|C N] { PATTERN | -e PATTERN... | -f FILE... } [FILE]...

Search for PATTERN in FILEs (or stdin)

	-H	Add 'filename:' prefix
	-h	Do not add 'filename:' prefix
	-n	Add 'line_no:' prefix
	-l	Show only names of files that match
	-L	Show only names of files that don't match
	-c	Show only count of matching lines
	-o	Show only the matching part of line
	-q	Quiet. Return 0 if PATTERN is found, 1 otherwise
	-v	Select non-matching lines
	-s	Suppress open and read errors
	-r	Recurse
	-R	Recurse and dereference symlinks
	-i	Ignore case
	-w	Match whole words only
	-x	Match whole lines only
	-F	PATTERN is a literal (not regexp)
	-E	PATTERN is an extended regexp
	-m N	Match up to N times per file
	-A N	Print N lines of trailing context
	-B N	Print N lines of leading context
	-C N	Same as '-A N -B N'
	-e PTRN	Pattern to match
	-f FILE	Read pattern from file`

**Comment by lksky8** [comment]
青龙哪个版本

**Comment by 371942171** [comment]
我也是这样，青龙v2.11.2
