### ISSUE TITLE
有道云笔记本签到提示 获取账号信息失败 list index out of range

### ISSUE THREAD

**Issue by OxYGC** [Sitoi/dailycheckin#179]
获取账号信息失败: list index out of range 其他的正常就这一个提示错误

**Comment by Hansoulxxx** [comment]
有道云更换版本了，点击头像可以切换旧版，在控制台界面过滤出push。第一个push?cstlk.....里面cookie转义出来应该就ok了。

**Comment by mingjing99** [comment]
> 有道云更换版本了，点击头像可以切换旧版，在控制台界面过滤出push。第一个push?cstlk.....里面cookie转义出来应该就ok了。

请教如何进行cookie转义呢？谢谢先！

**Comment by Hansoulxxx** [comment]
> 

json.cn   里面有压缩转义，或者百度下json转义，一大堆....

**Comment by mingjing99** [comment]
> 

非常感谢！转义之后就工作了！

**Comment by davget** [comment]
感谢，成功了

**Comment by OxYGC** [comment]
现在好像又不行了
![image](https://user-images.githubusercontent.com/26112510/187016593-48f39616-bfff-4535-9f76-d7c84d5adc60.png)

**Comment by crazyPerject** [comment]
> 现在好像又不行了 ![图片](https://user-images.githubusercontent.com/26112510/187016593-48f39616-bfff-4535-9f76-d7c84d5adc60.png)

同,我这边也不行啊

**Comment by truynal** [comment]
> 有道云更换版本本了，点击头像可以切换旧版本，在控制界面过滤出push。第一个push?cstlk.....里面cookie转义出来应该就ok了。

大佬，切换了新版本，复制出来的cookie格式有问题，看了一下是多了两个\，斜杠后面跟着\d和\l，我尝试着在斜杠前加一个\，虽然格式正确了，但是依然抱错 list index out of range，这种json如何才能修正多来呢。
<img width="1203" alt="截屏2023-05-29 00 16 56" src="https://github.com/Sitoi/dailycheckin/assets/98015467/fc10cd5d-e5f1-4303-97a8-8f4db2561842">
