### ISSUE TITLE
腾讯视频」签到  NoneType' object has no attribute 'group

### ISSUE THREAD

**Issue by OxYGC** [Sitoi/dailycheckin#181]
----------开始执行「腾讯视频」签到----------
获取成长值失败 'NoneType' object has no attribute 'group'
![image](https://user-images.githubusercontent.com/26112510/169306383-028ca02a-f4a4-45c6-afe1-50da8ed1d814.png)

**Comment by d569101769** [comment]
同样 用青龙面板出现这

**Comment by longer008** [comment]
一样的问题

**Comment by link-unigo** [comment]
我也遇到了一样的情况

**Comment by a2505** [comment]
me too

**Comment by HorrZzz** [comment]
一样的问题

**Comment by allyscn** [comment]
是否不准备修复了哦 作者要不要弃坑啊，当然希望不要弃坑

**Comment by wapchief** [comment]
半年多没维护了

**Comment by allyscn** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
