### ISSUE TITLE
本地docker的问题求教

### ISSUE THREAD

**Issue by VermouthEki** [Sitoi/dailycheckin#182]
当前时间: 2022-05-22 23:35:56
当前版本: 0.3.8
未找到 config.json 配置文件
请在下方任意目录中添加「config.json」文件:
/ql/scripts
/dailycheckin
/
/dailycheckin/config
/config
/
/dailycheckin # 

这个我要如何去创建啊.找不到位置
mac系统

**Comment by xlh001** [comment]
你的docker文件是怎样的?没有映射配置文件目录?
