### ISSUE TITLE
求一个阿里云函数/华为云函数的教程

### ISSUE THREAD

**Issue by a492338462** [Sitoi/dailycheckin#183]
原先用的腾讯云函数，但是现在要收费了。同样的方法在阿里云函数和华为云函数上试验不成功，真诚求个教学

**Comment by glqf** [comment]
把腾讯云函数的代码下载下来上传到阿里云上就可以了

**Comment by LoveForeverBoa** [comment]
> 把腾讯云函数的代码下载下来上传到阿里云上就可以了

不行啊 哥们 。。。有图么有

**Comment by glqf** [comment]
> > 把腾讯云函数的代码下载下来上传到阿里云上就可以了
> 
> 不行啊 哥们 。。。 有图么有

![image](https://user-images.githubusercontent.com/46473050/170619259-9dfb9a52-cf76-4263-a0fa-ba1003fcc742.png)
![image](https://user-images.githubusercontent.com/46473050/170619318-d5aa62c3-39a4-400e-9b19-f95a6877473a.png)
![image](https://user-images.githubusercontent.com/46473050/170619384-47cd30a6-e266-4556-b795-461e7a0ba7e2.png)

**Comment by LoveForeverBoa** [comment]
> 



> > > 把腾讯云函数的代码下载下来上传到阿里云上就可以了
> > 
> > 
> > 不行啊 哥们 。。。 有图么有
> 
> ![image](https://user-images.githubusercontent.com/46473050/170619259-9dfb9a52-cf76-4263-a0fa-ba1003fcc742.png) ![image](https://user-images.githubusercontent.com/46473050/170619318-d5aa62c3-39a4-400e-9b19-f95a6877473a.png) ![image](https://user-images.githubusercontent.com/46473050/170619384-47cd30a6-e266-4556-b795-461e7a0ba7e2.png)

谢谢哈

**Comment by qxshawn** [comment]
刚试了一下，阿里云的默认入口函数名称和腾讯云的不一样，需要改成index.main_handler

**Comment by Fnvelope** [comment]
基本的设置都是一样的，前面都按教程进行
安装依赖包那步只填pip3 install dailycheckin --upgrade -t 就行，不用填cd src，阿里云没这个文件夹
