### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by zjm54321** [Sitoi/dailycheckin#189]
# 两个问题
- 腾讯云函数从昨天开始**更改收费策略**，昨天收了我 ￥0.41，建议取消云函数教程。
- gitee中该项目**404**了，建议**更改**教程中docker的下载地址，可以使用GitHub套[CDN](https://raw.fastgit.org/sitoi/dailycheckin/main/docker_start.sh)来实现国内使用。

**Comment by zjm54321** [comment]
补充一下

- 即使使用了CDN，该部署sh脚本依然无法正常运行，内部地址依然是gitee，需要修改

**Comment by lisonglin980** [comment]
+1同样的问题
