### ISSUE TITLE
天翼网盘失效

### ISSUE THREAD

**Issue by Phoebus888** [Sitoi/dailycheckin#19]
报list index out of range

**Comment by LV36** [comment]
我也是

**Comment by HOT-POT1** [comment]
me too

**Comment by insoxin** [comment]
新地址  https://cloud.189.cn/api/portal/loginUrl.action?redirectURL=https://cloud.189.cn/web/redirect.html

改成这个就好了

**Comment by Phoebus888** [comment]
> 新地址 [https://cloud.189.cn/api/portal/loginUrl.action?redirectURL=https: / /cloud.189.cn/web/redirect.html ](https://cloud.189.cn/api/portal/loginUrl.action?redirectURL=https://cloud.189.cn/web/redirect.html)
> 
> 改成这个就好了

怎么修改代码  代码在哪个路径里面

**Comment by Sitoi** [comment]
已修复，请更新到更新到 0.1.3 版本
