### ISSUE TITLE
建议有各签到模块执行及通知的开关控制

### ISSUE THREAD

**Issue by Zero688** [Sitoi/dailycheckin#19]
## 期望增加的功能

各签到模块的执行及通知开关，签到成功通知的配置(目前用docker，通知发的是qqreader和xmly)。

## 新的薅羊毛功能

京东签到能否考虑添加

**Comment by Sitoi** [comment]
> ## 期望增加的功能
> 各签到模块的执行及通知开关，签到成功通知的配置(目前用docker，通知发的是qqreader和xmly)。
> 
> ## 新的薅羊毛功能
> 京东签到能否考虑添加

1. 签到部分是每日一签到，一起通知的，当前默认时间为早上 8：45
2. 是否执行签到是看你 config.json 是否填写相关参数，不填写就是不执行。
3. qqread 和 xmly 每天早上9点和晚上18点通知一次
4. 京东签到建议直接使用大佬开发的 docker 即可，更新的实时性要高很多。
