### ISSUE TITLE
b站签到失败

### ISSUE THREAD

**Issue by answer42n** [Sitoi/dailycheckin#195]
已解决。
群辉进入docker之后，修改/usr/local/lib/python3.8/site-packages/dailycheckin/bilibili的脚本即可修复。

**Comment by BayMRX** [comment]
> 

怎么改的啊，大佬分享一下

**Comment by BayMRX** [comment]
> 已解决。 群辉进入docker之后，修改/usr/local/lib/python3.8/site-packages/dailycheckin/bilibili的脚本即可修复。

怎么改的啊，大佬分享一下

**Comment by Cytuslcy** [comment]
修改哪里

**Comment by BayMRX** [comment]
> 修改哪里

我好了  参考这个大佬的就行了
https://github.com/Sitoi/dailycheckin/issues/170#issuecomment-1138125261

**Comment by Alan315123** [comment]
大佬们，安装在青龙面板里面的要怎么修改呢

**Comment by hailinz** [comment]
> 大佬们，安装在青龙面板里面的要怎么修改呢

我再青龙里找到路径是:
/usr/lib/python3.8/site-packages/dailycheckin/bilibili/main.py

但改完后我这提示 
unsupported operand type(s) for //: 'NoneType' and 'int'

**Comment by Charles-Hello** [comment]
@hailinz id

**Comment by wonderhong** [comment]
> > 大佬们，安装在青龙面板里面的要怎么修改呢
> 
> 我再青龙里找到路径是: /usr/lib/python3.8/site-packages/dailycheckin/bilibili/main.py
> 
> 但改完后我这提示 unsupported operand type(s) for //: 'NoneType' and 'int'

容器里找不着usr文件夹

**Comment by lbbboy** [comment]
> > > 大佬们，安装在青龙面板里面的要怎么修改呢
> > 
> > 
> > 我再青龙里找到路径是: /usr/lib/python3.8/site-packages/dailycheckin/bilibili/main.py
> > 但改完后我这提示 unsupported operand type(s) for //: 'NoneType' and 'int'
> 
> 容器里找不着usr文件夹

/usr/lib/python3.10/site-packages/dailycheckin/bilibili

python 版本可能不同 自己确认下

有错误提示，但是签到时成功的
unsupported operand type(s) for //: 'NoneType' and 'int'
