### ISSUE TITLE
沃邮箱签到失效

### ISSUE THREAD

**Issue by ysuolmai** [Sitoi/dailycheckin#198]
地址好像已经换了，没法用了

**Comment by echo567** [comment]
我也抓不到。。。
![165a45483f567b1afaefef1fe4f3f24](https://user-images.githubusercontent.com/33777600/187345261-338366da-0c73-4801-9c73-143cf1923921.jpg)

**Comment by echo567** [comment]
并且直接点击签到得好礼 登录不进去 必须先在下面的俱乐部登录上账号信息  才能点击签到得好礼  跳过去
