### ISSUE TITLE
Github Actions 参数配置错误，运行报错 exit code 1 

### ISSUE THREAD

**Issue by Tinkler-i** [Sitoi/dailycheckin#2]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否仔细阅读了教程
- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装 Python
- [ ] 方法三：Docker
- [ ] 方法二：腾讯云函数
- [x] 方法二：Github Actions

### (1) 具体问题
A：Github Actions运行报错exit code 1

### (2) 详细日志
A：Traceback (most recent call last):
  File "index.py", line 234, in <module>
    main_handler(event=event, context=None)
  File "index.py", line 100, in main_handler
    city_name_list = json.loads(os.environ.get("CITY_NAME_LIST", [])) if os.environ.get("CITY_NAME_LIST") else []
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Error: Process completed with exit code 1.

**Comment by Sitoi** [comment]
CITY_NAME_LIST 环境变量设置了吗？？是否是 list 格式 参考 
```json
["上海"]
```

**Comment by Tinkler-i** [comment]
> CITY_NAME_LIST环境变量设置了吗？？是否是列表格式参考
> 
> ```json
> [ “上海” ]
> ```

修改后还是报错，日志如下
##***group***Run python3 index.py
***36;1mpython3 index.py***0m
shell: /bin/bash -e ***0***
env:
  pythonLocation: /opt/hostedtoolcache/Python/3.7.9/x64
  IS_GITHUB_ACTION: ***
  DINGTALK_SECRET: 
  DINGTALK_ACCESS_TOKEN: 
  SCKEY: 
  TG_BOT_TOKEN: 
  TG_USER_ID: 
  QMSG_KEY: ***
  MOTTO: ***
  IQIYI_COOKIE_LIST: 
  BAIDU_URL_SUBMIT_LIST: 
  VQQ_COOKIE_LIST: 
  YOUDAO_COOKIE_LIST:  ***
  POJIE_COOKIE_LIST: 
  KGQQ_COOKIE_LIST: 
  MUSIC163_ACCOUNT_LIST: ***
  CITY_NAME_LIST: ***
  ONEPLUSBBS_COOKIE_LIST: 
##***endgroup***
Traceback (most recent call last):
  File "index.py", line 234, in <module>
    main_handler(event=event, context=None)
  File "index.py", line 89, in main_handler
    json.loads(os.environ.get("YOUDAO_COOKIE_LIST", ***)) if os.environ.get("YOUDAO_COOKIE_LIST") else ***
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 3 column 24 (char 32)
##***error***Process completed with exit code 1.

**Comment by Sitoi** [comment]
使用 英文的双引号 `"` 不要使用中文的双引号 `“`

**Comment by Sitoi** [comment]
**示例**:

```json
{
  "DINGTALK_SECRET": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "DINGTALK_ACCESS_TOKEN": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "SCKEY": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "QMSG_KEY": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "TG_BOT_TOKEN": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "TG_USER_ID": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "CITY_NAME_LIST": [
    "上海"
  ],
  "MOTTO": true,
  "IQIYI_COOKIE_LIST": [
    {
      "iqiyi_cookie": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    }
  ],
  "VQQ_COOKIE_LIST": [
    {
      "vqq_cookie": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    }
  ],
  "POJIE_COOKIE_LIST": [
    {
      "pojie_cookie": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    }
  ],
  "YOUDAO_COOKIE_LIST": [
    {
      "youdao_cookie": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    }
  ],
  "KGQQ_COOKIE_LIST": [
    {
      "kgqq_cookie": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    }
  ],
  "MUSIC163_ACCOUNT_LIST": [
    {
      "music163_phone": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      "music163_password": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    }
  ],
  "XMLY_COOKIE_LIST": [
    {
      "xmly_cookie": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    }
  ],
  "ONEPLUSBBS_COOKIE_LIST": [
    {
      "oneplusbbs_cookie": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    }
  ],
  "QQREAD_ACCOUNT_LIST": [
    {
      "qqread_bodys": {
        "common": {
          "appid": "xxxxxxxxxx",
          "areaid": "xxxxxxxxxx",
          "qq_ver": "xxxxxxxxxx",
          "os_ver": "xxxxxxxxxx",
          "mp_ver": "xxxxxxxxxx",
          "mpos_ver": "xxxxxxxxxx",
          "brand": "xxxxxxxxxx",
          "model": "xxxxxxxxxx",
          "screenWidth": "xxxxxxxxxx",
          "screenHeight": "xxxxxxxxxx",
          "windowWidth": "xxxxxxxxxx",
          "windowHeight": "xxxxxxxxxx",
          "openid": "xxxxxxxxxx",
          "guid": "xxxxxxxxxx",
          "session": "xxxxxxxxxx",
          "scene": "xxxxxxxxxx",
          "source": "xxxxxxxxxx",
          "hasRedDot": "xxxxxxxxxx",
          "missions": "xxxxxxxxxx",
          "caseID": "xxxxxxxxxx"
        },
        "dataList": [
          {
            "click1": "xxxxxxxxxx",
            "click2": "xxxxxxxxxx",
            "route": "xxxxxxxxxx",
            "refer": "xxxxxxxxxx",
            "options": {
              "bid": "xxxxxxxxxx",
              "cid": "xxxxxxxxxx"
            },
            "dis": 1607589409986,
            "ext6": 26,
            "eventID": "xxxxxxxxxx",
            "type": "xxxxxxxxxx",
            "ccid": 1,
            "bid": "xxxxxxxxxx",
            "bookStatus": 1,
            "bookPay": 0,
            "chapterStatus": 0,
            "ext1": {
              "font": 18,
              "bg": 0,
              "pageMode": 1
            },
            "from": "xxxxxxxxxx"
          }
        ]
      },
      "qqread_headers": {
        "Accept": "*/*",
        "ywsession": "xxxxxxxxxx",
        "Connection": "keep-alive",
        "Content-Type": "application/json",
        "Cookie": "ywguid=xxxxxxxxxx",
        "Host": "mqqapi.reader.qq.com",
        "User-Agent": "xxxxxxxxxx",
        "Referer": "xxxxxxxxxx",
        "Accept-Language": "zh-cn",
        "Accept-Encoding": "gzip, deflate, br",
        "mpversion": "0.32.5"
      },
      "qqread_timeurl": "https://mqqapi.reader.qq.com/mqq/addReadTimeWithBid?xxxxxxxxxx"
    }
  ],
  "BAIDU_URL_SUBMIT_LIST": [
    {
      "data_url": "https://cdn.jsdelivr.net/gh/Sitoi/Sitoi.github.io/baidu_urls.txt",
      "submit_url": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      "times": 10
    }
  ]
}
```


参考配置信息，基本上都是直接填写 list 格式 去 [http://www.json.cn/](http://www.json.cn/) 网站格式化一下数据 确保没有错误

**Comment by Tinkler-i** [comment]
> 使用 英文的双引号 `"` 不要使用中文的双引号 `“`

- [ ] 好的，修改后我再试试

**Comment by Tinkler-i** [comment]
### 有道云笔记的cookie获取
有道云笔记的cookie是需要通过app抓包获得吗

**Comment by Tinkler-i** [comment]
> ### 有道云笔记的cookie获取
> 有道云笔记的cookie是需要通过app抓包获得吗

填好有道云的SECRET就报错，看起来像是有道云cookie错误

**Comment by Sitoi** [comment]
Web 端就好，参考配置文档，里面基本上获取的网站都有 点击跳转即可
https://github.com/Sitoi/dailycheckin/blob/main/docs/settings.md

**Comment by Sitoi** [comment]
> > ### 有道云笔记的cookie获取
> > 有道云笔记的cookie是需要通过app抓包获得吗
> 
> 填好有道云的SECRET就报错，看起来像是有道云cookie错误

SECRET NAME: `YOUDAO_COOKIE_LIST`

SECRET VALUE: 
```json
[
    {
        "youdao_cookie":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    }
]
```

**Comment by Sitoi** [comment]
检查下 cookie 中 有没有这个参数 `YNOTE_PERS `

**Comment by Tinkler-i** [comment]
> 检查下cookie中有没有这个参数 `YNOTE_PERS `

只需要这一个参数吗`YNOTE_PERS=*******`，是否只需要这个参数的值，还是要一并填入cookie

**Comment by Sitoi** [comment]
> > 检查下cookie中有没有这个参数 `YNOTE_PERS `
> 
> 只需要这一个参数吗`YNOTE_PERS=*******`，是否只需要这个参数的值，还是要一并填入cookie

全部都要

**Comment by villainousx** [comment]
`Run python3 index.py
  python3 index.py
  shell: /bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.7.9/x64
    IS_GITHUB_ACTION: true
    DINGTALK_SECRET: 
    DINGTALK_ACCESS_TOKEN: 
    SCKEY: 
    QMSG_KEY: 
    TG_BOT_TOKEN: 
    TG_USER_ID: 
    COOLPUSHSKEY: 
    COOLPUSHQQ: 
    COOLPUSHWX: 
    COOLPUSHEMAIL: 
    CITY_NAME_LIST: 
    MOTTO: 
    IQIYI_COOKIE_LIST: 
    VQQ_COOKIE_LIST: 
    YOUDAO_COOKIE_LIST: 
    KGQQ_COOKIE_LIST: 
    MUSIC163_ACCOUNT_LIST: 
    ONEPLUSBBS_COOKIE_LIST: 
    FMAPP_ACCOUNT_LIST: 
    BAIDU_URL_SUBMIT_LIST: 
    TIEBA_COOKIE_LIST: 
    BILIBILI_COOKIE_LIST: 
当前时间: 2020-12-29 12:48:21.488338
-----------------------------

本次任务使用时间: 7.224082946777344e-05 秒`

请问这样手动运行正常嘛？好像什么也没有

**Comment by Sitoi** [comment]
> ## `Run python3 index.py
> python3 index.py
> shell: /bin/bash -e {0}
> env:
> pythonLocation: /opt/hostedtoolcache/Python/3.7.9/x64
> IS_GITHUB_ACTION: true
> DINGTALK_SECRET:
> DINGTALK_ACCESS_TOKEN:
> SCKEY:
> QMSG_KEY:
> TG_BOT_TOKEN:
> TG_USER_ID:
> COOLPUSHSKEY:
> COOLPUSHQQ:
> COOLPUSHWX:
> COOLPUSHEMAIL:
> CITY_NAME_LIST:
> MOTTO:
> IQIYI_COOKIE_LIST:
> VQQ_COOKIE_LIST:
> YOUDAO_COOKIE_LIST:
> KGQQ_COOKIE_LIST:
> MUSIC163_ACCOUNT_LIST:
> ONEPLUSBBS_COOKIE_LIST:
> FMAPP_ACCOUNT_LIST:
> BAIDU_URL_SUBMIT_LIST:
> TIEBA_COOKIE_LIST:
> BILIBILI_COOKIE_LIST:
> 当前时间: 2020-12-29 12:48:21.488338
> 本次任务使用时间: 7.224082946777344e-05 秒`
> 
> 请问这样手动运行正常嘛？好像什么也没有

你这是本地运行还是什么？ 环境配置了吗

**Comment by villainousx** [comment]
> > ## `Run python3 index.py
> > python3 index.py
> > shell: /bin/bash -e {0}
> > env:
> > pythonLocation: /opt/hostedtoolcache/Python/3.7.9/x64
> > IS_GITHUB_ACTION: true
> > DINGTALK_SECRET:
> > DINGTALK_ACCESS_TOKEN:
> > SCKEY:
> > QMSG_KEY:
> > TG_BOT_TOKEN:
> > TG_USER_ID:
> > COOLPUSHSKEY:
> > COOLPUSHQQ:
> > COOLPUSHWX:
> > COOLPUSHEMAIL:
> > CITY_NAME_LIST:
> > MOTTO:
> > IQIYI_COOKIE_LIST:
> > VQQ_COOKIE_LIST:
> > YOUDAO_COOKIE_LIST:
> > KGQQ_COOKIE_LIST:
> > MUSIC163_ACCOUNT_LIST:
> > ONEPLUSBBS_COOKIE_LIST:
> > FMAPP_ACCOUNT_LIST:
> > BAIDU_URL_SUBMIT_LIST:
> > TIEBA_COOKIE_LIST:
> > BILIBILI_COOKIE_LIST:
> > 当前时间: 2020-12-29 12:48:21.488338
> > 本次任务使用时间: 7.224082946777344e-05 秒`
> > 请问这样手动运行正常嘛？好像什么也没有
> 
> 你这是本地运行还是什么？ 环境配置了吗

是action的 我把secret放到环境里的secret了 现在成功了 感谢

**Comment by jackymardt** [comment]
##***group***Run python3 index.py
***36;1mpython3 index.py***0m
shell: /bin/bash -e {0}
env:
  pythonLocation: /opt/hostedtoolcache/Python/3.7.9/x64
  IS_GITHUB_ACTION: true
  DINGTALK_SECRET: 
  DINGTALK_ACCESS_TOKEN: 
  SCKEY: ***
  QMSG_KEY: 
  TG_BOT_TOKEN: 
  TG_USER_ID: 
  CITY_NAME_LIST: ***
  MOTTO: 
  IQIYI_COOKIE_LIST: ***
  VQQ_COOKIE_LIST: 
  POJIE_COOKIE_LIST: 
  YOUDAO_COOKIE_LIST: 
  KGQQ_COOKIE_LIST: 
  MUSIC163_ACCOUNT_LIST: 
  ONEPLUSBBS_COOKIE_LIST: 
  FMAPP_ACCOUNT_LIST: 
  BAIDU_URL_SUBMIT_LIST: 
##***endgroup***
Traceback (most recent call last):
  File "index.py", line 234, in <module>
    main_handler(event=event, context=None)
  File "index.py", line 82, in main_handler
    json.loads(os.environ.get("IQIYI_COOKIE_LIST", ***)) if os.environ.get("IQIYI_COOKIE_LIST") else ***
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 776 (char 775)
##***error***Process completed with exit code 1.

实在抱歉，想搞iqiyi签到，action应该不需要编辑config.json，参数直接在secret里设置吧？
在secret设置IQIYI_COOKIE_LIST， 然后在value里填cookie，cookie是类似这样的：
QC005=aa8a56d7283......; QP001=1; QC006=4f57e9307da9ebc48......
但是始终报错。难道是我参数格式问题？

比如用了这样的格式：
[
    {
        "iqiyi_cookie": "xxxxxx"
    }
]

或者：
"IQIYI_COOKIE_LIST": [
    {
        "iqiyi_cookie": "xxxxxx"
    }
]
或者：
[{"iqiyi_cookie":"xxxxxx"}]
都不行，同样的报错。

**Comment by Sitoi** [comment]
> ##_**group**_Run python3 index.py
> �_**36;1mpython3 index.py�**_0m
> shell: /bin/bash -e {0}
> env:
> pythonLocation: /opt/hostedtoolcache/Python/3.7.9/x64
> IS_GITHUB_ACTION: true
> DINGTALK_SECRET:
> DINGTALK_ACCESS_TOKEN:
> SCKEY: ***
> QMSG_KEY:
> TG_BOT_TOKEN:
> TG_USER_ID:
> CITY_NAME_LIST: ***
> MOTTO:
> IQIYI_COOKIE_LIST: ***
> VQQ_COOKIE_LIST:
> POJIE_COOKIE_LIST:
> YOUDAO_COOKIE_LIST:
> KGQQ_COOKIE_LIST:
> MUSIC163_ACCOUNT_LIST:
> ONEPLUSBBS_COOKIE_LIST:
> FMAPP_ACCOUNT_LIST:
> BAIDU_URL_SUBMIT_LIST:
> ##_**endgroup**_
> Traceback (most recent call last):
> File "index.py", line 234, in
> main_handler(event=event, context=None)
> File "index.py", line 82, in main_handler
> json.loads(os.environ.get("IQIYI_COOKIE_LIST", ***)) if os.environ.get("IQIYI_COOKIE_LIST") else ***
> File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/json/**init**.py", line 348, in loads
> return _default_decoder.decode(s)
> File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/json/decoder.py", line 337, in decode
> obj, end = self.raw_decode(s, idx=_w(s, 0).end())
> File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/json/decoder.py", line 353, in raw_decode
> obj, end = self.scan_once(s, idx)
> json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 776 (char 775)
> ##_**error**_Process completed with exit code 1.
> 
> 实在抱歉，想搞iqiyi签到，action应该不需要编辑config.json，参数直接在secret里设置吧？
> 在secret设置IQIYI_COOKIE_LIST， 然后在value里填cookie，cookie是类似这样的：
> QC005=aa8a56d7283......; QP001=1; QC006=4f57e9307da9ebc48......
> 但是始终报错。难道是我参数格式问题？
> 
> 比如用了这样的格式：
> [
> {
> "iqiyi_cookie": "xxxxxx"
> }
> ]
> 
> 或者：
> "IQIYI_COOKIE_LIST": [
> {
> "iqiyi_cookie": "xxxxxx"
> }
> ]
> 或者：
> [{"iqiyi_cookie":"xxxxxx"}]
> 都不行，同样的报错。


参考配置信息，基本上都是直接填写 list 格式 去 http://www.json.cn/ 网站格式化一下数据 确保没有错误

```json
[
    {
        "iqiyi_cookie":"帐号1 cookie"
    },
    {
        "iqiyi_cookie":"帐号2 cookie"
    }
]
```
