### ISSUE TITLE
有道、bilibili、CSDN失败

### ISSUE THREAD

**Issue by 371942171** [Sitoi/dailycheckin#201]
----------开始执行「Bilibili」签到----------
第 1 个账号: ❌❌❌❌❌
Expecting value: line 1 column 1 (char 0)
----------开始执行「CSDN」签到----------
第 1 个账号: ❌❌❌❌❌
'latin-1' codec can't encode characters in position 712-716: ordinal not in range(256)
----------开始执行「有道云笔记」签到----------
获取账号信息失败: list index out of range
第 1 个账号: ✅✅✅✅✅

**Comment by soapffz** [comment]
bilibili同，报错内容一样

**Comment by misaya98** [comment]
同  
第 1 个账号: ❌❌❌❌❌
Expecting value: line 1 column 1 (char 0)

**Comment by gurenn** [comment]
我也是B站反馈回来的是
Expecting value: line 1 column 1 (char 0)
查了一下百度有人说
出现这种Expecting value: line 1 column 1 (char 0)报错，一般原因都是返回的数据的格式不是json格式的。
是不是B站的签到机制有变动了？

**Comment by 66622a** [comment]
https://github.com/Sitoi/dailycheckin/issues/195

**Comment by crazyPerject** [comment]
bilibili改了成功了
CSDN默认没报错
有道按帖转译也还是报错
