### ISSUE TITLE
提些建议和还能够使用的签到

### ISSUE THREAD

**Issue by oldye2020** [Sitoi/dailycheckin#205]
通知能不能直接整合一下，每个签到都发一次确实挺麻烦。

现在还在使用的：爱奇艺，魅族，一加，天翼云盘，值得买。
其他的要么失效要么不成功。当然欢迎大家指出还有什么能够用的

**Comment by glqf** [comment]
配置里面
MERGE_PUSH | 合并推送 | 配置 | true: 将推送消息合并；false: 分开推送

**Comment by oldye2020** [comment]
> 配置里面 MERGE_PUSH | 合并推送 | 配置 | true: 将推送消息合并；false: 分开推送

感谢，已经可以合并
