### ISSUE TITLE
一加手机社区官方论坛 签到

### ISSUE THREAD

**Issue by lbbboy** [Sitoi/dailycheckin#206]
「一加手机社区官方论坛」
帐号信息: 未获取到账号信息
签到信息: Cookie 可能过期
抽奖信息: 成功抽奖 10 次
抽奖结果: 获得 38 加油

抽奖可以使用签到不可

**Comment by oldye2020** [comment]
怎么解决的

**Comment by lbbboy** [comment]
> 怎么解决的

没抓对抓对了就好了
