### ISSUE TITLE
多看豆子变少

### ISSUE THREAD

**Issue by sofs2005** [Sitoi/dailycheckin#209]
多看豆子从原来每天6000+变成300+了，是不是任务列表有更新了？看了下日志任务少了很多，不知道是官方缩水了还是需要更新清单啊？

**Comment by ToSeeAll** [comment]
+1，看了下日志，7月25号和之前都是6000，7月26之后就是300了

**Comment by marigold233** [comment]
现在直接不行了？ 一直卡着不动了
![image](https://user-images.githubusercontent.com/62014410/199404086-73ef5b87-7e22-425b-84c5-6b066e2c26e7.png)
