### ISSUE TITLE
腾讯视频签到问题

### ISSUE THREAD

**Issue by sandglasstu** [Sitoi/dailycheckin#21]
## 1.关于你要提交的问题

Q：是否搜索了 issue（包括已关闭的issue）

- [x] 没有类似的 issue 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装 Python
- [ ] 方法二：Docker
- [ ] 方法三：腾讯云函数
- [x] 方法四：GitHub Actions

### (1) 具体问题

A：腾讯视频签到有点问题，签到奖励1一直是失败的，签到奖励2偶尔成功(需要一直换cookie)，确认Secrets配置无误

### (2) 详细日志

A：
【腾讯视频签到】
![image](https://user-images.githubusercontent.com/12029190/103844174-46708480-50d4-11eb-9b77-09753f56cf68.png)

**Comment by coffeetang-haitao** [comment]
方法一：本地安装 Python
同样的问题

**Comment by Sitoi** [comment]
换cookie 试试？

**Comment by sandglasstu** [comment]
> 换cookie 试试？

换cookie签到奖励2是没问题的，但是1一直是失败的，而且隔一两天就要换cookie，看下是哪里有问题吗

**Comment by Sitoi** [comment]
> > 换cookie 试试？
> 
> 换cookie签到奖励2是没问题的，但是隔一两天就要换cookie，看下是哪里有问题吗
> 
> 还有我看了下代码里奖励1的url貌似不存在了，所以一直失败

检查下，你获取cookie 的浏览器登录腾讯视频页面是否需要重新登录，需要重新登录的话，可能是你的电脑管家或者浏览器自动清理了cookie导致的。
