### ISSUE TITLE
8/5号之后，小米运动刷步数无效

### ISSUE THREAD

**Issue by immochan** [Sitoi/dailycheckin#21]
RT，有没有人碰到过类似情况的，8/5号之后，小米运动刷步数无效，日志结果上无明显报错
![image](https://user-images.githubusercontent.com/37736378/128437736-cb0731f8-750a-483b-aa17-2f89cdc50ddb.png)

**Comment by jobinli** [comment]
+1，调试了一晚上无效，包括手环上同步的步数也无法同步到三方（微信、支付宝）上，怀疑是小米运动自身问题。

**Comment by sofs2005** [comment]
Js脚本已经有新版可以更新支付宝了，应该是接口有变化。老大什么时候更啊

**Comment by Sitoi** [comment]
代码已修改 但我试了还是不行
