### ISSUE TITLE
青龙面板一直失败

### ISSUE THREAD

**Issue by hahashifeng** [Sitoi/dailycheckin#219]
## 开始执行... 2022-10-26 23:19:02

当前时间: 2022-10-26 23:19:03
当前版本: 0.3.8
usage: dailycheckin [-h] [--include INCLUDE [INCLUDE ...]]
                    [--exclude EXCLUDE [EXCLUDE ...]]
dailycheckin: error: unrecognized arguments: ""

**Comment by singyueyang** [comment]
嗷嗷。。我也是这个问题。。突然就没法用了。

**Comment by BNDou** [comment]
把青龙版本退回去，不用新版，青龙2.14.7及之前不报错

**Comment by wyfang** [comment]
> 把青龙版本退回去，不用新版，青龙2.14.7及之前不报错
求问如何指定版本？
是把这个
`image: whyour/qinglong:latest`改成`image: whyour/qinglong:2.14.7` 吗？

**Comment by BNDou** [comment]
> > 把青龙版本退回去，不用新版，青龙2.14.7及之前不报错
> 求问如何指定版本？
> 是把这个
> `image: whyour/qinglong:latest`改成`image: whyour/qinglong:2.14.7` 吗？

可以。

**Comment by wzwcc** [comment]
@BNDou 可以改成sh文件执行就没问题了 计划任务会默认加上task 好像

**Comment by hahashifeng** [comment]
> @BNDou可以改成sh文件执行默认任务问题了计划任务会
怎么改成sh文件执行啊

**Comment by sailcom** [comment]
> @BNDou 可以改成sh文件执行就没问题了 计划任务会默认加上task 好像

请教如何改成sh文件执行呢？

**Comment by BNDou** [comment]
新建一个py文件，写入代码

```python
import os
os.system('dailycheckin')
```

执行指令写成py就行了

```
task xxx.py
```

>借鉴群内大佬
![青龙-silo ²i!](https://user-images.githubusercontent.com/67632799/199679186-639ce73c-f903-4a5d-af4e-69a50a1c17a8.png)

**Comment by hahashifeng** [comment]
可以了我天，谢谢大佬！！！

**Comment by BNDou** [comment]
>@hahashifeng 可以close议题了🤙
