### ISSUE TITLE
宝塔里的Docker 怎么安装啊？

### ISSUE THREAD

**Issue by supergming** [Sitoi/dailycheckin#220]
在宝塔里的终端直接运行命令报错
[root@VM-16-11-centos ~]# curl https://gitee.com/sitoi/dailycheckin/raw/main/docker_start.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    52  100    52    0     0     15      0  0:00:03  0:00:03 --:--:--    15
bash: line 1: [session-0b408fbd]: command not found
应该怎么弄呢？

**Comment by yanglanshi** [comment]
一样的问题，有解决吗？
