### ISSUE TITLE
能否做一个适配华为云函数的教程

### ISSUE THREAD

**Issue by DaksenJanson** [Sitoi/dailycheckin#226]
腾讯云函数收费了，转战华为云，按原来的教程，发现依赖包搞不定，和腾讯云函数不一样。希望能做个华为云函数的教程，万分感谢！

**Comment by kyeo-hub** [comment]
@DaksenJanson 我费了两天时间成功了。你可以试试https://blog.10an.fun/article/dailycheckin-in-function.html
