### ISSUE TITLE
什么值得买签到失效了

### ISSUE THREAD

**Issue by longwangjiang** [Sitoi/dailycheckin#229]
什么值得买签到失效了

**Comment by zoeblow** [comment]
是呀是呀，
```
「什么值得买」

签到信息: 签到失败

错误信息: 'list' object has no attribute 'get'
```

**Comment by CrystalFairy** [comment]
请问有解决方法吗？

**Comment by gygzff** [comment]
一样的，失效了。之前很好用。。求修复~

**Comment by realjackwang** [comment]
现在什么值得买签到需要验证码了，所以会失败。

**Comment by Hello-XPH** [comment]
> 我做了一个使用青龙面板的签到脚本，使用Android App的接口实现的签到，有兴趣的朋友可以试试https://github.com/hex-ci/smzdm_script

安装有什么抓包软件吗，不root。可以说出来吗，谢谢。

**Comment by Hello-XPH** [comment]
ssl证书不信任

**Comment by dust2k** [comment]
> 

如果手机能root，可以添加自己sign的根证书到系统内置根证书里，或者直接拆apk换掉里面的证书就可以了。。
