### ISSUE TITLE
希望增加几个论坛的签到.

### ISSUE THREAD

**Issue by sadnecc** [Sitoi/dailycheckin#23]
## 期望增加的功能

A：学破解签到     https://www.xuepojie.com/
      看雪论坛签到   https://bbs.pediy.com/
      卡饭论坛签到    https://bbs.kafan.cn/
      V2EX论坛签到    https://www.v2ex.com/
       有可能的话搞一个DZ论坛通用的. 感谢

## 入口

A：

**Comment by geelinsir** [comment]
V2EX已实现
