### ISSUE TITLE
哔哩哔哩脚本兑换瓜子功能异常

### ISSUE THREAD

**Issue by github-h** [Sitoi/dailycheckin#231]
当 哔哩哔哩的 该配置项为 `"silver2coin": false` 时，

运行函数会爆
```
「Bilibili」
local variable 's2c_msg' referenced before assignment
```

请将 `src/dailycheckin/bilibili/main.py` 下 第 **352** 行的 else 缩进提前  使其与 **347** 行的 if 匹配

这也是个历史遗留问题了，麻烦改一下吧

**Comment by AiharaShion1** [comment]
大佬您好，我也遇到了同样的情况，
按照您提的「将 `src/dailycheckin/bilibili/main.py`下 第 352 行的 else 缩进提前 使其与 347 行的 if 匹配」手动修改后（如图），
![s2c_msg_main py](https://user-images.githubusercontent.com/129312150/228608686-01aaeeb3-dbc0-4b86-a477-1bee9082ff2f.png)
依旧会报错`「local variable 's2c_msg' referenced before assignment」`，请问这个问题是否得等到作者大佬更新才能解决呢？

**Comment by jackelchen** [comment]
其实问题是在于如果silver2coin是false的话,msg 里面的{"name": "瓜子兑换", "value": s2c_msg},是不存在的,在外面加个else来定义s2c_msg 就好,不会提交代码啊,大佬有空改一下吧@Sitoi

`            if silver2coin:
                silver2coin_ret = self.silver2coin(session=session, bili_jct=bili_jct)
                s2c_msg = silver2coin_ret["message"]
                if silver2coin_ret["code"] != 0:
                    print(s2c_msg)
                else:
                    s2c_msg = ""
            else:
            	s2c_msg = "不兑换硬币"`

**Comment by jackelchen** [comment]
其实是silver2coin=false时, s2c_msg会没定义, 导致msg里面报错, 在外面else定义一下就好了

if silver2coin:  
- xxxxxx

else:
- s2c_msg = "不兑换硬币"
