### ISSUE TITLE
青龙定时更新警告 task pip3 install dailycheckin --upgrade

### ISSUE THREAD

**Issue by wukecheng** [Sitoi/dailycheckin#234]
如何解决

WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

**Comment by lentikr** [comment]
添加--user参数试试

**Comment by drw2005** [comment]
> 添加--user参数试试

添加了也不行，还是有这个提示。
