### ISSUE TITLE
actions显示

### ISSUE THREAD

**Issue by niumingyuan** [Sitoi/dailycheckin#24]
我希望actions里面的签到集合分开显示出来，签到结果都集合到一个，出错也不知道是添加哪个cookie导致错误的原因😂
![Screenshot_2021-01-11-17-28-07-51](https://user-images.githubusercontent.com/45312204/104164276-a481cc80-5432-11eb-8f20-e5c632a7b7d3.jpg)

**Comment by Sitoi** [comment]
不进行分离了，后期会支持传入参数检测。
