### ISSUE TITLE
天翼云盘签到挂了

### ISSUE THREAD

**Issue by coachpo** [Sitoi/dailycheckin#241]
![image](https://github.com/Sitoi/dailycheckin/assets/12790403/393ca777-6b60-42ba-8ac2-873fac2afc8a)
不知道是什么原因。。
list index out of range

**Comment by 520yxl** [comment]
我还以为是我设置有问题呢

**Comment by hervenlee** [comment]
我也是从10号开始不行了

**Comment by 520yxl** [comment]
一样，我现在找其他的试试，是不是也是挂了

**Comment by 520yxl** [comment]
> 我也是从10号开始不行了

找到新的脚本了

**Comment by netboy8** [comment]
我还以为是我环境出问题呢

**Comment by vitasapple** [comment]
> 

那你贴出来吧

**Comment by 520yxl** [comment]
> > 
> 
> 那你贴出来吧

https://github.com/qiandao-today/qiandao/

**Comment by xjxjin** [comment]
> > > 
> > 
> > 
> > 那你贴出来吧
> 
> https://github.com/qiandao-today/qiandao/

这个怎么玩啊，我在本地部署成功了，也拿到了har文件，但是不知道下一步怎么搞，找不到签到的页面

**Comment by 520yxl** [comment]
> > > > 
> > > 
> > > 
> > > 那你贴出来吧
> > 
> > 
> > https://github.com/qiandao-today/qiandao/
> 
> 这个怎么玩啊，我在本地部署成功了，也拿到了har文件，但是不知道下一步怎么搞，找不到签到的页面

![image](https://www.520yxl.cn/tools/pan/view.php/c537a17d9ad009415bafad3e311bfec7.png)

**Comment by kyeo-hub** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 那你贴出来吧
> > > 
> > > 
> > > https://github.com/qiandao-today/qiandao/
> > 
> > 
> > 这个怎么玩啊，我在本地部署成功了，也拿到了har文件，但是不知道下一步怎么搞，找不到签到的页面
> 
> ![image](https://camo.githubusercontent.com/c05f229b670bbb8f01a137470329dce5c26eca3a97355002d334c37d1751cfee/68747470733a2f2f7777772e35323079786c2e636e2f746f6f6c732f70616e2f766965772e7068702f63353337613137643961643030393431356261666164336533313162666563372e706e67)

已尝试，有效，利用HAR文件做的签到。就是不懂怎么提取HAR的请求，自己用python去实现。

**Comment by wingswing1** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > 那你贴出来吧
> > > > 
> > > > 
> > > > https://github.com/qiandao-today/qiandao/
> > > 
> > > 
> > > 这个怎么玩啊，我在本地部署成功了，也拿到了har文件，但是不知道下一步怎么搞，找不到签到的页面
> > 
> > 
> > ![image](https://camo.githubusercontent.com/c05f229b670bbb8f01a137470329dce5c26eca3a97355002d334c37d1751cfee/68747470733a2f2f7777772e35323079786c2e636e2f746f6f6c732f70616e2f766965772e7068702f63353337613137643961643030393431356261666164336533313162666563372e706e67)
> 
> 已尝试，有效，利用HAR文件做的签到。就是不懂怎么提取HAR的请求，自己用python去实现。

有没有适合小白的呀？这种太难了

**Comment by kkzhh** [comment]
原来这边也挂了，我还以为是我的那个脚本挂了

**Comment by 889098** [comment]
同样的问题，怎么还没有修复啊

**Comment by aitixiong** [comment]
等待修复ing...
