### ISSUE TITLE
小米运动已失效

### ISSUE THREAD

**Issue by CoverUp137** [Sitoi/dailycheckin#25]
大佬可以更新接口么

**Comment by gold2wave** [comment]
确实是失效了，吾爱好像也没有用

**Comment by lexno** [comment]
吾爱好像还行，我这边成功了
运动貌似是上传步数成功了，但是小米运动不认这个步数

**Comment by Bob472** [comment]
我这边推送显示步数修改成功，但小米运动的步数根本没变

**Comment by lexno** [comment]
> 我这边推送显示步数修改成功，但小米运动的步数根本没变

这个同步是通过小米运动的渠道推送到支付宝或者微信，小米运动本身的步数是不会改的

**Comment by Sitoi** [comment]
已修复
