### ISSUE TITLE
小米运动刷步数，有已完成的项目，可否添加多账号？[https://github.com/fuckgm/mimotion]

### ISSUE THREAD

**Issue by villainousx** [Sitoi/dailycheckin#25]
## 期望增加的功能

A：小米运动刷步数，有已完成的项目，可否添加多账号？[https://github.com/fuckgm/mimotion](https://github.com/fuckgm/mimotion)

## 入口

A：[https://github.com/fuckgm/mimotion](https://github.com/fuckgm/mimotion)

**Comment by Sitoi** [comment]
已添加 支持多账号
