### ISSUE TITLE
天翼云盘签到失效

### ISSUE THREAD

**Issue by ChangJun1** [Sitoi/dailycheckin#255]
新版本(v24.01.07)更新后，天翼云盘无法签到，查看dailychekin目录下没有对应执行任务的py文件，请作者抽空修复。

**Comment by Sitoi** [comment]
登录需要验证码，不在支持天翼云盘了

**Comment by xzhlksh** [comment]
> 登录需要验证码，不在支持天翼云盘了

大佬，我在别的地方找到了可用天翼签到脚本，已经自己魔改到旧版签到脚本了，一个月最多有1~2天的不稳定，不知道怎么把代码共享出来，请问接受pull么？

**Comment by Sitoi** [comment]
可以接受pull，你可以发起一个
