### ISSUE TITLE
[Request] b币自动充电

### ISSUE THREAD

**Issue by sdogsq** [Sitoi/dailycheckin#257]
### 🥰 需求描述

增加大会员b币自动充电功能。

### 🧐 解决方案

脚本中已有领取b币券功能（vip_privilege_receive）和充电接口（elec_pay），仅需加入功能即可。

**Comment by Sitoi** [comment]
给谁充电啊？？

**Comment by sdogsq** [comment]
可以给自己充电😂

**Comment by Hades-ming** [comment]
> 给谁充电啊？？

可以加一个参数设置被充电人的UID

**Comment by MrSean527** [comment]
会员还有个每日 10 经验可以领🤣

**Comment by Sitoi** [comment]
不考虑了，一个月就一次 手动点一下吧
