### ISSUE TITLE
docker 部署发现定时 依旧沿用原根目录cron脚本  未使用/cron/目录下脚本    [Bug] 

### ISSUE THREAD

**Issue by jiulan** [Sitoi/dailycheckin#258]
### 💻 系统环境

Other Linux

### 📦 部署环境

Docker

### 🐛 问题描述

进入容器发现  原defult_task.sh未更新     导致挂载cron目录 实际未生效
![Uploading 企业微信截图_17055398016323.png…]()

**Comment by Sitoi** [comment]
把旧的容器删了，重新部署

**Comment by jiulan** [comment]
我把容器镜像都删除了&nbsp; 一样的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月18日(周四) 上午9:54
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Sitoi/dailycheckin] docker 部署发现定时 依旧沿用原根目录cron脚本  未使用/cron/目录下脚本    [Bug]  (Issue #258)




 
把旧的容器删了，重新部署

**Comment by Sitoi** [comment]
图呢？日志？docker 内文件？ 挂载目录是否正确？

**Comment by jiulan** [comment]
docker 容器镜像都是新的&nbsp; &nbsp; 感觉用的是不是cron目录下的定时配置


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Sitoi/dailycheckin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月18日(星期四) 下午4:58
***@***.***&gt;;
抄送:&nbsp;"Room Liang ***@***.******@***.***&gt;;
主题:&nbsp;Re: [Sitoi/dailycheckin] docker 部署发现定时 依旧沿用原根目录cron脚本  未使用/cron/目录下脚本    [Bug]  (Issue #258)





 
图呢？日志？docker 内文件？ 挂载目录是否正确？

**Comment by Sitoi** [comment]
是啊，用的 cron 目录下的定时任务

**Comment by jiulan** [comment]
我看了默认cron目录下执行不是9:00嘛&nbsp; &nbsp;实际执行是8:45



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月19日(周五) 上午8:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Sitoi/dailycheckin] docker 部署发现定时 依旧沿用原根目录cron脚本  未使用/cron/目录下脚本    [Bug]  (Issue #258)




 
是啊，用的 cron 目录下的定时任务

**Comment by reY2ox** [comment]
我也遇到了这个问题。最终我发现是通过阿里的镜像源拉取的镜像是21年封装的，即使作者做到了镜像内的pip更新程序，但是启动程序的脚本还是旧的，所以导致最新的挂载方法无法正确的使用。建议删掉镜像切换源后重新下载镜像。

**Comment by jiulan** [comment]
感谢&nbsp;目前还有其他镜像源在阿里上&nbsp; &nbsp;暂时没换&nbsp; 用宿主机cron调用的&nbsp; &nbsp;影响不大




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Sitoi/dailycheckin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月26日(星期一) 上午10:29
***@***.***&gt;;
抄送:&nbsp;"Room Liang ***@***.******@***.***&gt;;
主题:&nbsp;Re: [Sitoi/dailycheckin] docker 部署发现定时 依旧沿用原根目录cron脚本  未使用/cron/目录下脚本    [Bug]  (Issue #258)





 
我也遇到了这个问题。最终我发现是通过阿里的镜像源拉取的docker是21年封装的，即使作者做到了镜像内的pip更新程序，但是启动程序的脚本还是旧的，所以导致最新的挂载方法无法正确的使用。建议删掉镜像切换源后重新下载镜像。
