### ISSUE TITLE
[Request] 请求融合腾讯视频和狐蒂云等

### ISSUE THREAD

**Issue by yu0o** [Sitoi/dailycheckin#259]
### 🥰 需求描述

可以加入腾讯视频签到，任务和狐蒂云每日签到吗，腾讯视频不用过多说明狐蒂云是云服务器，每天签到一毛钱
![屏幕截图(33)](https://github.com/Sitoi/dailycheckin/assets/147189804/b06aa0bf-7109-47f4-9173-907208371907)

### 🧐 解决方案

[京东](https://conveniencespace.com/index.php/2022/05/03/2022%E6%9C%80%E6%96%B0%E9%9D%92%E9%BE%99%E9%9D%A2%E6%9D%BF%E4%BA%AC%E4%B8%9C%E8%84%9A%E6%9C%AC%E5%BA%93%EF%BC%88%E6%8C%81%E7%BB%AD%E6%9B%B4%E6%96%B0%E4%B8%AD%EF%BC%89/)
[腾讯视频](https://blog.csdn.net/lvhaoye/article/details/119963357) 
狐蒂云太小众了暂无脚本，[签到页面](https://www.hudiyun.com/addons?_plugin=25&_controller=index&_action=index)

**Comment by Sitoi** [comment]
腾讯视频掉的太快 没有实际的意义
狐蒂云太小众了，实际的需求可能不高
京东有更专业的
