### ISSUE TITLE
配置文档说明链接失效，无法查看配置说明

### ISSUE THREAD

**Issue by FairyWorld** [Sitoi/dailycheckin#26]
配置文档说明链接失效，无法查看配置说明

**Comment by Sitoi** [comment]
修复了

**Comment by niumingyuan** [comment]
https://sitoi.cn/dailycheckin/ 这个404啦。梯子也挂啦

**Comment by Sitoi** [comment]
> https://sitoi.cn/dailycheckin/ 这个404啦。梯子也挂啦

https://sitoi.github.io/dailycheckin

**Comment by Sitoi** [comment]
> https://sitoi.cn/dailycheckin/ 这个404啦。梯子也挂啦

不行的话 开无痕
