### ISSUE TITLE
[Request] V2EX签到问题

### ISSUE THREAD

**Issue by mipaers** [Sitoi/dailycheckin#261]
### 🥰 需求描述

V2EX签到能不能加一个去除Proxy的代码选项.

### 🧐 解决方案

V2EX签到能不能加一个去除Proxy的代码选项.

**Comment by Sitoi** [comment]
不设置 或者 设置成 None 就好

**Comment by marchanbbb** [comment]
docker版不配置直接报错

**Comment by ekodong** [comment]
+1，docker版删除这个配置运行不了

**Comment by Sitoi** [comment]
这个网站需要代理，没有代理连不上

**Comment by marchanbbb** [comment]
> 这个网站需要代理，没有代理连不上

但是如果vps在外网不需要代理吧

**Comment by Sitoi** [comment]
不需要，那可能是cookie 问题

**Comment by ekodong** [comment]
> 不需要，那可能是cookie 问题

cookie是按照指南提供的方法提取的，看上去是代理的问题，我在这个issue里面贴了日志：https://github.com/Sitoi/dailycheckin/issues/284

报错是连接没有建立起来，实际还没有到检查cookie的阶段。

**Comment by Sitoi** [comment]
你看看能不能ping 通吧

**Comment by ekodong** [comment]
> 你看看能不能ping 通吧
可以的，我的机器在HK，可以直接打开的
[root@VM-8-12-centos dailycheckin]# ping www.v2ex.com
PING www.v2ex.com (104.20.10.218) 56(84) bytes of data.
64 bytes from 104.20.10.218 (104.20.10.218): icmp_seq=1 ttl=57 time=1.17 ms
64 bytes from 104.20.10.218 (104.20.10.218): icmp_seq=2 ttl=57 time=1.25 ms
64 bytes from 104.20.10.218 (104.20.10.218): icmp_seq=3 ttl=57 time=1.35 ms
64 bytes from 104.20.10.218 (104.20.10.218): icmp_seq=4 ttl=57 time=1.36 ms
64 bytes from 104.20.10.218 (104.20.10.218): icmp_seq=5 ttl=57 time=1.35 ms

**Comment by Sitoi** [comment]
你试试看 wget 一下呢？

**Comment by mipaers** [comment]
不行用这个得了

>
[Uploading v2ex.txt…]()

**Comment by vicshi2015** [comment]
docker运行，可以试试 config proxy配置成 http://host.docker.internal:xxxx
