### ISSUE TITLE
有道云笔记无法签到[Bug] 

### ISSUE THREAD

**Issue by ccloving2007** [Sitoi/dailycheckin#262]
### 💻 系统环境

Ubuntu

### 📦 部署环境

Docker

### 🐛 问题描述

提示获取账号信息失败：list index out of range.

### 📝 运行日志

----------开始执行「有道云笔记」签到----------
获取账号信息失败: list index out of range
第 1 个账号: ❌❌❌❌❌
HTTPConnectionPool(host='note.youdao.com', port=80): Max retries exceeded with url: /login/acc/pe/getsess?product=YNOTE (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe0f239ab20>: Failed to establish a new connection: [Errno 113] Host is unreachable'))

**Comment by Sitoi** [comment]
![image](https://github.com/Sitoi/dailycheckin/assets/32479597/282e2a82-d54e-4c8e-a153-6a3dbd8f1048)
可以试试看这种方式获取有道云笔记的 cookie

**Comment by ccloving2007** [comment]
已解决。
