### ISSUE TITLE
通知消息在 Qmsg 中被视为违规  

### ISSUE THREAD

**Issue by littledogboy** [Sitoi/dailycheckin#264]
### 🥰 需求描述

![c32e9cfb749a477eaf484902adf51cdf](https://github.com/Sitoi/dailycheckin/assets/11345643/4f633149-debc-4c62-938d-3082175302b5)

如图所示，qmsg 的qq机器人不会转发含有 url 地址的消息。

### 🧐 解决方案

感觉使用时只能换其他解决方式了。 但是我觉得这点还是要让用户知道的。毕竟脚本会有 git 仓库地址消息，而这在 Qmsg 中根本就不会被转发。

### 📝 补充信息

[issues/70](https://github.com/Sitoi/dailycheckin/issues/70)  翻看issue 时发现21年已经有人提过该问题了，所以还是希望有时间修改一下使用文档。 

_No response_

**Comment by Sitoi** [comment]
这个有什么办法规避吗？还是没有办法？

**Comment by littledogboy** [comment]
> 这个有什么办法规避吗？还是没有办法？

应该没有办法规避，我去他们群里反应了一下，他们给我的建议是赞助版自己搭建。sad 。然后我换了 bark 通知。

**Comment by Sitoi** [comment]
最新文档已添加
