### ISSUE TITLE
[Bug] 什么值得买签到报错'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by cheng-jc** [Sitoi/dailycheckin#265]
### 💻 系统环境

Other Linux

### 📦 部署环境

青龙

### 🐛 问题描述

2024年1月23日安装脚本。什么值得买签到失败，用的网页获取CK，后面手机登录可以签到。报错内容为：'NoneType' object is not subscriptable
![screenshot-20240123-224227](https://github.com/Sitoi/dailycheckin/assets/54888578/af8b5839-3517-4a55-a0ae-25a42601d4db)

## 开始执行... 2024-01-23 22:34:51

当前时间: 2024-01-23 22:34:52
当前版本: 24.1.20
使用配置文件路径: /ql/data/scripts/config.json

---------- 本次执行签到任务如下 ----------

「i茅台」账号数 : 3
「什么值得买」账号数 : 1

----------开始执行「i茅台」签到----------
第 1 个账号: ✅✅✅✅✅
第 2 个账号: ✅✅✅✅✅
第 3 个账号: ✅✅✅✅✅
----------开始执行「什么值得买」签到----------
第 1 个账号: ❌❌❌❌❌
'NoneType' object is not subscriptable

Pushplus 推送开始

## 执行结束... 2024-01-23 22:35:03 耗时 12 秒

**Comment by cheng-jc** [comment]
青龙版本v2.12.0

**Comment by Sitoi** [comment]
![image](https://github.com/Sitoi/dailycheckin/assets/32479597/68a92722-a89b-41ca-a335-f17a82e8250a)
使用这种方式获取 cookie的吗？

**Comment by cheng-jc** [comment]
用这种方式获取cookie后可以正常签到了，谢谢大佬

**Comment by dgulan** [comment]
谢谢。
需要复制的内容很长。要全部复制。
