### ISSUE TITLE
[Request] 提交【奥拉星积分商城】自动签到，支持多用户|Cookie,已有青龙一键订阅等完整使用功能代码

### ISSUE THREAD

**Issue by lanzeweie** [Sitoi/dailycheckin#266]
### 🥰 需求描述

【奥拉星积分商城】自动签到项目，支持多用户 | Cookie
任务网站：http://www.100bt.com/m/creditMall/?gameId=2#task 经过抓包测试，百田积分商城的每个任务结算是发出任务完成请求，就可以完成此任务获得积分。
并且每个任务都使用了一样的模板，只需要找到请求完成任务网站，并且附加任务信息就可以一键完成任务。
❗注意：无法完成邀请人的任务
任务完成速度在10s内 （不占内存，纯粹是等待机制）

**功能**
1.支持多用户
2.输出完成信息（用户信息、任务完成数、获得积分点、总共签到天数）
3.支持青龙面板订阅
4.推送钉钉等青龙支持的通知方式

**奖励**
可以换取 《奥拉星》 周边商品、付费游戏币 等

### 🧐 解决方案

开源地址：https://github.com/lanzeweie/aolaxing

**Comment by Sitoi** [comment]
竟然是作者本人！行，我加上

**Comment by Sitoi** [comment]
24.2.6 版本新增
