### ISSUE TITLE
[Bug] 茅台失败

### ISSUE THREAD

**Issue by doomlordcn** [Sitoi/dailycheckin#267]
### 💻 系统环境

Other Linux

### 📦 部署环境

青龙

### 🐛 问题描述

青龙运行报错

### 📝 运行日志

第 1 个账号: ✅✅✅✅✅
----------开始执行「i茅台」签到----------
get_current_session_id : params : 1706256000000, response code : 404, response body : <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key></Key><BucketName></BucketName><Resource>/mt-backend/xhr/front/mall/index/session/get/1706256000000</Resource><RequestId>HYNX4ZXG7TKL0F42</RequestId><HostId>PQNV9IS97EKYNP5U</HostId></Error>
第 1 个账号: ❌❌❌❌❌
Expecting value: line 1 column 1 (char 0)

**Comment by ohspecial** [comment]
请问解决了没有，我也是这样

**Comment by h7ml** [comment]
+1 我目前使用隔壁家的 [iMaoTai-reserve](https://github.com/397179459/iMaoTai-reserve)
