### ISSUE TITLE
action运行了0.001秒就结束了，是我没有配置对吗~

### ISSUE THREAD

**Issue by sola237** [Sitoi/dailycheckin#27]
小白一个…不太懂，大大有时间方便的话帮忙回答下，谢谢

**Comment by Sitoi** [comment]
应该是的 没有获取的任何参数

**Comment by sola237** [comment]
原来是Secret参数没有写对地方…

**Comment by sola237** [comment]
还是不行。。不知道为啥，方糖能收到通知，但也只是提示任务用时0.0014秒，感觉是没成功-= -=

**Comment by Sitoi** [comment]
你cookie 什么的配置了吗？格式对吗？

**Comment by sola237** [comment]
cookie都设置了~cookie复制过来会自动换行，这个应该没问题吧（cookie没有打双引号，也没有加列表符号[]）

**Comment by Sitoi** [comment]
要加啊，仔细看文档，有例子

**Comment by Sitoi** [comment]
请根据模版重新开 issue ，此issue 不予回答！
