### ISSUE TITLE
[Request] 增加优酷自动签到和酷金币任务自动做的功能

### ISSUE THREAD

**Issue by ypq123456789** [Sitoi/dailycheckin#271]
### 🥰 需求描述

![0556d3bfff6b4b1419d52fd99f8e113](https://github.com/Sitoi/dailycheckin/assets/114487221/fc4392cd-c5ab-45e9-b9bd-094ea486b21e)
如图所示。

### 🧐 解决方案

暂时在github上和网络上没找到，所以请求大佬考虑下增加这个功能，酷金币可以兑换迅雷会员和百度云盘会员，还是很有用的！

**Comment by Sitoi** [comment]
这个需要会员吗？还是普通用户也可以？

**Comment by ypq123456789** [comment]
会员才能兑换礼品，但是做任务领取金币不需要会员。会员本身也可以通过金币兑换，可以花少量金币就可以兑换一天会员，拿到兑换资格，所以没有影响的哈。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月6日(周二) 下午3:16
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Sitoi/dailycheckin] [Request] 增加优酷自动签到和酷金币任务自动做的功能 (Issue #271)




 
这个需要会员吗？还是普通用户也可以？

**Comment by ypq123456789** [comment]
> 这个需要会员吗？还是普通用户也可以？

另外每日打卡，打卡一个礼拜也可以获得一天会员。
![156971488a79e4495917c94c1bb1ae3](https://github.com/Sitoi/dailycheckin/assets/114487221/751d7379-9cf0-4207-a745-711c65f74c90)
![80bccbe00f973d864cd346eb5a8d711](https://github.com/Sitoi/dailycheckin/assets/114487221/4dd845b2-c3b4-41ed-ae9f-a51df2326bb4)

**Comment by Sitoi** [comment]
不考虑
