### ISSUE TITLE
[Bug] I茅台显示签到成功，但没有申购

### ISSUE THREAD

**Issue by wavesbig** [Sitoi/dailycheckin#274]
### 💻 系统环境

Other Linux

### 📦 部署环境

Docker

### 🐛 问题描述

https://github.com/Sitoi/dailycheckin/issues/270

### 📝 运行日志
![image](https://github.com/Sitoi/dailycheckin/assets/34082148/c6d25a67-430b-43b1-bc94-3e1def737134)
![image](https://github.com/Sitoi/dailycheckin/assets/34082148/7b6f6fec-a2ef-43c0-b81c-ceb8088eaf56)
![微信图片_20240204094251](https://github.com/Sitoi/dailycheckin/assets/34082148/94da2e79-b81c-4572-b9c6-c8cd59fbc740)

**Comment by benyian** [comment]
i茅台-我的-申购单 有记录，但茅运不能拿，报40001

**Comment by dgulan** [comment]
你要从申购记录里看【我的--我的申购单--前往查看，从这里看申购历史记录】。
你的截图那个位置是不会显示的。

**Comment by wavesbig** [comment]
> 你要从申购记录里看【我的--我的申购单--前往查看，从这里看申购历史记录】。 你的截图那个位置是不会显示的。

ok 明天我再看看
