### ISSUE TITLE
[Bug] 关于百度贴吧签到失败的反馈

### ISSUE THREAD

**Issue by Xubin-Ou** [Sitoi/dailycheckin#277]
### 💻 系统环境

Other Linux

### 📦 部署环境

青龙

### 🐛 问题描述

环境是物理机-PVE-Debian-DockerQinglong
配置好了网页版抓取的百度cookie，运行起来也可以读取到我的账户信息
但是返回的全部数值都为0
观察日志也并未发现问题出在何处
但是我发现推送里面，当前版本：24.1.20 和 最新版本：24.2.6存在出入，不过我无法选择运行版本

## 开始执行... 2024-02-06 21:33:28

当前时间: 2024-02-06 21:33:29
当前版本: 24.1.20
使用配置文件路径: /ql/data/scripts/config.json

---------- 本次执行签到任务如下 ----------

「百度贴吧」账号数 : 1

----------开始执行「百度贴吧」签到----------
第 1 个账号: ✅✅✅✅✅

server 酱 Turbo 推送开始

## 执行结束... 2024-02-06 21:33:34  耗时 6 秒　　　　　
----------------------------------------------------------------
以下是server酱收到的日志
每日签到「百度贴吧！
帐号信息.
贴吧总数：0签到成功：0已经签到：0被屏蔽的：0签到失败：0
开始时间：2024-02-07 08:37:40
任务用时：1秒
当前版本：24.1.20
最新版本：24.2.6
项目地址：https://github.com/Sitoi/dailycheckin
11秒钟前

**Comment by Sitoi** [comment]
![image](https://github.com/Sitoi/dailycheckin/assets/32479597/c217946f-ea51-4081-bc20-6a0f047c8aa3)
参考这个方式获取cookie呢？

**Comment by Xubin-Ou** [comment]
我没有研究值得买的脚本，上面讲的是贴吧的cookie
我获取到的cookie能包括示例里面的各项，并且也套进去json格式校验，对于某些引号也添加了反斜杠标注
但是真正给脚本读取的时候就是显示全部0000

**Comment by Sitoi** [comment]
你参考这个方式获取cookie

**Comment by Xubin-Ou** [comment]
问题解决了，换成控制台-network-index.html条目下的cookie复制出来，然后校验json再对应加反斜杠，
导入运行，脚本就有正确的内容返回了。
与之前的获取方式相对比，通过index页面获取到的cookie多了BDUSS，BDUSS_BFESS，STOKEN，ab_sr这几个条目，可能是脚本假运行的问题所在，感谢作者指点~
