### ISSUE TITLE
i茅台签到成功推送显示设备id不一致和none[Bug] 

### ISSUE THREAD

**Issue by co-star** [Sitoi/dailycheckin#278]
### 💻 系统环境

Other Linux

### 📦 部署环境

青龙

### 🐛 问题描述

![image](https://github.com/Sitoi/dailycheckin/assets/21311900/c101ba9e-4be1-4343-b098-880ef0963e26)
![image](https://github.com/Sitoi/dailycheckin/assets/21311900/743fbe54-6c90-4a38-9256-51bc4b0bcbeb)

### 📝 运行日志

如上图

**Comment by Sitoi** [comment]
实际签到情况如何呢？

**Comment by co-star** [comment]
> 实际签到情况如何呢？

也没有申请单

**Comment by co-star** [comment]
重新用更新的方法配置就又正常了
