### ISSUE TITLE
[Bug] 在使用main.py获取account.json时发生错误

### ISSUE THREAD

**Issue by xw0811** [Sitoi/dailycheckin#279]
### 💻 系统环境

Windows

### 📦 部署环境

本地

### 🐛 问题描述

在使用main.py获取account.json时发生错误，KeyError: 'geocodes'

### 📝 运行日志

Traceback (most recent call last):
  File "main copy.py", line 156, in <module>
    location_select: dict = get_location()
  File "main copy.py", line 134, in get_location
    selects = select_geo(location)
  File "main copy.py", line 76, in select_geo
    geocodes: list = resp.json()["geocodes"]
KeyError: 'geocodes'

**Comment by Sitoi** [comment]
可能是地址识别不到，建议具体到xxx路

**Comment by github-h** [comment]
> 可能是地址识别不到，建议具体到xxx路

其实好像是高德的key有问题 新申请的key需要搭配安全密钥一起使用

**Comment by xw0811** [comment]
> 可能是地址识别不到，建议具体到xxx路

尝试过，依然报错。

**Comment by hanyuanda** [comment]
> > 可能是地址识别不到，建议具体到xxx路
> 
> 尝试过，依然报错。

最后解决了吗》我遇到了同样的问题

**Comment by hanyuanda** [comment]
作为一个非编程领域的人，看了一晚上代码都快学会python了，也没搞懂咋回事。

**Comment by hanyuanda** [comment]
刚刚用了别的手段自己获取了token和id以及经纬度，自己写了一个json，明天跑一下试试吧。

**Comment by Sitoi** [comment]
![image](https://github.com/Sitoi/dailycheckin/assets/32479597/93c9047c-28fb-4f96-8928-5415771f7bd4)
高德地图的key 使用这个选项

**Comment by github-h** [comment]
> ![image](https://private-user-images.githubusercontent.com/32479597/304735775-93c9047c-28fb-4f96-8928-5415771f7bd4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwMDcyNDksIm5iZiI6MTcwODAwNjk0OSwicGF0aCI6Ii8zMjQ3OTU5Ny8zMDQ3MzU3NzUtOTNjOTA0N2MtMjhmYi00Zjk2LTg5MjgtNTQxNTc3MWY3YmQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE1VDE0MjIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwNGM0ZGZkNmQ5MzMzZDg2OTAyZDQ4OTJlMmRiMjQ3NjBkYTdjYjgyNzdiNjU5NmYwZTliMjc2NmM4YzYxZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XB6PJ8G8fcWZzQpACjshLKX22Vf12XTDCuAE_Mw1xaM) 高德地图的key 使用这个选项

是的是的 选错平台了 刚刚测试了一下没有问题
