### ISSUE TITLE
微博签到。 有现成的 想添加到你的docker上。

### ISSUE THREAD

**Issue by 50733364** [Sitoi/dailycheckin#28]
## 期望增加的功能

A：能添加个微博跟微博钱包的签到吗？ 有个仓库有现成的圈X版本。  作者是Sunert 的。 想弄到docker上运行。

## 入口

A：

**Comment by Sitoi** [comment]
提交个脚本地址

**Comment by 50733364** [comment]
https://github.com/Sunert/Scripts

Task文件夹里 需要的参数在git开头的文件里

**Comment by 50733364** [comment]
大佬有添加上去吗？

**Comment by 50733364** [comment]
要是方便的话 我这还有个滴滴的。 您也看下？

**Comment by Sitoi** [comment]
app 暂不做支持 需要获得 cookie 太多。
