### ISSUE TITLE
[Request] 小米运动刷步

### ISSUE THREAD

**Issue by benyian** [Sitoi/dailycheckin#280]
### 🥰 需求描述

目前zepp无法支撑手机号注册，只能用邮箱注册，能否增加邮箱刷步途径

### 🧐 解决方案

可参考https://github.com/miranda0111/xmydsbs

**Comment by Sitoi** [comment]
可以加tg  或qq 群私聊发下邮箱账号，用来测试一下吗？

**Comment by Sitoi** [comment]
更新到 24.2.20 版本即可 
https://sitoi.github.io/dailycheckin/settings/mimotion/
