### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by rarawu** [Sitoi/dailycheckin#282]
### 💻 系统环境

Windows

### 📦 部署环境

Docker

### 🐛 问题描述

有道云笔记签到显示“获取账号信息失败: list index out of range”，我是使用chrome f12，刷新copy所有的cookie信息粘贴进去的。
![PixPin_2024-02-17_21-06-55](https://github.com/Sitoi/dailycheckin/assets/38600759/7effcf56-6ef0-4dc9-8d83-ddd3e6cc2955)

**Comment by Sitoi** [comment]
cookie 有问题
