### ISSUE TITLE
奥拉星签到无反应

### ISSUE THREAD

**Issue by JerryChuanzhan** [Sitoi/dailycheckin#283]
### 💻 系统环境

Ubuntu

### 📦 部署环境

青龙

### 🐛 问题描述

按照配置，配置奥拉星签到，无推送、无效果

### 📝 运行日志

1

**Comment by Sitoi** [comment]
cookie 有问题吧

**Comment by JerryChuanzhan** [comment]
配置了奥拉星，但是看日志没有执行，是因为配置文件的配置有问题？cookie的话应该是没有问题的，别的执行都是可以正常的
| 发件人 | ***@***.***> |
| 发送日期 | 2024年2月19日 09:43 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [Sitoi/dailycheckin] 奥拉星签到无反应 (Issue #283) |

cookie 有问题吧
