### ISSUE TITLE
[Bug] V2EX 签到失败，如何可以如何设置为不使用代理？

### ISSUE THREAD

**Issue by ekodong** [Sitoi/dailycheckin#284]
### 💻 系统环境

Other Linux

### 📦 部署环境

本地

### 🐛 问题描述

V2EX 签到失败，配置文件一定要配置代理才行，如何修改配置为不使用代理？
![image](https://github.com/Sitoi/dailycheckin/assets/50974390/4bec7db7-67bf-4749-8d57-0a64b0c4a291)

### 📝 运行日志

----------开始执行「V2EX 论坛」签到----------
第 1 个账号: ❌❌❌❌❌
HTTPSConnectionPool(host='www.v2ex.com', port=443): Max retries exceeded with url: /mission/daily (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc5ece2e8e0>: Failed to establish a new connection: [Errno 111] Connection refused')))

**Comment by Sitoi** [comment]
把proxy 删了就行

**Comment by ekodong** [comment]
删掉proxy会报错，已经尝试过的。
![image](https://github.com/Sitoi/dailycheckin/assets/50974390/5ca2eacf-12e3-4f22-aad8-af725821e13c)
配置文件如下：
![image](https://github.com/Sitoi/dailycheckin/assets/50974390/36f84b2f-25cf-4a07-b7f6-cccd9fcca4da)

**Comment by Sitoi** [comment]
没有代理 连不上这个
