### ISSUE TITLE
[Request] 请求增加一个推送平台 pushme

### ISSUE THREAD

**Issue by liubin0520** [Sitoi/dailycheckin#285]
### 🥰 需求描述

请求增加 一个推送平台 https://push.i-i.me/ 类似于ios的bark

### 🧐 解决方案

请求增加 一个推送平台 https://push.i-i.me/ 类似于ios的bark

**Comment by Sitoi** [comment]
等我整个 安卓手机

**Comment by Sitoi** [comment]
归档到 projects 中 https://github.com/users/Sitoi/projects/1 关闭 issue
