### ISSUE TITLE
[Bug] imaotai无法正确领取水滴

### ISSUE THREAD

**Issue by bzsss** [Sitoi/dailycheckin#289]
### 💻 系统环境

Other Linux

### 📦 部署环境

青龙

### 🐛 问题描述

在完成imaotai运行后，无法自动领取水滴，需要再次运行脚本后才能领取

### 📝 运行日志

申购结果: 申购完成，请于2月22日18:00查看预约申购结果

小茅运: 任务未完成，无法领取奖励

申购结果: 申购完成，请于2月22日18:00查看预约申购结果

小茅运: 任务未完成，无法领取奖励

**Comment by bzsss** [comment]
当前时间: 2024-02-22 09:04:43
当前版本: 24.2.20
使用配置文件路径: /ql/data/scripts/config.json

**Comment by drw2005** [comment]
同样的情况，有没有大佬给指点一下原因？

**Comment by a390685320** [comment]
![image](https://github.com/Sitoi/dailycheckin/assets/135823375/5d9b9560-722d-4898-8c35-d4e5750f622d)
我的怎么跟你们的不一样，显示预约了，但是订单里没有

**Comment by Sitoi** [comment]
24.2.27 版本已修复
