### ISSUE TITLE
添加Bark推送支持

### ISSUE THREAD

**Issue by hmsjy2017** [Sitoi/dailycheckin#29]
## 期望增加的功能

A：Bark是一个小工具，使用简单 http 请求给自己的 iPhone 发推送 

## 入口

A：Bark 介绍：https://www.v2ex.com/t/467407
### 后端
后端代码：https://github.com/Finb/bark-server
后端部署文档https://day.app/2018/06/bark-server-document/
### 客户端
支持全平台，支持多种使用方式。
iOS 客户端：https://github.com/Finb/Bark
Chrome插件：https://github.com/xlvecle/Bark-Chrome-Extension
Chrome插件（自动复制版）：https://github.com/xlvecle/Bark-Chrome-Extension
在线定时发送：https://api.ihint.me/bark.html
Windows推送客户端：https://github.com/HsuDan/BarkHelper
跨平台命令行应用：https://github.com/JasonkayZK/bark-cli
Quicker动作：https://getquicker.net/Sharedaction?code=e927d844-d212-4428-758d-08d69de12a3b
Wox版：https://github.com/Zeroto521/Wox.Plugin.Bark

**Comment by Sitoi** [comment]
已添加！
