### ISSUE TITLE
爱奇艺签到总是报SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING]

### ISSUE THREAD

**Issue by Rawwiin** [Sitoi/dailycheckin#292]
### 💻 系统环境

Windows

### 📦 部署环境

青龙

### 🐛 问题描述

![1708668946932](https://github.com/Sitoi/dailycheckin/assets/40519176/4777f750-0e7b-43b6-96c1-84c040d8e63e)

**Comment by Sitoi** [comment]
网络问题，你是不是广告规则杀掉了
