### ISSUE TITLE
[Request] 增加imaotai防黑号机制

### ISSUE THREAD

**Issue by juneren26** [Sitoi/dailycheckin#296]
### 🥰 需求描述

当前代码确实能实现自动申购功能，但是该代码目前永远不可能成功实现imaotai申购，因为imaotai有用户行为分析黑号算法，个人揣测可能有用户常用设备识别、ip、个人常规访问习惯等

### 🧐 解决方案

个人设备user-agent抓取伪装、ip伪装、定时任务时间点9-10点间随机等，具体黑号算法仍需大量分析

**Comment by Sitoi** [comment]
黑号是会有提醒还是什么吗？

**Comment by Rolanddaan** [comment]
现在拉取不到依赖了

**Comment by juneren26** [comment]
参考该文章，imaotai应该有一套用户操作行为的分析算法来判定，一旦被判定为非人工操作，极可能黑号，大佬目前项目的star数已经算比较高了，说明用户不少，可以在readme里面加条信息，用该脚本成功申购的可带截图反馈给你https://zhuanlan.zhihu.com/p/624843647
