### ISSUE TITLE
[Bug]  请问这个爱奇艺是不是签到失败了呢？

### ISSUE THREAD

**Issue by fl1906** [Sitoi/dailycheckin#297]
### 💻 系统环境

Other Linux

### 📦 部署环境

青龙

### 🐛 问题描述

现在已经刷到了 7394秒, 数据同步有延迟, 仅供参考
现在已经刷到了 7464秒, 数据同步有延迟, 仅供参考
现在已经刷到了 7542秒, 数据同步有延迟, 仅供参考
现在已经刷到了 7658秒, 数据同步有延迟, 仅供参考
{'code': 'A00000', 'msg': '成功', 'data': None}
{'code': 'A00000', 'msg': '成功', 'data': None}
{'code': 'A00000', 'msg': '成功', 'data': None}
第 1 个账号: ❌❌❌❌❌
'daily'

**Comment by Sitoi** [comment]
非会员账号没有适配好，但抽奖任务已经完成
