### ISSUE TITLE
[Bug] 试用青龙面板 任务执行成功 但bark不推送

### ISSUE THREAD

**Issue by myrena** [Sitoi/dailycheckin#299]
### 💻 系统环境

Other Linux

### 📦 部署环境

青龙

### 🐛 问题描述

"BARK_URL": "https://api.day.app/c**ZyCBx5wRhxbc4f/",
  "MERGE_PUSH": "true",

配置文件如上，请问还需要配置什么吗？

### 📝 运行日志

----------开始执行「什么值得买」签到----------
第 1 个账号: ✅✅✅✅✅

Bark 推送开始

## 执行结束... 2024-02-26 14:16:52  耗时 6 秒

**Comment by Sitoi** [comment]
能ping 通吗？

**Comment by myrena** [comment]
我青龙面板执行其他任务，可以推送成功的

Sitoi ***@***.***> 于2024年2月26日周一 14:43写道：

**Comment by myrena** [comment]
ping api.day.app
PING api.day.app (43.155.109.24) 56(84) bytes of data.
64 bytes from 43.155.109.24 (43.155.109.24): icmp_seq=1

**Comment by Tizzy-3** [comment]
+1  我的bark也不推送

**Comment by fghs123** [comment]
**查看bark的记录，应该问题是最后这段dailycheckin的链接没有做url编码。**

`2024-02-28`` 09:00:04     INFO    172.17.0.1 -> [[93m 404 [0m] [96m GET     [0m 42.314µs / => /************/%E3%80%8Ci%E8%8C%85%E5%8F%B0%E3%80%8D%0A%E6%89%8B%E6%9C%BA%E5%8F%B7:%201**********%0A%E7%9C%81%E4%BB%BD%E5%9F%8E%E5%B8%82:%20******%0A%E7%94%B3%E8%B4%AD%E7%BB%93%E6%9E%9C:%20%E7%94%B3%E8%B4%AD%E5%AE%8C%E6%88%90%EF%BC%8C%E8%AF%B7%E4%BA%8E2%E6%9C%8828%E6%97%A518:00%E6%9F%A5%E7%9C%8B%E9%A2%84%E7%BA%A6%E7%94%B3%E8%B4%AD%E7%BB%93%E6%9E%9C%0A%E5%B0%8F%E8%8C%85%E8%BF%90:%20%E4%BB%BB%E5%8A%A1%E6%9C%AA%E5%AE%8C%E6%88%90%EF%BC%8C%E6%97%A0%E6%B3%95%E9%A2%86%E5%8F%96%E5%A5%96%E5%8A%B1%0A%E7%94%B3%E8%B4%AD%E7%BB%93%E6%9E%9C:%20%E7%94%B3%E8%B4%AD%E5%AE%8C%E6%88%90%EF%BC%8C%E8%AF%B7%E4%BA%8E2%E6%9C%8828%E6%97%A518:00%E6%9F%A5%E7%9C%8B%E9%A2%84%E7%BA%A6%E7%94%B3%E8%B4%AD%E7%BB%93%E6%9E%9C%0A%E5%B0%8F%E8%8C%85%E8%BF%90:%20None%0A%E2%80%94%E2%80%94%E2%80%94%E2%80%94%E2%80%94%E2%80%94%E2%80%94%E2%80%94%E2%80%94%E2%80%94%E2%80%94%E2%80%94%0A%0A%E5%BC%80%E5%A7%8B%E6%97%B6%E9%97%B4:%202024-02-28%2009:00:00%0A%E4%BB%BB%E5%8A%A1%E7%94%A8%E6%97%B6:%202%20%E7%A7%92%0A%E5%BD%93%E5%89%8D%E7%89%88%E6%9C%AC:%2024.2.22%0A%E6%9C%80%E6%96%B0%E7%89%88%E6%9C%AC:%2024.2.27%0A%E9%A1%B9%E7%9B%AE%E5%9C%B0%E5%9D%80:%20https://github.com/Sitoi/dailycheckin`


P.S. bark的FAQ
[https://bark.day.app/#/faq?id=%e6%8e%a8%e9%80%81%e7%89%b9%e6%ae%8a%e5%ad%97%e7%ac%a6%e5%af%bc%e8%87%b4%e6%8e%a8%e9%80%81%e5%a4%b1%e8%b4%a5%ef%bc%8c%e6%af%94%e5%a6%82-%e6%8e%a8%e9%80%81%e5%86%85%e5%ae%b9%e5%8c%85%e5%90%ab%e9%93%be%e6%8e%a5%ef%bc%8c%e6%88%96%e6%8e%a8%e9%80%81%e5%bc%82%e5%b8%b8-%e6%af%94%e5%a6%82-%e5%8f%98%e6%88%90%e7%a9%ba%e6%a0%bc](url)

> 能ping 通吗？

**Comment by Sitoi** [comment]
BUG 是因为 Bark 识别到 Url 推送就失败了，还是建议换一个推送吧

**Comment by Sitoi** [comment]
即使是编码了 也没用

**Comment by Sitoi** [comment]
识别到 http https 就会出问题

**Comment by Sitoi** [comment]
下一个版本会修复这个问题
