### ISSUE TITLE
大佬，请问多账号怎么填写？

### ISSUE THREAD

**Issue by r0ckmifan** [Sitoi/dailycheckin#3]
是在新建一个环境变量名称呢，还是用什么字符连接呢？

**Comment by Sitoi** [comment]
> 是在新建一个环境变量名称呢，还是用什么字符连接呢？

是列表格式的，直接复制一份就行

**Comment by r0ckmifan** [comment]
> > 是在新建一个环境变量名称呢，还是用什么字符连接呢？
> 
> 是列表格式的，直接复制一份就行

没明白Secrets 环境变量名称的值应该怎么填写，比如爱奇艺的值是否为
"IQIYI_COOKIE_LIST": [
    {
      "iqiyi_cookie": "xxxxxx"
    }
  ]

**Comment by Sitoi** [comment]
> > > 是在新建一个环境变量名称呢，还是用什么字符连接呢？
> > 
> > 
> > 是列表格式的，直接复制一份就行
> 
> 没明白Secrets 环境变量名称的值应该怎么填写，比如爱奇艺的值是否为
> "IQIYI_COOKIE_LIST": [
> {
> "iqiyi_cookie": "xxxxxx"
> }
> ]


```json
[
    {
        "iqiyi_cookie":"xxxxxx"
    },
    {
        "iqiyi_cookie":"xxxxxx"
    }
]
```
基本上都是这样就可以了

**Comment by Sitoi** [comment]
Secrets 变量名是 IQIYI_COOKIE_LIST

值是 
```json
[
    {
        "iqiyi_cookie":"xxxxxx"
    },
    {
        "iqiyi_cookie":"xxxxxx"
    }
]
```

**Comment by r0ckmifan** [comment]
大佬麻烦你看下，我按照这个格式网易云还有贴吧都可以，爱奇艺和腾讯视频不行，是cookie有问题吗？

[
    {
      "iqiyi_cookie": "cookie: QC005=7e30fdd75c48dfa4a7b85d9eea2a5169; QC006=23b792318459cda0d13c65c34ab2c021; QC008=1608626475.1608626475.1608626475.1; __uuid=e8923592-930e-1aa0-fc6a-5c1a10e20648; nu=0; QC180=true; QC173=0; P00004=.1608626477.71d9f09644; QP0030=1; QP007=720; P00001=59CH7Bm3K0N10TDs5K2OkCsJM11NC4tIyRNE2hil9eQdDMbR5YSm3Sm1k8PSm1LjcUPMfN31; P00003=2110160131; P00010=2110160131; P01010=1608652800; P00007=59CH7Bm3K0N10TDs5K2OkCsJM11NC4tIyRNE2hil9eQdDMbR5YSm3Sm1k8PSm1LjcUPMfN31; P00PRU=2110160131; P00002=%7B%22uid%22%3A%222110160131%22%2C%22pru%22%3A2110160131%2C%22user_name%22%3A%2218659306356%22%2C%22nickname%22%3A%22Rick.rose%22%2C%22pnickname%22%3A%22Rick.rose%22%2C%22type%22%3A4%2C%22email%22%3A%22%22%7D; QC160=%7B%22u%22%3A%2218659306356%22%2C%22lang%22%3A%22%22%2C%22local%22%3A%7B%22name%22%3A%22%E4%B8%AD%E5%9B%BD%E5%A4%A7%E9%99%86%22%2C%22init%22%3A%22Z%22%2C%22rcode%22%3A48%2C%22acode%22%3A%2286%22%7D%2C%22type%22%3A%22p1%22%7D; QC170=1; QYABEX={"mergedAbtest":"1258_C,1651_B","pcw_home_sorting":{"value":"2","abtest":"1258_C"},"PCW-Home-List":{"value":"1","abtest":"1651_B"}}; QC163=1; QC175=%7BXXXXXXX%2C%22ct%22%3A1608627343908%7D; QP0013=1; QY_PUSHMSG_ID=7e30fdd75c48dfa4a7b85d9eea2a5169; QC112=weid1608627586949; 7e30fdd75c48dfa4a7b85dXXXXXXXXXXXXXX08627586.1; QC179=%7B%22vipTypes%22%3A%221%22%2C%22userIcon%22%3A%22%2F%2Fimg7.iqiyipic.com%2Fpassport%2F20201127%2Fb9%2F71%2Fpassport_2110160131_160647093088611_130_130.png%22%2C%22%22%2C%22uid%22%3A2110160131%7D; QP008=1320; QC007=https%253A%252F%252Fwww.baidu.com%252Fs%253Fie%253DUTF-8%2526wd%253D%2525E7XXXXXX2525E8%252589%2525BA; QC010=133903626; QP0022=CNC%7CHeNan-42.233.95.121%7Cvcdn_Rcache_luoyang3_cnc; __dfp=a0867490f8b63241d2ba1beff65fb8fabe10b25bb11172cd423da7c0fabdbf34ff@1609922474901@1608626475901"
    }
]

**Comment by Sitoi** [comment]
值多了cookie：

**Comment by r0ckmifan** [comment]
也不知道试了十几次了，还是错误，有三个都弄不了，全民k哥，腾讯爱奇艺，下面是爱奇艺报错，不知道哪出问题了。

##***group***Run python3 index.py
***36;1mpython3 index.py***0m
shell: /bin/bash -e ***0***
env:
  pythonLocation: /opt/hostedtoolcache/Python/3.7.9/x64
  IS_GITHUB_ACTION: true
  DINGTALK_SECRET: 
  DINGTALK_ACCESS_TOKEN: 
  SCKEY: 
  QMSG_KEY: 
  TG_BOT_TOKEN: ***
  TG_USER_ID: ***
  COOLPUSHSKEY: 
  COOLPUSHQQ: 
  COOLPUSHWX: 
  COOLPUSHEMAIL: 
  CITY_NAME_LIST: ***
  MOTTO: 
  IQIYI_COOKIE_LIST: ***
  VQQ_COOKIE_LIST: 
  POJIE_COOKIE_LIST: ***
  YOUDAO_COOKIE_LIST: ***
  KGQQ_COOKIE_LIST: 
  MUSIC163_ACCOUNT_LIST: ***
  ONEPLUSBBS_COOKIE_LIST: 
  FMAPP_ACCOUNT_LIST: 
  BAIDU_URL_SUBMIT_LIST: 
  TIEBA_COOKIE_LIST: ***
  BILIBILI_COOKIE_LIST: 
##***endgroup***
Traceback (most recent call last):
  File "index.py", line 268, in <module>
    main_handler(event=event, context=None)
  File "index.py", line 101, in main_handler
    iqiyi_cookie_list = json.loads(os.getenv("IQIYI_COOKIE_LIST", ***)) if os.getenv("IQIYI_COOKIE_LIST") else ***
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 3 column 915 (char 922)
##***error***Process completed with exit code 1.

**Comment by Sitoi** [comment]
去 http://www.json.cn/ 网站格式化一下数据 确保没有错误 

你把值放到这个网站格式化一下

**Comment by r0ckmifan** [comment]
> 去 http://www.json.cn/ 网站格式化一下数据 确保没有错误
> 
> 你把值放到这个网站格式化一下

提示这个，是cookie错了吗
Error: 在第3行发生解析错误 :
...; QC170=1; QYABEX={"mergedAbtest":"1258_
                  
此处缺少'EOF', '}', ':', ',', ']'字符, 实际上是一个 'undefined'

**Comment by Sitoi** [comment]
> > 去 http://www.json.cn/ 网站格式化一下数据 确保没有错误
> 
> > 
> 
> > 你把值放到这个网站格式化一下
> 
> 
> 
> 提示这个，是cookie错了吗
> 
> 
> 
> Error: 在第3行发生解析错误 :
> 
> ...; QC170=1; QYABEX={"mergedAbtest":"1258_
> 
>                   
> 
> 此处缺少'EOF', '}', ':', ',', ']'字符, 实际上是一个 'undefined'

是你的参数错了 不符合 json 格式。

**Comment by r0ckmifan** [comment]
这个是cookie的内容，那能改吗？

**Comment by Sitoi** [comment]
> 这个是cookie的内容，那能改吗？

你开无痕模式重新获取一个 cookie 吧 正常的应该没有这些

**Comment by r0ckmifan** [comment]
不正我的cookie，开了无痕换还是有，脸黑

**Comment by r0ckmifan** [comment]
刚刚试了下，从有问题的哪里开始删掉，然后在 http://www.json.cn/ 解析了下没问题，更新了环境变量可以成功签到了。

大佬这么晚还在帮忙解答，多谢多谢。

**Comment by r0ckmifan** [comment]
大佬，这个还是参数问题吗？我在json上解析了，没发现错误。

##***endgroup***
Traceback (most recent call last):
  File "index.py", line 268, in <module>
    main_handler(event=event, context=None)
  File "index.py", line 105, in main_handler
    vqq_cookie_list = json.loads(os.getenv("VQQ_COOKIE_LIST", ***)) if os.getenv("VQQ_COOKIE_LIST") else ***
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 5 column 2 (char 1120)
##***error***Process completed with exit code 1.

**Comment by Sitoi** [comment]
你加我 QQ 吧 133397418
