### ISSUE TITLE
云函数错误

### ISSUE THREAD

**Issue by Arrogance-H** [Sitoi/dailycheckin#30]
## 1.关于你要提交的问题

Q：是否搜索了 issue（包括已关闭的issue）

- [x] 没有类似的 issue 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装 Python
- [ ] 方法二：Docker
- [x] 方法三：腾讯云函数
- [ ] 方法四：GitHub Actions

### (1) 具体问题

A：云函数报错

### (2) 详细日志

A：ERROR RequestId:1163bae0-35f5-443f-915d-fdaf72576d33 Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/index.py\", line 60, in main_handler\n    raise e\n  File \"/var/user/index.py\", line 45, in main_handler\n    data = json.loads(f.read())\n  File \"/var/lang/python3/lib/python3.6/json/__init__.py\", line 354, in loads\n    return _default_decoder.decode(s)\n  File \"/var/lang/python3/lib/python3.6/json/decoder.py\", line 339, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/var/lang/python3/lib/python3.6/json/decoder.py\", line 357, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 10 column 3 (char 205)","statusCode":430}

**Comment by Sitoi** [comment]
config.json 的问题，请严格按照教程来。确保是 Json 格式
