### ISSUE TITLE
[Request] 请求增加一个IMAOTAI的每日晚上6点申购结果自动查询及推送功能

### ISSUE THREAD

**Issue by 396910028** [Sitoi/dailycheckin#300]
### 🥰 需求描述

请求增加一个IMAOTAI的每日晚上6点申购结果自动查询及推送功能

### 🧐 解决方案

尝试抓包了下 实现方式应该比较简单
<img width="640" alt="微信图片_20240226151920" src="https://github.com/Sitoi/dailycheckin/assets/23514766/48dd391e-898d-4d11-a893-151129051b9e">
![微信图片_20240226151925](https://github.com/Sitoi/dailycheckin/assets/23514766/6771c3f5-9ffe-4fbe-9bd0-91a036d04e7e)

**Comment by drw2005** [comment]
支持一下，这样就更方便了。

**Comment by tangtang666** [comment]
预约成功不是有短信吗

**Comment by cat-kun** [comment]
你都抓包出来了，自己写一个监控

**Comment by Sitoi** [comment]
半项目主打每日一次运行，暂不考虑支持，可以自己修改源码或者新写脚本。
