### ISSUE TITLE
IMAOTAI签到超时

### ISSUE THREAD

**Issue by nxppru** [Sitoi/dailycheckin#302]
### 💻 系统环境

Other Linux

### 📦 部署环境

青龙

### 🐛 问题描述

青龙v2.17.1

## 开始执行... 2024-02-28 09:00:01

当前时间: 2024-02-28 09:00:03
当前版本: 24.2.27
使用配置文件路径: /ql/data/scripts/config.json

---------- 本次执行签到任务如下 ----------

「i茅台」账号数 : 1

----------开始执行「i茅台」签到----------
第 1 个账号: ❌❌❌❌❌
HTTPSConnectionPool(host='static.moutai519.com.cn', port=443): Max retries exceeded with url: /mt-backend/xhr/front/mall/resource/get (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f731b0e3810>, 'Connection to static.moutai519.com.cn timed out. (connect timeout=None)'))

**Comment by Sitoi** [comment]
你自己的网络问题
