### ISSUE TITLE
[Request] 求一个上汽大众超级APP自动签到的脚本

### ISSUE THREAD

**Issue by ThisLuckyB** [Sitoi/dailycheckin#303]
### 🥰 需求描述

需要签到、发帖、评论、点赞、转发的功能

### 🧐 解决方案

app下载地址
https://connectivity.svw-volkswagen.com/m/download

**Comment by Sitoi** [comment]
归档到 projects 中 https://github.com/users/Sitoi/projects/1 关闭 issue
