### ISSUE TITLE
[Bug] i茅台脚本运行日志提示成功实际没有申购到

### ISSUE THREAD

**Issue by hzl000** [Sitoi/dailycheckin#304]
### 💻 系统环境

Other Linux

### 📦 部署环境

Docker

### 🐛 问题描述

看运行日志imaotai的签到结果是成功的，但是我看推送的内容说无效的申购信息，后面我手动到app里面申购完后再运行一次脚本也是日志输出签到成功，耐力是可以成功自动获取的

### 📝 运行日志

![image](https://github.com/Sitoi/dailycheckin/assets/22371057/c9c81d2f-934b-4e29-9219-7c43d3006cfb)
![image](https://github.com/Sitoi/dailycheckin/assets/22371057/3e2d05d6-ce87-439a-bded-6c3c9d2d0f94)
![image](https://github.com/Sitoi/dailycheckin/assets/22371057/4e9aab69-b572-4e0e-92d0-558237f6046b)
![image](https://github.com/Sitoi/dailycheckin/assets/22371057/f1c4f87f-9189-49a3-91cd-b4608701473b)

**Comment by nxppru** [comment]
先在应用商店下载i茅台app，安装注册完善资料

**Comment by hzl000** [comment]
> 先在应用商店下载i茅台app，安装注册完善资料

我在i茅台里面是可以正常申购，跑脚本就提示无效的申购信息。脚本能正常帮我领取耐力，说明token userid这些应该都是正常工作的。你说的完善资料是指什么呢？

**Comment by buzhayandehuang** [comment]
> > 先在应用商店下载i茅台app，安装注册完善资料
> 
> 我在i茅台里面是可以正常申购，跑脚本就提示无效的申购信息。脚本能正常帮我领取耐力，说明token userid这些应该都是正常工作的。你说的完善资料是指什么呢？

我之前和你一样，你把mian.py更新下，重新跑下新的，然后复制到青龙就行了
