### ISSUE TITLE
[Bug] IMAOTAI运行报错

### ISSUE THREAD

**Issue by samxxxxx** [Sitoi/dailycheckin#305]
### 💻 系统环境

Other Linux

### 📦 部署环境

青龙

### 🐛 问题描述

![Snipaste_2024-02-29_16-07-42](https://github.com/Sitoi/dailycheckin/assets/47911690/755eaf92-d231-4ca2-a1ec-0cf7d9e4f668)

我配置了config.json，填写了IMAOTAI的JSON配置项，运行任务后得到这个错误提示。
请问一下这个是什么问题

## 开始执行... 2024-02-29 15:57:14

当前时间: 2024-02-29 15:57:14
当前版本: 24.2.27
使用配置文件路径: /ql/data/scripts/config.json

---------- 本次执行签到任务如下 ----------

「i茅台」账号数 : 1

----------开始执行「i茅台」签到----------
第 1 个账号: ❌❌❌❌❌
HTTPSConnectionPool(host='resource.moutai519.com.cn', port=443): Max retries exceeded with url: /mt-resource/resource/mtshops_pc/1709191806896/mtshops_pc.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbbf855acd0>: Failed to establish a new connection: [Errno -3] Try again'))

## 执行结束... 2024-02-29 15:57:16  耗时 2 秒　

# 另外我使用的是Debian 11版本系统

**Comment by samxxxxx** [comment]
是不是这个服务器IP被拉黑了，这个IP是香港的服务器，是这个原因吗？

**Comment by Jaxx4Fun** [comment]
不算 bug 吧，应该是你网络的问题，看着像是多次建立连接都失败了
