### ISSUE TITLE
[Request] 求大佬添加对 华印社区 自动签到的支持？

### ISSUE THREAD

**Issue by a410644209** [Sitoi/dailycheckin#307]
### 🥰 需求描述

华印社区的网址是：https://www.52cnp.com/ 登录需要验证码
华印社区的签到地址是：https://www.52cnp.com/k_misign-sign.html
华印社区是图文店广告公司设计师的聚集地，签到可获得印币，用于下载论坛上的部分pj版插件。插件可提高工作效率，但是经常失效，所以需要足够多的印币

### 🧐 解决方案

希望添加对 华印社区自动签到的支持

**Comment by Sitoi** [comment]
验证码破解需要太多的依赖，不考虑了
