### ISSUE TITLE
希望增加一个微信的反代配置[Request] 

### ISSUE THREAD

**Issue by kevinBobo** [Sitoi/dailycheckin#308]
### 🥰 需求描述

微信只支持公网ip的请求，nas没有公网ipv4无法直接请求微信，但是有公网的服务器可以做反代
希望加一个反代的企业微信配置，通过反向代理请求微信发送消息

### 🧐 解决方案

有反代配置的时候将微信域名替换为反代地址

**Comment by cat-kun** [comment]
nas自己配置frp穿透

**Comment by kevinBobo** [comment]
> nas自己配置frp穿透

frp只是把自己的服务暴漏到公网，这个是请求微信，是直接从本地发起的，和frp没有关系
