### ISSUE TITLE
你好，请问全家怎么抓cookie？stream抓了好久，都没显示有cookie的关键字

### ISSUE THREAD

**Issue by choyung** [Sitoi/dailycheckin#31]
你好，请问全家怎么抓cookie？stream抓了好久，都没显示有cookie的关键字

**Comment by Sitoi** [comment]
没用过 stream 我用的 fiddler

**Comment by nick814** [comment]
老大是安卓的？
我和上面的兄台一样  ip的 用steam抓  没有cookies   但是好像能用  明天试试看

**Comment by Sitoi** [comment]
> 老大是安卓的？
> 我和上面的兄台一样 ip的 用steam抓 没有cookies 但是好像能用 明天试试看

手动签到一次 里面应该有的，今早还抓了
