### ISSUE TITLE
[Bug] V2EX签到提示cookie可能过期

### ISSUE THREAD

**Issue by ekodong** [Sitoi/dailycheckin#313]
### 💻 系统环境

Other Linux

### 📦 部署环境

本地

### 🐛 问题描述

按照文档获取到cookie以后，写入config直接3分钟内执行就提示可能过期。

报错信息如下：
「V2EX 论坛」

签到失败: cookie 可能过期

————————————

开始时间: 2024-03-08 15:30:54

任务用时: 0 秒

当前版本: 24.3.7

最新版本: 24.3.7

**Comment by Sitoi** [comment]
看看是否没有转译，我这边测试都是正常的

**Comment by adowls** [comment]
我也提示cookie可能过期，似乎v2ex的cookie是base64编码过的
是24.3.11版本的

**Comment by adowls** [comment]
解码后也还是提示cookie 可能过期

**Comment by devswork** [comment]
同遇到此问题，重新登陆拿cookie也不行，config.json是格式没问题的，双引号的都加了/转义。

**Comment by devswork** [comment]
版本是  24.3.11
![Snipaste_2024-03-14_10-27-07](https://github.com/Sitoi/dailycheckin/assets/18701798/1bec2173-0028-46f0-87e8-d1679d99b239)

**Comment by devswork** [comment]
换另一个签到框架解决了，同一个 cookie，在 QD 上完美签成功

**Comment by ekodong** [comment]
> 换另一个签到框架解决了，同一个 cookie，在 QD 上完美签成功

帮忙指条路？

**Comment by zhsama** [comment]
the same issue, any solves?
