### ISSUE TITLE
是否能对外提供推送接口

### ISSUE THREAD

**Issue by cat-kun** [Sitoi/dailycheckin#314]
### 🥰 需求描述

想自己实现基于微信的消息订阅，推送到对应的人。而不是推送消息集合

### 🧐 解决方案

![IMG_0124](https://github.com/Sitoi/dailycheckin/assets/8529528/18dfaa67-68e9-4877-bb6e-c18355431344)

**Comment by Sitoi** [comment]
可以自行修改 dailycheckin/utils/message.py 文件
