### ISSUE TITLE
[Bug] iqiyi签到失败

### ISSUE THREAD

**Issue by sju168** [Sitoi/dailycheckin#315]
### 💻 系统环境

Other Linux

### 📦 部署环境

青龙

### 🐛 问题描述

升级到最新版后，出现这问题

当前版本: 24.3.7
使用配置文件路径: /ql/data/scripts/config.json

---------- 本次执行签到任务如下 ----------

「爱奇艺」账号数 : 1

----------开始执行「爱奇艺」签到----------
{'code': 'A00000', 'msg': '成功', 'data': None}
{'code': 'A00000', 'msg': '成功', 'data': None}
{'code': 'A00000', 'msg': '成功', 'data': None}
现在已经刷到了 0秒, 数据同步有延迟, 仅供参考
第 1 个账号: ❌❌❌❌❌
HTTPSConnectionPool(host='msg.qy.net', port=443): Max retries exceeded with url: /b?u=f6

**Comment by Sitoi** [comment]
网络问题
