### ISSUE TITLE
[Bug] i茅台，多账号签到时，只有第一个账号领耐力值成功，其他账号都领取失败

### ISSUE THREAD

**Issue by Chenyccc** [Sitoi/dailycheckin#316]
### 💻 系统环境

Other Linux

### 📦 部署环境

Docker

### 🐛 问题描述

 i茅台，多账号签到时，只有第一个账号领耐力值成功，其他账号都领取失败

**Comment by Chenyccc** [comment]
bug补充说明：
我的系统是Debian
1、更改crontab_list.sh中的执行时间，只要不是9:00执行，都会报错，具体情况如下：
即便更改了定时时间，但仍会在9:00执行，并且报错，申购结果: 'int' object has no attribute 'get'，在报这个错之后，登录app查看申购情况，有的时候能申购上，有的时候没有申购上
2、不更改执行时间，默认9:00执行，多个账号均能申购上，但是只有第一个账号领到耐力值，此时在控制台手动再执行一次，剩余账号耐力值才能领取成功（也就是说，需要执行两次才能保证均收购上，且耐力值领取成功）

**Comment by Felix-yao** [comment]
![bafc694eba41623353472aaa6b0d44c](https://github.com/Sitoi/dailycheckin/assets/26133973/809dee29-25e0-44fa-9cb9-08850df58528)
也是只有第一个账号耐力值领取成功

**Comment by drw2005** [comment]
同样的情况，只有第一帐号耐力值领取成功。
