### ISSUE TITLE
[Request] 网上国网，萤石，中国移动云盘能不能加入

### ISSUE THREAD

**Issue by 632225259** [Sitoi/dailycheckin#317]
### 🥰 需求描述

网上国网，萤石，中国移动云盘，中国移动，机场，能不能加入豪华套餐

### 🧐 解决方案

我目前用青龙面板

**Comment by ilanni2460** [comment]
+1

**Comment by simple603888** [comment]
中国移动云盘，中国移动 +1

**Comment by qiulifei992** [comment]
中国移动云盘，+1

**Comment by Sitoi** [comment]
归档到 projects 中 https://github.com/users/Sitoi/projects/1 关闭 issue
