### ISSUE TITLE
[Bug] 群晖搭建青龙面板，运行脚本命令及更新命令时都报错 Part.2

### ISSUE THREAD

**Issue by zhaosongonline** [Sitoi/dailycheckin#318]
### 💻 系统环境

Other Linux

### 📦 部署环境

青龙

### 🐛 问题描述

群晖搭建青龙面板，运行 Dailycheckin 指定脚本（包含） | task dailycheckin --include IQIYI YOUDAO TIEBA 时报错、且运行 Dailycheckin 更新 | task pip3 install dailycheckin --upgrade 时报错，请问如何解决呢？运行 Dailycheckin 更新的日志如下：

### 📝 运行日志

WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

**Comment by Sitoi** [comment]
这不是报错

**Comment by zhaosongonline** [comment]
> 这不是报错

那请问这个怎么处理呢？

**Comment by simple603888** [comment]
命令改成 task pip3 install dailycheckin --upgrade --root-user-action=ignore
