### ISSUE TITLE
[Bug] 什么值得买&爱奇艺签到失败

### ISSUE THREAD

**Issue by goku-jinglv** [Sitoi/dailycheckin#321]
### 💻 系统环境

Ubuntu

### 📦 部署环境

青龙

### 🐛 问题描述

----------开始执行「爱奇艺」签到----------
获取账号信息失败，错误信息: Expecting value: line 1 column 1 (char 0)
{'code': 'Q00304', 'msg': '用户登录信息失效', 'data': None}
{'code': 'Q00304', 'msg': '用户登录信息失效', 'data': None}
{'code': 'Q00304', 'msg': '用户登录信息失效', 'data': None}
第 1 个账号: ❌❌❌❌❌
'NoneType' object is not subscriptable
----------开始执行「什么值得买」签到----------
第 1 个账号: ❌❌❌❌❌
'latin-1' codec can't encode character '\u2026' in position 512: ordinal not in range(256)

**Comment by wdvipa** [comment]
爱奇艺是你自己的问题，cookie没抓对

**Comment by goku-jinglv** [comment]
> 爱奇艺是你自己的问题，cookie没抓对

感谢大佬回复，我是用火狐浏览器登录爱奇艺抓的cookie，需要直接从手机抓cookie吗？
