### ISSUE TITLE
获取通知失败

### ISSUE THREAD

**Issue by maizhike** [Sitoi/dailycheckin#324]
### 💻 系统环境

Windows

### 📦 部署环境

青龙

### 🐛 问题描述

----------开始执行「i茅台」签到----------
第 1 个账号: ❌❌❌❌❌
HTTPSConnectionPool(host='itunes.apple.com', port=443): Max retries exceeded with url: /cn/lookup?id=1600482450 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8f127df0>: Failed to establish a new connection: [Errno -3] Try again'))
----------开始执行「爱奇艺」签到----------
第 1 个账号: ❌❌❌❌❌
HTTPSConnectionPool(host='community.iqiyi.com', port=443): Max retries exceeded with url: /openApi/task/execute?agentType=1&agentversion=1&appKey=basic_pcw&authCookie=4cPXvBDu7zQ5hwpibm2tIFPYdm1Rq4m3bVQ8LCIGcVfD19WyjJpXEa1l6sc6PYEdraUm3f64&qyid=4f070735855049b2&sign=5c926a58b2195915e56c36cd1bfd144b&task_code=natural_month_sign&timestamp=1710668420188&typeCode=point&userId=4673116018057408 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8f127e20>: Failed to establish a new connection: [Errno -3] Try again'))

获取最新版本失败
获取重要通知失败: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/Sitoi/dailycheckin/issues?state=open&labels=%E9%80%9A%E7%9F%A5 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8f127e20>: Failed to establish a new connection: [Errno -3] Try again'))

**Comment by Rolanddaan** [comment]
脚本挂了
