### ISSUE TITLE
[Bug] 爱奇艺摇一摇规则校验失败

### ISSUE THREAD

**Issue by gthanmon** [Sitoi/dailycheckin#326]
### 💻 系统环境

Ubuntu

### 📦 部署环境

青龙

### 🐛 问题描述

爱奇艺摇一摇规则校验异常，已经持续很久了
![图片1](https://github.com/Sitoi/dailycheckin/assets/62300251/ac494a78-1c05-4e60-ab71-aebaa084545a)

## 开始执行... 2024-03-17 00:10:01

当前时间: 2024-03-17 00:10:01
当前版本: 24.3.11
使用配置文件路径: /ql/data/scripts/config.json

---------- 本次执行签到任务如下 ----------

「爱奇艺」账号数 : 1
「全民K歌」账号数 : 1
「百度贴吧」账号数 : 1

----------开始执行「爱奇艺」签到----------
{'code': 'A00000', 'msg': '成功', 'data': None}
{'code': 'A00000', 'msg': '成功', 'data': None}
{'code': 'A00000', 'msg': '成功', 'data': None}
现在已经刷到了 0秒, 数据同步有延迟, 仅供参考
现在已经刷到了 98秒, 数据同步有延迟, 仅供参考
现在已经刷到了 217秒, 数据同步有延迟, 仅供参考
现在已经刷到了 333秒, 数据同步有延迟, 仅供参考
现在已经刷到了 397秒, 数据同步有延迟, 仅供参考
现在已经刷到了 499秒, 数据同步有延迟, 仅供参考
现在已经刷到了 609秒, 数据同步有延迟, 仅供参考
现在已经刷到了 679秒, 数据同步有延迟, 仅供参考
现在已经刷到了 781秒, 数据同步有延迟, 仅供参考
现在已经刷到了 844秒, 数据同步有延迟, 仅供参考
现在已经刷到了 964秒, 数据同步有延迟, 仅供参考
现在已经刷到了 1075秒, 数据同步有延迟, 仅供参考
现在已经刷到了 1182秒, 数据同步有延迟, 仅供参考
现在已经刷到了 1285秒, 数据同步有延迟, 仅供参考
现在已经刷到了 1392秒, 数据同步有延迟, 仅供参考
现在已经刷到了 1470秒, 数据同步有延迟, 仅供参考
现在已经刷到了 1540秒, 数据同步有延迟, 仅供参考
现在已经刷到了 1613秒, 数据同步有延迟, 仅供参考
现在已经刷到了 1728秒, 数据同步有延迟, 仅供参考
现在已经刷到了 1790秒, 数据同步有延迟, 仅供参考
现在已经刷到了 1879秒, 数据同步有延迟, 仅供参考
现在已经刷到了 1946秒, 数据同步有延迟, 仅供参考
现在已经刷到了 2061秒, 数据同步有延迟, 仅供参考
现在已经刷到了 2137秒, 数据同步有延迟, 仅供参考
现在已经刷到了 2220秒, 数据同步有延迟, 仅供参考
现在已经刷到了 2298秒, 数据同步有延迟, 仅供参考
现在已经刷到了 2363秒, 数据同步有延迟, 仅供参考
现在已经刷到了 2478秒, 数据同步有延迟, 仅供参考
现在已经刷到了 2597秒, 数据同步有延迟, 仅供参考
现在已经刷到了 2715秒, 数据同步有延迟, 仅供参考
现在已经刷到了 2794秒, 数据同步有延迟, 仅供参考
现在已经刷到了 2889秒, 数据同步有延迟, 仅供参考
现在已经刷到了 2988秒, 数据同步有延迟, 仅供参考
现在已经刷到了 3050秒, 数据同步有延迟, 仅供参考
现在已经刷到了 3118秒, 数据同步有延迟, 仅供参考
现在已经刷到了 3181秒, 数据同步有延迟, 仅供参考
现在已经刷到了 3294秒, 数据同步有延迟, 仅供参考
现在已经刷到了 3389秒, 数据同步有延迟, 仅供参考
现在已经刷到了 3455秒, 数据同步有延迟, 仅供参考
现在已经刷到了 3515秒, 数据同步有延迟, 仅供参考
现在已经刷到了 3617秒, 数据同步有延迟, 仅供参考
现在已经刷到了 3716秒, 数据同步有延迟, 仅供参考
现在已经刷到了 3783秒, 数据同步有延迟, 仅供参考
现在已经刷到了 3893秒, 数据同步有延迟, 仅供参考
现在已经刷到了 3958秒, 数据同步有延迟, 仅供参考
现在已经刷到了 4025秒, 数据同步有延迟, 仅供参考
现在已经刷到了 4132秒, 数据同步有延迟, 仅供参考
现在已经刷到了 4217秒, 数据同步有延迟, 仅供参考
现在已经刷到了 4332秒, 数据同步有延迟, 仅供参考
现在已经刷到了 4402秒, 数据同步有延迟, 仅供参考
现在已经刷到了 4503秒, 数据同步有延迟, 仅供参考
现在已经刷到了 4601秒, 数据同步有延迟, 仅供参考
现在已经刷到了 4671秒, 数据同步有延迟, 仅供参考
现在已经刷到了 4770秒, 数据同步有延迟, 仅供参考
现在已经刷到了 4886秒, 数据同步有延迟, 仅供参考
现在已经刷到了 4972秒, 数据同步有延迟, 仅供参考
现在已经刷到了 5049秒, 数据同步有延迟, 仅供参考
现在已经刷到了 5135秒, 数据同步有延迟, 仅供参考
现在已经刷到了 5201秒, 数据同步有延迟, 仅供参考
现在已经刷到了 5297秒, 数据同步有延迟, 仅供参考
现在已经刷到了 5394秒, 数据同步有延迟, 仅供参考
现在已经刷到了 5513秒, 数据同步有延迟, 仅供参考
现在已经刷到了 5601秒, 数据同步有延迟, 仅供参考
现在已经刷到了 5666秒, 数据同步有延迟, 仅供参考
现在已经刷到了 5763秒, 数据同步有延迟, 仅供参考
现在已经刷到了 5830秒, 数据同步有延迟, 仅供参考
现在已经刷到了 5920秒, 数据同步有延迟, 仅供参考
现在已经刷到了 6011秒, 数据同步有延迟, 仅供参考
现在已经刷到了 6118秒, 数据同步有延迟, 仅供参考
现在已经刷到了 6188秒, 数据同步有延迟, 仅供参考
现在已经刷到了 6249秒, 数据同步有延迟, 仅供参考
现在已经刷到了 6353秒, 数据同步有延迟, 仅供参考
现在已经刷到了 6457秒, 数据同步有延迟, 仅供参考
现在已经刷到了 6562秒, 数据同步有延迟, 仅供参考
现在已经刷到了 6681秒, 数据同步有延迟, 仅供参考
现在已经刷到了 6747秒, 数据同步有延迟, 仅供参考
现在已经刷到了 6833秒, 数据同步有延迟, 仅供参考
现在已经刷到了 6941秒, 数据同步有延迟, 仅供参考
现在已经刷到了 7047秒, 数据同步有延迟, 仅供参考
现在已经刷到了 7162秒, 数据同步有延迟, 仅供参考
现在已经刷到了 7258秒, 数据同步有延迟, 仅供参考
现在已经刷到了 7357秒, 数据同步有延迟, 仅供参考
现在已经刷到了 7475秒, 数据同步有延迟, 仅供参考
现在已经刷到了 7578秒, 数据同步有延迟, 仅供参考
现在已经刷到了 7673秒, 数据同步有延迟, 仅供参考
第 1 个账号: ✅✅✅✅✅
----------开始执行「全民K歌」签到----------
第 1 个账号: ✅✅✅✅✅
----------开始执行「百度贴吧」签到----------
第 1 个账号: ✅✅✅✅✅

企业微信应用消息推送开始
企业微信应用消息推送开始
企业微信应用消息推送开始
企业微信应用消息推送开始

## 执行结束... 2024-03-17 00:10:38  耗时 37 秒

**Comment by Sitoi** [comment]
新版本修复
