### ISSUE TITLE
[Bug] 计划任务不执行 连续执行了四五天然后今天没有执行.. 

### ISSUE THREAD

**Issue by ihuanx** [Sitoi/dailycheckin#327]
### 💻 系统环境

Other Linux

### 📦 部署环境

Docker

### 🐛 问题描述

不知道为什么计划任务没有执行.. docker也没有挂.

**Comment by ihuanx** [comment]
临时解决方案 把crontab_list.sh的计划任务停掉  //避免二次任务
然后在容器外部创建计划任务  
用 docker exec -it dailycheckin dailycheckin 来执行每日任务

**Comment by Sitoi** [comment]
保留配置文件后，删除容器和镜像后，重新安装吧，没遇到过这种问题
