### ISSUE TITLE
[Request] 增加脚本日志的功能

### ISSUE THREAD

**Issue by interestingfrankking** [Sitoi/dailycheckin#328]
### 🥰 需求描述

大佬可以考虑给脚本增加个日志的功能吗

### 🧐 解决方案

大佬可以考虑给脚本增加个日志的功能吗

**Comment by Sitoi** [comment]
日志文件一直是有的吧

**Comment by Sitoi** [comment]
docker 会自动保存到 /dailycheckin/logs 目录下
