### ISSUE TITLE
[Bug] 百度贴吧，账号正常，签到为0

### ISSUE THREAD

**Issue by W727584152** [Sitoi/dailycheckin#329]
### 💻 系统环境

Ubuntu

### 📦 部署环境

青龙

### 🐛 问题描述

百度贴吧，账号正常，没有签到的贴吧  
![image](https://github.com/Sitoi/dailycheckin/assets/31676470/dce7a57e-5781-4df1-a327-4027e99d72d9)

![3d2964636eeabb3552299dec6f39676](https://github.com/Sitoi/dailycheckin/assets/31676470/6ce5a846-5ce9-42b1-b297-c077f8c4dbf3)

**Comment by Sitoi** [comment]
我记得tg群里有人有过这个问题，你看看聊天记录
