### ISSUE TITLE
什么值得买签到失败

### ISSUE THREAD

**Issue by fzx40195** [Sitoi/dailycheckin#33]
## 1.关于你要提交的问题

Q：是否搜索了 issue（包括已关闭的issue）

- [x ] 没有类似的 issue 

Q：是否仔细阅读了教程

- [x ] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装 Python
- [ ] 方法二：Docker
- [ ] 方法三：腾讯云函数
- [x ] 方法四：GitHub Actions

### (1) 具体问题

A：1、什么值得买签到失败，失败信息point  2、贴吧签到成功，但是没有推送，只推送了别的签到信息

### (2) 详细日志

***'error_code': 0, 'error_msg': '', 'data': ***'add_point': 0, 'checkin_num': 2, 'point': 185, 'exp': 272, 'gold': 0, 'prestige': 0, 'rank': 2, 'slogan': '<div class="signIn_data">今日已领<span class="red">0</span>积分，再签到<span class="red">1</span>天可领<span class="red">0</span>积分</div>', 'cards': '3', 'can_contract': 0, 'continue_checkin_days': 2, 'continue_checkin_reward_show': False***
【什么值得买】
签到状态: 签到失败
错误信息: 'point'
***'error_code': 0, 'error_msg': '', 'data': ***'add_point': 0, 'checkin_num': 2, 'point': 0, 'exp': 0, 'gold': 0, 'prestige': 0, 'rank': 0, 'slogan': '<div class="signIn_data">今日已领<span class="red">0</span>积分，再签到<span class="red">1</span>天可领<span class="red">0</span>积分</div>', 'cards': 0, 'can_contract': 0, 'continue_checkin_days': 2, 'continue_checkin_reward_show': False***
【什么值得买】
签到状态: 签到失败
错误信息: 'point'
Expecting value: line 1 column 1 (char 0)

**Comment by Sitoi** [comment]
什么值得买签到问题已修复，贴吧签到脚本无异常！

贴吧和什么值得买签到都是 web 端签到，请尝试重新获取 cookie。
