### ISSUE TITLE
[Bug] 有道云笔记提示有问题

### ISSUE THREAD

**Issue by motian0828** [Sitoi/dailycheckin#330]
### 💻 系统环境

Windows

### 📦 部署环境

本地

### 🐛 问题描述

----------开始执行「有道云笔记」签到----------
获取账号信息失败: list index out of range
第 1 个账号: ✅✅✅✅✅

### 📝 运行日志

----------开始执行「有道云笔记」签到----------
获取账号信息失败: list index out of range
第 1 个账号: ✅✅✅✅✅

**Comment by Sitoi** [comment]
cookie 问题

**Comment by motian0828** [comment]
cookie试了没问题，还是提示错误 ![image](https://github.com/Sitoi/dailycheckin/assets/19517236/e6bc225b-1814-4f17-a57d-ffc6524a291d)
