### ISSUE TITLE
[Bug] 在华为云上部署，提示OSError

### ISSUE THREAD

**Issue by ohspecial** [Sitoi/dailycheckin#333]
### 💻 系统环境

Other Linux

### 📦 部署环境

云函数

### 🐛 问题描述

报错提示如图，好像是Crypto这个库的问题，网上有个方法说换成其他库也是一样报错，请看看
![微信截图_20240326084834](https://github.com/Sitoi/dailycheckin/assets/105205583/e972558c-993f-4628-8368-6d7385819741)
![微信截图_20240326085449](https://github.com/Sitoi/dailycheckin/assets/105205583/f62a4abf-a4a6-4831-a957-59f61fd6b503)

**Comment by Sitoi** [comment]
安装这个 pycryptodome

**Comment by Sitoi** [comment]
python 版本 3.9以上

**Comment by ohspecial** [comment]
![微信截图_20240402092042](https://github.com/Sitoi/dailycheckin/assets/105205583/3f1853d2-facd-4373-a75f-da28a74c4d40)
![微信截图_20240402092813](https://github.com/Sitoi/dailycheckin/assets/105205583/97a55a8e-c204-4454-96d7-8789868e4b2f)
![微信截图_20240402092827](https://github.com/Sitoi/dailycheckin/assets/105205583/065a402b-6bc8-4c39-8cfc-dc30173d2bc6)
已经安装了的，但是就是在华为云上面运行不了，本地运行都没问题
