### ISSUE TITLE
[Bug] 24.3.19_i茅台申购时间过长？

### ISSUE THREAD

**Issue by dgulan** [Sitoi/dailycheckin#335]
### 💻 系统环境

macOS

### 📦 部署环境

青龙

### 🐛 问题描述

环境：在群晖docker 上部署青龙，运行dailycheckin，
问题：感觉升级到24.3.19之后，执行i茅台的预约申购时间变长，一个账号申购约需要70秒。
之前十来秒就能完成一个账号的申购；

## 开始执行... 2024-03-29 09:08:00

当前时间: 2024-03-29 09:08:01
当前版本: 24.3.19
使用配置文件路径: /ql/data/scripts/config.json

---------- 本次执行签到任务如下 ----------

「i茅台」账号数 : 5
「什么值得买」账号数 : 1

----------开始执行「i茅台」签到----------
第 1 个账号: ✅✅✅✅✅
第 2 个账号: ✅✅✅✅✅
第 3 个账号: ✅✅✅✅✅
第 4 个账号: ✅✅✅✅✅
第 5 个账号: ✅✅✅✅✅
----------开始执行「什么值得买」签到----------
第 1 个账号: ✅✅✅✅✅

## 执行结束...   耗时 317 秒

**Comment by Sitoi** [comment]
是的，为了领取小茅运
