### ISSUE TITLE
[Bug] 「Bilibili」 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by ihuanx** [Sitoi/dailycheckin#340]
### 💻 系统环境

Windows

### 📦 部署环境

本地

### 🐛 问题描述

任务是执行了 日志没有返回..  重新执行了任务又返回了 很怪

**Comment by tsvico** [comment]
遇到同样问题
![image](https://github.com/Sitoi/dailycheckin/assets/32492304/0ab5da60-6c20-4a06-b7d0-02822cda7f84)

**Comment by Sitoi** [comment]
cookie 问题吧
