### ISSUE TITLE
[Request] 请求新增一个自动领取epic免费游戏的功能

### ISSUE THREAD

**Issue by huoshuigege** [Sitoi/dailycheckin#341]
### 🥰 需求描述

epic每周都有免费游戏领取,希望能出一个自动领取的功能

### 🧐 解决方案

能否增加一个类似的脚本

### 📝 补充信息

无

**Comment by ksmarisa520** [comment]
附议

**Comment by Sitoi** [comment]
归档到 projects 中 https://github.com/users/Sitoi/projects/1 关闭 issue
