### ISSUE TITLE
可以支持cookiecloud的吗

### ISSUE THREAD

**Issue by taozuinb** [Sitoi/dailycheckin#342]
### 🥰 需求描述

cookie过期得手动一个个更新，如果可以支持cookiecloud自动拉取就完美了

### 🧐 解决方案

添加cookiecloud支持

**Comment by TaoRone** [comment]
支持！

**Comment by Sitoi** [comment]
归档到 projects 中 https://github.com/users/Sitoi/projects/1 关闭 issue
