### ISSUE TITLE
添加设置选项：签到失败才推送通知[Request] 

### ISSUE THREAD

**Issue by MicroGame0** [Sitoi/dailycheckin#343]
### 🥰 需求描述

添加设置选项，只有签到失败才推送通知

### 🧐 解决方案

config.json 添加一个设置选项

**Comment by 389377616** [comment]
附议，cookie没失效时候正常签到通不通知其实也无所谓，cookie失效了了通知一下，看到通知及时更新一下cookie正好。

**Comment by Sitoi** [comment]
是个好想法，接口改变之类的无法捕捉到全部的可能性，会漏掉很多信息，建议还是每天看一下吧
