### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by qazgp** [Sitoi/dailycheckin#344]
### 💻 系统环境

Other Linux

### 📦 部署环境

本地

### 🐛 问题描述

经常出现这个报错为什么

### 📝 运行日志

HTTPSConnectionPool(host='auth.aliyundrive.com', port=443): Max retries exceeded with url: /v2/account/token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe7bd20db50>: Failed to establish a new connection: [Errno -3] Try again'))

**Comment by Sitoi** [comment]
网络问题
