### ISSUE TITLE
[Request] 百度收录限制添加数量上限和随机抓取模式

### ISSUE THREAD

**Issue by silverQH** [Sitoi/dailycheckin#345]
### 🥰 需求描述

由于API提交数量，无法全站提交收录。
建议在config提供设置提交数量、并且提供选择3个：随机抓取TXT/取头部/取尾部 ，中的对应数量进行提交设置。

### 🧐 解决方案

[https://github.com/MHG-LAB/submit-urls-from-sitemap-to-search-engine/tree/main](url)
[https://github.com/waahah/pushSitemapUrls/blob/main/.gitignore](url)
这两个库可以参考一下。

**Comment by Sitoi** [comment]
归档到 projects 中 https://github.com/users/Sitoi/projects/1 关闭 issue
