### ISSUE TITLE
[Request] 增加龙湖app或者小程序的签到

### ISSUE THREAD

**Issue by Dron1sh** [Sitoi/dailycheckin#347]
### 🥰 需求描述

龙湖app或者小程序的每日签到支持

### 🧐 解决方案

api接入

**Comment by ksmarisa520** [comment]
为了高昂的物业费的龙湖业主也来附议

**Comment by Sitoi** [comment]
归档到 projects 中 https://github.com/users/Sitoi/projects/1 关闭 issue
