### ISSUE TITLE
[Request] 路径问题，导致无法运行。

### ISSUE THREAD

**Issue by liqiang945** [Sitoi/dailycheckin#349]
### 🥰 需求描述

我使用的是群晖的狂神套件里安装的青龙面板。按照教程运行
## 开始执行... 2024-04-17 10:01:35

当前时间: 2024-04-17 10:01:36
当前版本: 24.3.19
使用配置文件路径: /ql/data/scripts/config.json

## 执行结束...   耗时 1 秒　　　　　
导致失败，经过查询发现路径是/volume1/qinglong/scripts/config.json
怎么进行修改和调整，期待高手的指点。

### 🧐 解决方案

困扰两天，未解决

**Comment by ximu-tao** [comment]
可以在config.json相同路径下，创建一个python脚本文件
```
import os
import dailycheckin.main as dailycheckin
os.chdir("config.json所在的路径")
dailycheckin.checkin()
```
然后在定时任务中运行自己创建的脚本
