### ISSUE TITLE
【重要版本更新】

### ISSUE THREAD

**Issue by Sitoi** [Sitoi/dailycheckin#35]
![telegram-cloud-photo-size-5-6213238800545590995-y](https://user-images.githubusercontent.com/32479597/133954184-642ed6da-28f9-4943-a31a-54fd8b4efa27.jpg)

Dailycheckin Pypi 0.1.8 ~ 0.2.1 版本更新

⚠️⚠️重要
1. ⚠️优化配置文件 (https://sitoi.gitee.io/dailycheckin/settings/) 需要手动 复制输出的配置内容，更新到 config.json 文件中
2. ⚠️需要手动更新 pypi 包至 v0.2.1 ， 并运行一次签到，复制新版的配置 替换原有的配置文件，更新命令及详细配置信息移步 https://sitoi.gitee.io/dailycheckin
3. ⚠️由于任务名称改变，会导致原有的 include 或 exclude 会失效 请及时更新

更新步骤
1. 更新 pypi 到 0.2.0（如何更新看教程文档）
2. 手动执行一次签到
3. 复制新版的 config.json（打印输出 ------ 之间的内容） 替换原有的（也可以参考文档自己改），记得去 https://json.cn 校验一下
4. 替换完成后 再运行一次即可

新增
1. 添加【联通营业厅】脚本 
2. 添加【欢太商城】脚本

优化
1. 优化项目结构 
2. 优化日志输出

移除
1. 移除【每日天气】
2. 移除【每日一句】

**Comment by IrisLostName** [comment]
求救，请问要复制哪个？复制到哪里？
频台是腾讯云函数，log如下，求大神解答！

![image](https://user-images.githubusercontent.com/74960289/133974101-e5185516-433b-4f8b-b7b8-f4e35216b82d.png)

**Comment by Sitoi** [comment]
> 求救，请问要复制哪个？复制到哪里？
> 频台是腾讯云函数，log如下，求大神解答！
> 
> ![image](https://user-images.githubusercontent.com/74960289/133974101-e5185516-433b-4f8b-b7b8-f4e35216b82d.png)

再运行一次试试

**Comment by IrisLostName** [comment]
找到了，但日志显示不全 截至到b站的cookie后就没了
![image](https://user-images.githubusercontent.com/74960289/133975283-0c357d52-dfda-495e-8a23-d26ae91d346f.png)

**Comment by Sitoi** [comment]
你要么试试在运行一下，要么只能手动改了，看着文档重新配置

**Comment by tuoxiao** [comment]
不更新会不能用了吗，目前只用破站签到一个功能，还蛮好用的，不想再折腾了。

**Comment by Sitoi** [comment]
> 不更新会不能用了吗，目前只用破站签到一个功能，还蛮好用的，不想再折腾了。

云函数不更新 不影响

**Comment by wxchil** [comment]
"更新命令及详细配置信息移步 https://sitoi.gitee.io/dailycheckin"
可是并没有找到如何更新的教程呀......
