### ISSUE TITLE
申请增加中国移动 中国联通 签到功能

### ISSUE THREAD

**Issue by simple603888** [Sitoi/dailycheckin#351]
### 🥰 需求描述

申请增加中国移动 中国联通 签到功能。这些都是大家很常用的把！

### 🧐 解决方案

无

### 📝 补充信息

申请增加中国移动 中国联通 签到功能

**Comment by w32x42y** [comment]
附议

**Comment by xianrenqh** [comment]
附议

**Comment by nicknamexiaozui** [comment]
电信：俺也一样

**Comment by wings110** [comment]
希望添加 移动 联通自动签到等功能

**Comment by ZhengchaoCao** [comment]
附议：移动

**Comment by Sitoi** [comment]
归档到 projects 中 https://github.com/users/Sitoi/projects/1 关闭 issue
