### ISSUE TITLE
[Request] 请新增多看签到功能

### ISSUE THREAD

**Issue by vadonmo** [Sitoi/dailycheckin#353]
### 🥰 需求描述

希望新增多看阅读的签到

### 🧐 解决方案

https://github.com/ALXWJJ/duokan_checkin_and_get_limit_free_book
现有签到代码，部分数据格式需要调整

**Comment by Sitoi** [comment]
归档到 projects 中 https://github.com/users/Sitoi/projects/1 关闭 issue
