### ISSUE TITLE
## 开始执行... 2024-04-25 16:16:34  当前时间: 2024-04-25 16:16:35 当前版本: 24.3.19 未找到 config.json 配置文件 请在下方任意目录中添加「config.json」文件: /ql/scripts /ql/data/scripts /ql/data /ql/data/scripts/config /ql/data/config /  ## 执行结束... 2024-04-25 16:16:35  耗时 1 秒　　　　　[Bug] 

### ISSUE THREAD

**Issue by hhtnFxQVwQntBLkULKjy** [Sitoi/dailycheckin#354]
### 💻 系统环境

Windows

### 📦 部署环境

青龙

## 开始执行... 2024-04-25 16:16:34

当前时间: 2024-04-25 16:16:35
当前版本: 24.3.19
未找到 config.json 配置文件
请在下方任意目录中添加「config.json」文件:
/ql/scripts
/ql/data/scripts
/ql/data
/ql/data/scripts/config
/ql/data/config
/

## 开始执行... 2024-04-25 16:16:34

当前时间: 2024-04-25 16:16:35
当前版本: 24.3.19
未找到 config.json 配置文件
请在下方任意目录中添加「config.json」文件:
/ql/scripts
/ql/data/scripts
/ql/data
/ql/data/scripts/config
/ql/data/config
/

## 执行结束... 2024-04-25 16:16:35  耗时 1 秒　　　　　

咋搞，完全安装教程做的

**Comment by JokerIvanZK** [comment]
看下config.json的文件名是不是有空格 重命名试试
