### ISSUE TITLE
[Request] 添加参数 `dailycheckin --config [config.json路径]`

### ISSUE THREAD

**Issue by yzqdev** [Sitoi/dailycheckin#355]
### 🥰 需求描述

看了一下源码,是从这几个位置获取config.json的
https://github.com/Sitoi/dailycheckin/blob/46349fbe453a37d4c694d9f038b1350e168b78bf/dailycheckin/main.py#L24-L32

可以添加一个可选的`--config [config.json路径]`参数,如果参数存在,就优先使用参数的config.json路径

#349, #286

手动部署的时候可以直接指定config.json路径,避免部分命令比如crontab执行`dailycheckin`命令的pwd不对,导致程序找不到`config.json`

### 🧐 解决方案

https://github.com/Sitoi/dailycheckin/blob/46349fbe453a37d4c694d9f038b1350e168b78bf/dailycheckin/main.py#L15-L18

添加
```python
 parser.add_argument("--config", nargs="+", help="config.json绝对路径") 

```

**Comment by ximu-tao** [comment]
我也遇到了类似的问题，我目前的解决方法是在自己的脚本文件中import dailycheckin
像这样：
```
import os
import dailycheckin.main as dailycheckin
os.chdir("config.json所在的路径")
dailycheckin.checkin()
```

**Comment by Sitoi** [comment]
归档到 projects 中 https://github.com/users/Sitoi/projects/1 关闭 issue
