### ISSUE TITLE
[Bug] 青龙，版本：2.17.4 执行失败一片空白

### ISSUE THREAD

**Issue by hhtnFxQVwQntBLkULKjy** [Sitoi/dailycheckin#357]
### 💻 系统环境

Windows

### 📦 部署环境

青龙

### 🐛 问题描述

![屏幕截图 2024-04-28 111839](https://github.com/Sitoi/dailycheckin/assets/20140506/0f4249dd-0165-4502-89c4-73fc90be7a3c)
看图，操作都是一步步按照搭建教程来的。

### 📝 运行日志

没有日志

**Comment by lzhguan** [comment]
同样情况加1

**Comment by Sitoi** [comment]
没有日志，无法判断

**Comment by AlonWangg** [comment]
> 同样情况加1
