### ISSUE TITLE
[Bug] 阿里云盘签到异常

### ISSUE THREAD

**Issue by LQYHYQ** [Sitoi/dailycheckin#359]
### 💻 系统环境

Other Linux

### 📦 部署环境

Docker

### 🐛 问题描述

阿里云盘签到出现异常！

### 📝 运行日志

----------开始执行「阿里云盘」签到----------
签到成功
第 1 个账号: ❌❌❌❌❌
'NoneType' object is not iterable
签到成功
第 2 个账号: ❌❌❌❌❌
'NoneType' object is not iterable

**Comment by Fusuccess** [comment]
我也有遇到类似情况，我是使用IQIYI接口时，我的cookie值中包含双引号
> "cookie": "QC005=abcxxx; QC006=**"**xxxx**"** "
> 以至于导致json格式不正确，因此自己加了转义符 \
>> "cookie": "QC005=abcxxx; QC006=**\"**xxxx**\"** "
>> 加了转义符号后就会报'NoneType' object is not subscriptable
