### ISSUE TITLE
gcc g++ make libffi-dev openssl-dev安装失败

### ISSUE THREAD

**Issue by Testplayers** [Sitoi/dailycheckin#361]
### 💻 系统环境

Windows

### 📦 部署环境

本地

### 🐛 问题描述

gcc g++ make libffi-dev openssl-dev安装失败
Debian 12

### 📝 运行日志

开始安装依赖 gcc g++ make libffi-dev openssl-dev，开始时间 2024-05-07 09:37:49

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package openssl-dev

依赖安装失败，结束时间 2024-05-07 09:37:50，耗时 0 秒

**Comment by Fansirsqi** [comment]
`build-essential libssl-dev libffi-dev`这样试试

**Comment by Testplayers** [comment]
> `build-essential libssl-dev libffi-dev`这样试试

还是失败

**Comment by Fansirsqi** [comment]
> > `build-essential libssl-dev libffi-dev`这样试试
> 
> 还是失败

`sudo apt update -y && sudo apt install build-essential libssl-dev libffi-dev gcc g++ make -y`

**Comment by Fansirsqi** [comment]
> > `build-essential libssl-dev libffi-dev`这样试试
> 
> 还是失败

`sudo apt update -y && sudo apt install build-essential libssl-dev libffi-dev -y`

**Comment by Sitoi** [comment]
你直接 pip 安装 dailycheckin 看看行不行，行的话 不需要额外安装依赖了

**Comment by alienbigking** [comment]
是你青龙内部的镜像源URL有问题，进到容器里更新下就可以了
