### ISSUE TITLE
找不到文件[Bug] 

### ISSUE THREAD

**Issue by v125543215** [Sitoi/dailycheckin#363]
### 💻 系统环境

Other Linux

### 📦 部署环境

青龙

### 🐛 问题描述

日志显示
## 开始执行... 2024-05-10 20:39:05

/ql/shell/otask.sh: line 209: dailychecki: command not found

## 执行结束... 2024-05-10 20:39:06  耗时 1 秒
去脚本页面调试输出日志
## 开始执行... 2024-05-10 21:11:47

/ql/shell/otask.sh: line 209: ./config.swap.json: Permission denied

## 执行结束... 2024-05-10 21:11:47  耗时 1 秒
请问怎么处理  设备：玩客云 armbian  docker 青龙面板

**Comment by Sitoi** [comment]
单词都拼错了

**Comment by VvLin-61** [comment]
解决了吗？我也遇到这问题了
