### ISSUE TITLE
[Bug] 「爱奇艺」 用户账号: 未获取到，请检查 Cookie 中 P00002 字段 用户昵称: 未获取到，请检查 Cookie 中 P00002 字段

### ISSUE THREAD

**Issue by zhoudahong** [Sitoi/dailycheckin#368]
### 💻 系统环境

Windows

### 📦 部署环境

本地

### 🐛 问题描述

「爱奇艺」
用户账号: 未获取到，请检查 Cookie 中 P00002 字段
用户昵称: 未获取到，请检查 Cookie 中 P00002 字段
cookie是按教程复制的全部，P00002检查已经有了。烦请大神抽空看看

### 📝 运行日志

「爱奇艺」
用户账号: 未获取到，请检查 Cookie 中 P00002 字段
用户昵称: 未获取到，请检查 Cookie 中 P00002 字段
VIP 等级: 6
当前成长: 28154
今日成长: 4
升级还需: 646
VIP 到期: 2026-02-05
签到天数: 账号存在风险，请联系客服
任务奖励: +4成长值
抽奖奖励: 携程机票贵宾厅30元立减券;《守护者》;携程机票贵宾厅30元立减券;
视频时长: 已经刷了 7612秒, 数据同步有延迟, 仅供参考
每天摇一摇: 携程机票贵宾厅30元立减券、携程机票贵宾厅30元立减券、携程机票贵宾厅30元立减券
V7 免费升级星钻: 当前用户不在白名单中
白金抽奖: 白金VIP会员月卡5元代金券

**Comment by Sitoi** [comment]
报错没有 那就是没有
