### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by wdybb** [Sitoi/dailycheckin#369]
### 💻 系统环境

Other Linux

### 📦 部署环境

青龙

### 🐛 问题描述

请问一下青龙面板安装，遇到自动升级失败如何决解？
![b84547b924e8d88ac6eaa0d50250696](https://github.com/Sitoi/dailycheckin/assets/99387845/e03aae8e-1c73-478a-9d4d-53e2474e6b3e)

![image](https://github.com/Sitoi/dailycheckin/assets/99387845/ee1d5362-cba6-4c15-b166-d5b7575690a0)

### 📝 运行日志

Requirement already satisfied: dailycheckin in /usr/local/lib/python3.11/site-packages (24.5.15)
Requirement already satisfied: pycryptodome==3.17 in /usr/local/lib/python3.11/site-packages (from dailycheckin) (3.17)
Requirement already satisfied: requests~=2.25.1 in /usr/local/lib/python3.11/site-packages (from dailycheckin) (2.25.1)
Requirement already satisfied: rsa~=4.0 in /usr/local/lib/python3.11/site-packages (from dailycheckin) (4.9)
Requirement already satisfied: urllib3~=1.26.2 in /usr/local/lib/python3.11/site-packages (from dailycheckin) (1.26.18)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.11/site-packages (from requests~=2.25.1->dailycheckin) (4.0.0)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.11/site-packages (from requests~=2.25.1->dailycheckin) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/site-packages (from requests~=2.25.1->dailycheckin) (2024.2.2)
Requirement already satisfied: pyasn1>=0.1.3 in /usr/local/lib/python3.11/site-packages (from rsa~=4.0->dailycheckin) (0.6.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

## 执行结束... 2024-05-16 10:56:25  耗时 4 秒

**Comment by Sitoi** [comment]
哪里失败了？

**Comment by wdybb** [comment]
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead这句话是啥意思？

**Comment by simple603888** [comment]
命令改成 task pip3 install dailycheckin --upgrade --root-user-action=ignore
