### ISSUE TITLE
[Bug] 问下大家，爱奇艺账号存在风险，如何解决？

### ISSUE THREAD

**Issue by 722721** [Sitoi/dailycheckin#371]
### 💻 系统环境

Other Linux

### 📦 部署环境

青龙

### 🐛 问题描述

如题

**Comment by simple603888** [comment]
我也是。
![image](https://github.com/Sitoi/dailycheckin/assets/60378045/46de4dbf-633e-440a-a8ad-a34ffe41f72d)

**Comment by v125543215** [comment]
相同情况，是被官方黑号了吗？

**Comment by reverie1988** [comment]
更新24.5.15解决

pip install dailycheckin --user --upgrade

**Comment by simple603888** [comment]
> 更新24.5.15解决
> 
> pip install dailycheckin --user --upgrade

更新了。还是提示存在风险

**Comment by v125543215** [comment]
我更新后可以了

**Comment by simple603888** [comment]
> 我更新后可以了
我的是最新版本了呀
开始时间: 2024-05-21 09:00:00
任务用时: 50 秒
当前版本: 24.5.15
最新版本: 24.5.15

**Comment by v125543215** [comment]
> > 我更新后可以了
> > 我的是最新版本了呀
> > 开始时间: 2024-05-21 09:00:00
> > 任务用时: 50 秒
> > 当前版本: 24.5.15
> > 最新版本: 24.5.15


新建定时任务 pip install dailycheckin --user --upgrade 运行之后我就可以了

**Comment by reverie1988** [comment]
更新后可以签到，但是你们有没有发现签到的是积分没有的，还是有点问题

**Comment by qq4878168** [comment]
> 更新后可以签到，但是你们有没有发现签到的是积分没有的，还是有点问题

网页端抓的CK签到成功， 实际无成长值到账。现在抓了APP的CK签到成功，有成长值到账

**Comment by Sitoi** [comment]
更新最新版本，重新抓cookie 试试，web 端和 ios 端都可以尝试下
