### ISSUE TITLE
有道云签到[Bug] 

### ISSUE THREAD

**Issue by v125543215** [Sitoi/dailycheckin#372]
### 💻 系统环境

Other Linux

### 📦 部署环境

青龙

### 🐛 问题描述

获取账号信息失败，重新填写cook还是没能解决

## 开始执行... 2024-05-17 12:15:49

当前时间: 2024-05-17 12:15:51
当前版本: 24.5.15
使用配置文件路径: /ql/data/scripts/config.json

---------- 本次执行签到任务如下 ----------

「有道云笔记」账号数 : 1

----------开始执行「有道云笔记」签到----------
获取账号信息失败: list index out of range
第 1 个账号: ✅✅✅✅✅

Pushplus 推送开始
Pushplus 推送开始

## 执行结束... 2024-05-17 12:15:55  耗时 6 秒

**Comment by Sitoi** [comment]
cookie 有问题
