### ISSUE TITLE
[Bug] 爱奇艺签到成功但无成长值到账

### ISSUE THREAD

**Issue by qq4878168** [Sitoi/dailycheckin#373]
### 💻 系统环境

Other Linux

### 📦 部署环境

青龙

### 🐛 问题描述

脚本显示签到成功，且APP查看签到状态显示当天已签到，但查看成长值明细中，并没有签到的成长值到账

**Comment by qq4878168** [comment]
同时测试其他账号，提示风险，无法签到，已是最新版脚本

**Comment by Sitoi** [comment]
更新 cookie 试试

**Comment by qq4878168** [comment]
> 更新 cookie 试试

网页端抓的CK签到成功， 实际无成长值到账。现在抓了APP的CK签到成功，有成长值到账
