### ISSUE TITLE
[Bug] 爱奇艺刷时长的请求抛出异常

### ISSUE THREAD

**Issue by bpguide** [Sitoi/dailycheckin#374]
### 💻 系统环境

Other Linux

### 📦 部署环境

青龙

### 🐛 问题描述

刷时长的时候抛出了异常，链接放到浏览器里打开能成功，在python环境里抛异常，只有我一个人碰到这个问题了吗？

### 📝 运行日志

requests.exceptions.ConnectionError: HTTPSConnectionPool(host='msg.qy.net', port=443): Max retries exceeded with url: ……(Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001851DEF92A0>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed'))

**Comment by Sitoi** [comment]
是不是你的规则把这个地址给办了

**Comment by bpguide** [comment]
> 是不是你的规则把这个地址给办了

你说得对，已经解决了，3q
