### ISSUE TITLE
[Bug] NoneType' object is not iterable

### ISSUE THREAD

**Issue by mcxiaochenn** [Sitoi/dailycheckin#375]
### 💻 系统环境

Ubuntu

### 📦 部署环境

青龙

### 🐛 问题描述

通知输出偶现标题问题

### 📝 运行日志

钉钉输出
`「Bilibili」
'NoneType' object is not iterable
————————————

「Bilibili」
'NoneType' object is not iterable
————————————

开始时间: 2024-05-19 08:45:01
任务用时: 12 秒
当前版本: 24.5.15
最新版本: 24.5.15
项目地址: https://github.com/Sitoi/dailycheckin`
有时候可以正常输出，有时候不行，日志一切正常，很奇怪

**Comment by v125543215** [comment]
我的也是相同情况，docker 青龙面板  bilibili 日志打印只有 None

**Comment by Sitoi** [comment]
### 选择 Fetch/XHR 标签

### 选中 https://api.bilibili.com/x/space/user/setting/list
换这个 cookie 试试
