### ISSUE TITLE
[Request] 申请增加云函数部署方式

### ISSUE THREAD

**Issue by qq4878168** [Sitoi/dailycheckin#376]
### 🥰 需求描述

申请增加云函数部署方式，云函数免费且无需占用设备资源，可以让吾等无专用青龙或群辉的网友也可以玩转签到，十分感谢

### 🧐 解决方案

增加阿里云函数部署签到脚本功能

**Comment by Sitoi** [comment]
阿里云函数收费了，不考虑了，之前的教程应该有，还是一样的

**Comment by Sitoi** [comment]
https://github.com/Sitoi/dailycheckin/blob/2900d1a462114bab2aa496cc452be9d97e2b3308/docs/tencent-scf.md
可以参考腾讯云的
