### ISSUE TITLE
AliyunPan-签到领奖励失败

### ISSUE THREAD

**Issue by jingc1413** [Sitoi/dailycheckin#377]
### 💻 系统环境

Ubuntu

### 📦 部署环境

本地

### 🐛 问题描述

阿里云盘新增了请求头的验签操作
{"code":"Forbidden","message":"请升级最新客户端访问","requestId":"1daaaaa9d-3a15-44b1-8d0f-bbbbbbbb"}

**Comment by Sitoi** [comment]
阿里云没啥羊毛了，不想维护了
