### ISSUE TITLE
IMAOTAI签到bug

### ISSUE THREAD

**Issue by xy-zi** [Sitoi/dailycheckin#378]
### 💻 系统环境

Other Linux

### 📦 部署环境

Docker

### 🐛 问题描述

提示[ianus-token-auth] token expired
![Screenshot_2024-05-23-13-09-40-356_com ftqq sct mobile serverapp](https://github.com/Sitoi/dailycheckin/assets/154971240/9c1c8d54-257e-4d60-aa98-ffd30fdd7fb1)

### 📝 运行日志

----------开始执行「i茅台」签到----------
第 1 个账号: ✅ ✅ ✅ ✅ ✅
第 2 个账号: ✅ ✅ ✅ ✅ ✅
第 3 个账号: ✅ ✅ ✅ ✅ ✅
第 4 个账号: ✅ ✅ ✅ ✅ ✅

**Comment by LQYHYQ** [comment]
重新获取token试下

**Comment by daqiaowijiu** [comment]
token过期了老铁
