### ISSUE TITLE
爱奇艺签到失败[Bug] 

### ISSUE THREAD

**Issue by lzhguan** [Sitoi/dailycheckin#379]
### 💻 系统环境

Ubuntu

### 📦 部署环境

青龙

### 🐛 问题描述

日志显示成功，但实际没有签到，还是需要手动到app里签到

## 开始执行... 2024-05-24 07:20:00

当前时间: 2024-05-24 07:20:01
当前版本: 24.5.15
使用配置文件路径: /ql/data/scripts/config.json

---------- 本次执行签到任务如下 ----------

「爱奇艺」账号数 : 1

----------开始执行「爱奇艺」签到----------
{'code': 'A00000', 'msg': '成功', 'data': None}
{'code': 'A00000', 'msg': '成功', 'data': None}
{'code': 'A00000', 'msg': '成功', 'data': None}
现在已经刷到了 0秒, 数据同步有延迟, 仅供参考
现在已经刷到了 97秒, 数据同步有延迟, 仅供参考
...........
现在已经刷到了 7639秒, 数据同步有延迟, 仅供参考
第 1 个账号: ✅✅✅✅✅

## 执行结束... 2024-05-24 07:20:39  耗时 39 秒

**Comment by qq4878168** [comment]
更换CK试试

**Comment by lzhguan** [comment]
换了四五个ck终于好使了！
