### ISSUE TITLE
[Bug] 恩山无线论坛签到失败：list index out of range

### ISSUE THREAD

**Issue by LQYHYQ** [Sitoi/dailycheckin#380]
### 💻 系统环境

Other Linux

### 📦 部署环境

Docker

### 🐛 问题描述

恩山无线论坛签到异常，
![image](https://github.com/Sitoi/dailycheckin/assets/38932132/9daeb3d5-2d00-4f19-8cb5-097b231719e3)

**Comment by AmazingYHT** [comment]
我也遇到一样的。青龙面板的confg里面增加了恩山的信息，签到失败。
![image](https://github.com/Sitoi/dailycheckin/assets/25163453/1da5df9b-82fa-4570-8672-67c3e57974cd)

**Comment by argajeng** [comment]
检查下你们的json

**Comment by LQYHYQ** [comment]
> 检查下你们的json

不是json的问题，偶发性异常，这个信息一看就是签到失败返回解析异常的问题
