### ISSUE TITLE
[Bug] 阿里云盘/i茅台签到失败

### ISSUE THREAD

**Issue by Psilocine** [Sitoi/dailycheckin#385]
### 💻 系统环境

Ubuntu

### 📦 部署环境

Docker

### 🐛 问题描述

日志无异常显示，且更换token前后，都是☑️的，没有报错，🥺🙏

### 📝 运行日志

![image](https://github.com/Sitoi/dailycheckin/assets/25545052/922339c9-2ff2-45ba-95e9-68ef899243ae)

**Comment by Psilocine** [comment]
i茅台换了token好像可以了，但是云盘签到成功但实际没有成功

**Comment by mengfs2980** [comment]
阿里云盘 好像一直都在换token  不知道怎么弄了  是不是失效了


| |
孟凡松
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年6月3日 14:20 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> |
| 主题 | Re: [Sitoi/dailycheckin] [Bug] 阿里云盘/i茅台签到失败 (Issue #385) |

i茅台换了token好像可以了，但是云盘签到成功但实际没有成功

**Comment by ivangreat** [comment]
> i茅台换了token好像可以了，但是云盘签到成功但实际没有成功

怎么换token，我也是显示成功但实际没有预约

**Comment by mengfs2980** [comment]
https://sitoi.github.io/dailycheckin/settings/imaotai/
有教程啊




| |
孟凡松
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | Ivan ***@***.***> |
| 发送日期 | 2024年6月5日 16:01 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***>,
***@***.***> |
| 主题 | Re: [Sitoi/dailycheckin] [Bug] 阿里云盘/i茅台签到失败 (Issue #385) |

i茅台换了token好像可以了，但是云盘签到成功但实际没有成功

怎么换token，我也是显示成功但实际没有预约

**Comment by javading** [comment]
docker 启动任务之后修改cron任务未生效，logs下面也没有日志文件，有人遇到过没

**Comment by sweetspace2024** [comment]
i茅台只能早上9点到10点之间申请，要符合这个时间要求的吧
