### ISSUE TITLE
[Request] 请求增加云函数

### ISSUE THREAD

**Issue by qq4878168** [Sitoi/dailycheckin#386]
### 🥰 需求描述

经测试，只启用爱奇艺签到的情况下，一个月的云函数费用仅需1分钱左右，正常人完全足以负担，请求恢复云函数的维护。目前使用云函数拉仓库的依赖只更新到二月份，希望恢复继续使用

### 🧐 解决方案

请求恢复云函数的维护

**Comment by Sitoi** [comment]
https://github.com/Sitoi/dailycheckin/issues/376
