### ISSUE TITLE
定时运行找不到dailycheckin

### ISSUE THREAD

**Issue by TopAceW** [Sitoi/dailycheckin#388]
### 💻 系统环境

Windows

### 📦 部署环境

青龙

### 🐛 问题描述

按照教程在青龙里添加安装了dailycheckin，但是定时任务运行task dailycheckin时失败，日志见图
![屏幕截图 2024-06-08 142817](https://github.com/Sitoi/dailycheckin/assets/172101842/7ff8f63a-23ae-4187-9559-1dc8f302294c)

**Comment by argajeng** [comment]
依赖装了吗？
