### ISSUE TITLE
[Bug] 为什么用默认的config.json 都报错

### ISSUE THREAD

**Issue by charliesxia** [Sitoi/dailycheckin#389]
### 💻 系统环境

Windows

### 📦 部署环境

本地

### 🐛 问题描述
手动部署，
直接用的默认，没改一个字，运行以后，报错，Json 格式错误，请检查 config.json 文件格式是否正确！
添加cookie 后也一样报错

### 📝 运行日志

Json 格式错误，请检查 config.json 文件格式是否正确！

**Comment by charliesxia** [comment]
同样的文件，在linux 环境下运行成功了。好奇怪。

**Comment by Sitoi** [comment]
windows 编码格式问题吧

**Comment by JokerIvanZK** [comment]
json格式错误可以复制内容到www.json.cn检查看下
路径错误看下config.json的文件名是不是有空格 重命名试试
