### ISSUE TITLE
i茅台签到失败[Bug] 

### ISSUE THREAD

**Issue by rqqian** [Sitoi/dailycheckin#391]
### 💻 系统环境

Other Linux

### 📦 部署环境

Docker

### 🐛 问题描述

显示签到成功，实际并未预约申购。
![imaotai](https://github.com/Sitoi/dailycheckin/assets/20737891/0372fd7e-d62f-4e1c-980d-894cee597d0e)

**Comment by Sitoi** [comment]
看你申购记录里
