### ISSUE TITLE
[Bug] 爱奇艺签到失败

### ISSUE THREAD

**Issue by LisonFan** [Sitoi/dailycheckin#394]
### 💻 系统环境

Other Linux

### 📦 部署环境

青龙

### 🐛 问题描述

![image](https://github.com/Sitoi/dailycheckin/assets/9424775/bb4ae870-0b24-423e-882e-94d3231776e6)

**Comment by yexian-cn** [comment]
+1，账号存在风险，请联系客服；前天开始的，CK换过也没有用。
当前版本: 24.5.15

**Comment by Sitoi** [comment]
因人而异吧，试试手机端的cookie

**Comment by yexian-cn** [comment]
手机端抓取cookie后能成功签到。
