### ISSUE TITLE
吾爱破解无法签到

### ISSUE THREAD

**Issue by 523295116** [Sitoi/dailycheckin#4]
## 1.关于你要提交的问题

Q：是否搜索了 issue（包括已关闭的issue）

- [x] 没有类似的 issue 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装 Python
- [ ] 方法二：Docker
- [ ] 方法三：腾讯云函数
- [x] 方法四：GitHub Actions

### (1) 具体问题

A：吾爱破解无法签到，企鹅读书运行都没有问题，就是无法自动阅读，增长阅读时长，

### (2) 详细日志

A：
【吾爱破解签到】
帐号信息: 653068
签到状态: 未知错误，检查日志
-----------------------------
企鹅读书代码里除了xxxx的需要改，那些淡蓝色的数字需要修改嘛。

**Comment by 523295116** [comment]
图中的那些数字需要修改嘛。 还有每日签到早上8点多的时候没有自动运行，设置了钉钉推送也没收到。
![QQ图片20201223145429](https://user-images.githubusercontent.com/32154527/102968600-2024e380-452f-11eb-90d7-65e93674bcf8.png)

**Comment by Sitoi** [comment]
> 图中的那些数字需要修改嘛。 还有每日签到早上8点多的时候没有自动运行，设置了钉钉推送也没收到。
> ![QQ图片20201223145429](https://user-images.githubusercontent.com/32154527/102968600-2024e380-452f-11eb-90d7-65e93674bcf8.png)

吾爱破解有点问题，有空修复吧

企鹅的需要都替换掉，我写的都是假的，根据你自己的来，一个是三个大的值。需要 app 抓包获取

**Comment by 523295116** [comment]
> > 还有每日签到早上8点多的时候没有自动运行，设置了钉钉推动也没收到。
> > ![QQ图片20201223145429](https://user-images.githubusercontent.com/32154527/102968600-2024e380-452f-11eb-90d7-65e93674bcf8.png)
> 
> 吾爱破解有点问题，有空修复吧
> 
> 企鹅的需要都替换掉，我写的都是假的，根据你自己的来，一共是三个大的值。需要app抓包获取

每日签到怎么没有定时运行，抓包都没问题，就是改的时候经常改错 - -

**Comment by Sitoi** [comment]
每日签到是每天早上8:45运行一次
