### ISSUE TITLE
TX云函数

### ISSUE THREAD

**Issue by wuge0** [Sitoi/dailycheckin#4]
云函数配置文件里怎么写
有没有例子

MIMOTION_ACCOUNT_LIST.mimotion_phone 123
MIMOTION_ACCOUNT_LIST.mimotion_phone = 123
MIMOTION_ACCOUNT_LIST.mimotion_phone = "123",

该怎么写

**Comment by tnc817** [comment]
docs文件夹里有

**Comment by wuge0** [comment]
> 文档文件夹里有

没有啊
