### ISSUE TITLE
请问小米运动的value怎么写

### ISSUE THREAD

**Issue by shemc** [Sitoi/dailycheckin#40]
## 期望增加的功能

A：看了GitHub Actions 使用教程 小米运动的value是按什么顺序写的？mimotion_phone ，mimotion_password，mimotion_min_step，mimotion_max_step这样写吗
--

**Comment by Sitoi** [comment]
看文档

**Comment by shemc** [comment]
> 看文档

[
    {
      "mimotion_phone": "17*****678",
      "mimotion_password": "w*****w",
      "mimotion_min_step": "20001",
      "mimotion_max_step": "24999"
    }
]

看文档后按照这样的格式写的，对吗？
用AC运行了几次，步数没变化呀

**Comment by Sitoi** [comment]
小米运动 app 是不会变化的，绑定的支付宝会变化
