### ISSUE TITLE
爱奇艺签到报错[Bug] 

### ISSUE THREAD

**Issue by mingrenmm** [Sitoi/dailycheckin#400]
### 💻 系统环境

Windows

### 📦 部署环境

青龙

### 🐛 问题描述

爱奇艺签到失败，重试过抓取CK，依然如此

### 📝 运行日志

----------开始执行「爱奇艺」签到----------
{'code': 'Q00393', 'msg': '超过次数赠送限额', 'data': None}
{'code': 'Q00393', 'msg': '超过次数赠送限额', 'data': None}
{'code': 'Q00393', 'msg': '超过次数赠送限额', 'data': None}
现在已经刷到了 0秒, 数据同步有延迟, 仅供参考
第 1 个账号: ❌❌❌❌❌
HTTPSConnectionPool(host='msg.qy.net', port=443): Max retries exceeded with url: /b?u=f600a23f03c26507f5482e6828cfc6c5&pu=1593061667&p1=1_10_101&v=5.2.66&ce=b2f9df8b83aa41f3addc2c8814150e73&de=1616773143.1639632721.1639653680.29&c1=2&ve=3e1798eba7674a13a844907e1b583b39&ht=0&pt=3348.501989&isdm=0&duby=0&ra=5&clt=&ps2=DIRECT&ps3=&ps4=&br=mozilla%2F5.0+%28windows+nt+10.0%3B+win64%3B+x64%29+applewebkit%2F537.36+%28khtml%2C+like+gecko%29+chrome%2F96.0.4664.110+safari%2F537.36&mod=cn_s&purl=https%3A%2F%2Fwww.iqiyi.com%2Fv_1eldg8u3r08.html%3Fvfrm%3Dpcw_home%26vfrmblk%3D712211_cainizaizhui%26vfrmrst%3D712211_cainizaizhui_image1%26r_area%3Drec_you_like%26r_source%3D62%2540128%26bkt%3DMBA_PW_T3_53%26e%3Db3ec4e6c74812510c7719f7ecc8fbb0f%26stype%3D2&tmplt=2&ptid=01010031010000000000&os=window&nu=0&vfm=&coop=&ispre=0&videotp=0&drm=&plyrv=&rfr=https%3A%2F%2Fwww.iqiyi.com%2F&fatherid=1043324375647345&stauto=1&algot=abr_v12-rl&vvfrom=&vfrmtp=1&pagev=playpage_adv_xb&engt=2&ldt=1&krv=1.1.85&wtmk=0&duration=6841865&bkt=&e=&stype=&r_area=&r_source=&s4=991811_dianshiju_tbrb_image2&abtest=1707_B%2C1550_B&s3=677892_dianshiju_tbrb&vbr=966873&mft=0&ra1=2&wint=3&s2=pcw_home&bw=10&ntwk=18&dl=15.27999999999997&rn=0.2847593695945669&dfp=&stime=1719197520355.854&r=1287194776986998&hu=1&t=2&tm=79&_=1719197520355.865 (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1007)')))

**Comment by Sitoi** [comment]
你自己网络问题

**Comment by mingrenmm** [comment]
> 你自己网络问题

其他的签到都成功了呀

**Comment by AkenClub** [comment]
> > 你自己网络问题
> 
> 其他的签到都成功了呀

的确是网络原因，可能是你用了代理，拦截了签到用的域名，我也碰到了这个问题，添加白名单后就没问题了，可参考
![image](https://github.com/user-attachments/assets/ca0b0754-c184-467a-98a3-5a57d1392c77)
