### ISSUE TITLE
i茅台每天六点后检查是否中签功能比较有用

### ISSUE THREAD

**Issue by 245427794** [Sitoi/dailycheckin#406]
### 🥰 需求描述

方便的话能否在原有基础上新增一个检测是否中签功能然后push通知的吗

### 🧐 解决方案

运行原有脚本的时候，判断一下运行时间是否在六点后，如果是的就检测一下每个账号是否中签并发送push通知

**Comment by mengfs2980** [comment]
i茅台有短信提醒的  你不会没中过吧






| |
孟凡松
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年7月3日 14:30 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> |
| 主题 | [Sitoi/dailycheckin] i茅台每天六点后检查是否中签功能比较有用 (Issue #406) |
🥰 需求描述

方便的话能否在原有基础上新增一个检测是否中签功能然后push通知的吗

🧐 解决方案

运行原有脚本的时候，判断一下运行时间是否在六点后，如果是的就检测一下每个账号是否中签并发送push通知

📝 补充信息

No response

**Comment by 245427794** [comment]
当用父母的号去申购时，短信是发到他们手机号上面的，无法即时查看得知的

**Comment by crane168** [comment]
> 当用父母的号去申购时，短信是发到他们手机号上面的，无法即时查看得知的

是有这个需求，多账号非常需要，不然不知道是哪个账号的
