### ISSUE TITLE
[Bug] 定时任务运行成功了，实际没有签到成功

### ISSUE THREAD

**Issue by CaoJ20132014** [Sitoi/dailycheckin#407]
### 💻 系统环境

绿联dx4600

### 📦 部署环境

青龙

### 🐛 问题描述

定时任务运行成功了，实际没有签到成功

**Comment by ywk1000** [comment]
DailyCheckin 还有一种方法可以跑， 把整个 项目文档拉到 ql/data/script 目录下， 然后在 DailyCheckin 目录下安装 [DailyCheckin.py](https://dailycheckin.py/) 依赖， 最后再 task dailycheckin   就能跑了
