### ISSUE TITLE
[Request] 爱奇艺签到脚本 有一个执行 超过次数赠送限额 是什么任务的

### ISSUE THREAD

**Issue by McdullD** [Sitoi/dailycheckin#408]
### 🥰 需求描述

{'code': 'Q00393', 'msg': '超过次数赠送限额', 'data': None}
{'code': 'Q00393', 'msg': '超过次数赠送限额', 'data': None}
{'code': 'Q00393', 'msg': '超过次数赠送限额', 'data': None}

### 🧐 解决方案

爱奇艺签到脚本 那个任务会这个提示错误

**Comment by Sitoi** [comment]
抽白金会员 5 次的活动
