### ISSUE TITLE
签到执行时间错误

### ISSUE THREAD

**Issue by rabbit-cat** [Sitoi/dailycheckin#41]
## 1.关于你要提交的问题

Q：是否搜索了 issue（包括已关闭的issue）

- [x] 没有类似的 issue 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装 Python
- [ ] 方法二：Docker
- [ ] 方法三：腾讯云函数
- [x] 方法四：GitHub Actions

### (1) 具体问题

A：签到的时间总是在每天的17:30分左右，但是程序我看了是设定的8:45，而且我自行修改运行时间不生效，不知道哪里出错了

相关代码正确

name: 每日签到合集

on:
  schedule:
    - cron: '45 8 * * * '

### (2) 详细日志

A：

**Comment by Sitoi** [comment]
因为有个同步仓库的 action，会自动同步仓库，导致被修改的时间又会变会默认。建议 disable 同步仓库 action
