### ISSUE TITLE
[Request] 更新dailycheckin问题

### ISSUE THREAD

**Issue by TopAceW** [Sitoi/dailycheckin#416]
### 🥰 需求描述

按照教程设置了青龙面板下python依赖，看了下日志，dailycheckin版本是24.2.27，又按照教程设置了定时任务更新dailycheckin，无论是手动还是自动更新，都不起任何作用，这是怎么回事

### 🧐 解决方案

解决定时更新dailycheckin版本问题

### 📝 补充信息

![image](https://github.com/user-attachments/assets/269f5f84-3f19-47e6-abd4-ef8ddd826087)
![image](https://github.com/user-attachments/assets/842a80d9-a417-4bd0-8c52-4e64e740dced)
![image](https://github.com/user-attachments/assets/aa087ef3-822e-4860-b182-4c85d0abffa0)

**Comment by Sitoi** [comment]
python 版本换成3.9以上，你现在是3.8
