### ISSUE TITLE
[Bug] 爱奇艺日常任务观看视频30分钟无法完成

### ISSUE THREAD

**Issue by LisonFan** [Sitoi/dailycheckin#418]
### 💻 系统环境

Other Linux

### 📦 部署环境

Docker

### 🐛 问题描述

![E97FBB75-0FE1-4B9C-B0F3-8F35D783947C](https://github.com/user-attachments/assets/eda74f9f-3031-4de3-93e8-57c47c9b3405)

### 📝 运行日志

```
----------开始执行「爱奇艺」签到----------
{'code': 'A00000', 'msg': '成功', 'data': None}
{'code': 'A00000', 'msg': '成功', 'data': None}
{'code': 'A00000', 'msg': '成功', 'data': None}
现在已经刷到了 0秒, 数据同步有延迟, 仅供参考
现在已经刷到了 66秒, 数据同步有延迟, 仅供参考
现在已经刷到了 169秒, 数据同步有延迟, 仅供参考
现在已经刷到了 271秒, 数据同步有延迟, 仅供参考
现在已经刷到了 339秒, 数据同步有延迟, 仅供参考
现在已经刷到了 438秒, 数据同步有延迟, 仅供参考
现在已经刷到了 529秒, 数据同步有延迟, 仅供参考
现在已经刷到了 622秒, 数据同步有延迟, 仅供参考
现在已经刷到了 707秒, 数据同步有延迟, 仅供参考
现在已经刷到了 825秒, 数据同步有延迟, 仅供参考
现在已经刷到了 935秒, 数据同步有延迟, 仅供参考
现在已经刷到了 1008秒, 数据同步有延迟, 仅供参考
现在已经刷到了 1068秒, 数据同步有延迟, 仅供参考
现在已经刷到了 1171秒, 数据同步有延迟, 仅供参考
现在已经刷到了 1248秒, 数据同步有延迟, 仅供参考
现在已经刷到了 1315秒, 数据同步有延迟, 仅供参考
现在已经刷到了 1426秒, 数据同步有延迟, 仅供参考
现在已经刷到了 1515秒, 数据同步有延迟, 仅供参考
现在已经刷到了 1628秒, 数据同步有延迟, 仅供参考
现在已经刷到了 1714秒, 数据同步有延迟, 仅供参考
现在已经刷到了 1775秒, 数据同步有延迟, 仅供参考
现在已经刷到了 1851秒, 数据同步有延迟, 仅供参考
现在已经刷到了 1935秒, 数据同步有延迟, 仅供参考
现在已经刷到了 2005秒, 数据同步有延迟, 仅供参考
现在已经刷到了 2124秒, 数据同步有延迟, 仅供参考
现在已经刷到了 2213秒, 数据同步有延迟, 仅供参考
现在已经刷到了 2325秒, 数据同步有延迟, 仅供参考
现在已经刷到了 2407秒, 数据同步有延迟, 仅供参考
现在已经刷到了 2474秒, 数据同步有延迟, 仅供参考
现在已经刷到了 2583秒, 数据同步有延迟, 仅供参考
现在已经刷到了 2677秒, 数据同步有延迟, 仅供参考
现在已经刷到了 2752秒, 数据同步有延迟, 仅供参考
现在已经刷到了 2872秒, 数据同步有延迟, 仅供参考
现在已经刷到了 2948秒, 数据同步有延迟, 仅供参考
现在已经刷到了 3057秒, 数据同步有延迟, 仅供参考
现在已经刷到了 3121秒, 数据同步有延迟, 仅供参考
现在已经刷到了 3215秒, 数据同步有延迟, 仅供参考
现在已经刷到了 3302秒, 数据同步有延迟, 仅供参考
现在已经刷到了 3370秒, 数据同步有延迟, 仅供参考
现在已经刷到了 3446秒, 数据同步有延迟, 仅供参考
现在已经刷到了 3537秒, 数据同步有延迟, 仅供参考
现在已经刷到了 3620秒, 数据同步有延迟, 仅供参考
现在已经刷到了 3690秒, 数据同步有延迟, 仅供参考
现在已经刷到了 3762秒, 数据同步有延迟, 仅供参考
现在已经刷到了 3860秒, 数据同步有延迟, 仅供参考
现在已经刷到了 3925秒, 数据同步有延迟, 仅供参考
现在已经刷到了 4004秒, 数据同步有延迟, 仅供参考
现在已经刷到了 4069秒, 数据同步有延迟, 仅供参考
现在已经刷到了 4133秒, 数据同步有延迟, 仅供参考
现在已经刷到了 4244秒, 数据同步有延迟, 仅供参考
现在已经刷到了 4342秒, 数据同步有延迟, 仅供参考
现在已经刷到了 4422秒, 数据同步有延迟, 仅供参考
现在已经刷到了 4527秒, 数据同步有延迟, 仅供参考
现在已经刷到了 4623秒, 数据同步有延迟, 仅供参考
现在已经刷到了 4716秒, 数据同步有延迟, 仅供参考
现在已经刷到了 4829秒, 数据同步有延迟, 仅供参考
现在已经刷到了 4920秒, 数据同步有延迟, 仅供参考
现在已经刷到了 4980秒, 数据同步有延迟, 仅供参考
现在已经刷到了 5097秒, 数据同步有延迟, 仅供参考
现在已经刷到了 5171秒, 数据同步有延迟, 仅供参考
现在已经刷到了 5276秒, 数据同步有延迟, 仅供参考
现在已经刷到了 5338秒, 数据同步有延迟, 仅供参考
现在已经刷到了 5410秒, 数据同步有延迟, 仅供参考
现在已经刷到了 5523秒, 数据同步有延迟, 仅供参考
现在已经刷到了 5624秒, 数据同步有延迟, 仅供参考
现在已经刷到了 5700秒, 数据同步有延迟, 仅供参考
现在已经刷到了 5767秒, 数据同步有延迟, 仅供参考
现在已经刷到了 5844秒, 数据同步有延迟, 仅供参考
现在已经刷到了 5904秒, 数据同步有延迟, 仅供参考
现在已经刷到了 5999秒, 数据同步有延迟, 仅供参考
现在已经刷到了 6061秒, 数据同步有延迟, 仅供参考
现在已经刷到了 6124秒, 数据同步有延迟, 仅供参考
现在已经刷到了 6225秒, 数据同步有延迟, 仅供参考
现在已经刷到了 6328秒, 数据同步有延迟, 仅供参考
现在已经刷到了 6435秒, 数据同步有延迟, 仅供参考
现在已经刷到了 6512秒, 数据同步有延迟, 仅供参考
现在已经刷到了 6623秒, 数据同步有延迟, 仅供参考
现在已经刷到了 6684秒, 数据同步有延迟, 仅供参考
现在已经刷到了 6780秒, 数据同步有延迟, 仅供参考
现在已经刷到了 6869秒, 数据同步有延迟, 仅供参考
现在已经刷到了 6962秒, 数据同步有延迟, 仅供参考
现在已经刷到了 7027秒, 数据同步有延迟, 仅供参考
现在已经刷到了 7133秒, 数据同步有延迟, 仅供参考
现在已经刷到了 7252秒, 数据同步有延迟, 仅供参考
现在已经刷到了 7354秒, 数据同步有延迟, 仅供参考
现在已经刷到了 7450秒, 数据同步有延迟, 仅供参考
现在已经刷到了 7511秒, 数据同步有延迟, 仅供参考
现在已经刷到了 7607秒, 数据同步有延迟, 仅供参考
第 1 个账号: ✅✅✅✅✅
```

**Comment by corsgoo** [comment]
> ### 💻 系统环境
> 
> Other Linux
> 
> ### 📦 部署环境
> 
> Docker
> 
> ### 🐛 问题描述
> 
> ![E97FBB75-0FE1-4B9C-B0F3-8F35D783947C](https://github.com/user-attachments/assets/eda74f9f-3031-4de3-93e8-57c47c9b3405)
> 
> 
> ### 📝 运行日志
> 
> ```
> ----------开始执行「爱奇艺」签到----------
> {'code': 'A00000', 'msg': '成功', 'data': None}
> {'code': 'A00000', 'msg': '成功', 'data': None}
> {'code': 'A00000', 'msg': '成功', 'data': None}
> 现在已经刷到了 0秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 66秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 169秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 271秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 339秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 438秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 529秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 622秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 707秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 825秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 935秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 1008秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 1068秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 1171秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 1248秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 1315秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 1426秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 1515秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 1628秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 1714秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 1775秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 1851秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 1935秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 2005秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 2124秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 2213秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 2325秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 2407秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 2474秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 2583秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 2677秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 2752秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 2872秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 2948秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 3057秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 3121秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 3215秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 3302秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 3370秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 3446秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 3537秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 3620秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 3690秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 3762秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 3860秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 3925秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 4004秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 4069秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 4133秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 4244秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 4342秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 4422秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 4527秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 4623秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 4716秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 4829秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 4920秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 4980秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 5097秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 5171秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 5276秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 5338秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 5410秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 5523秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 5624秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 5700秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 5767秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 5844秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 5904秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 5999秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 6061秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 6124秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 6225秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 6328秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 6435秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 6512秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 6623秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 6684秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 6780秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 6869秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 6962秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 7027秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 7133秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 7252秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 7354秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 7450秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 7511秒, 数据同步有延迟, 仅供参考
> 现在已经刷到了 7607秒, 数据同步有延迟, 仅供参考
> 第 1 个账号: ✅✅✅✅✅
> ```

我也是才发现从22号开始 ，出现了两个问题 ，第一个是刷这个视频的时间没有成长值了 我去APP看也显示0分钟 。其次是会报错，Connection reset by peer或者其他的报错 。

**Comment by 1934103887** [comment]
现在已经刷到了 4557秒, 数据同步有延迟, 仅供参考
现在已经刷到了 4641秒, 数据同步有延迟, 仅供参考
现在已经刷到了 4710秒, 数据同步有延迟, 仅供参考
现在已经刷到了 4820秒, 数据同步有延迟, 仅供参考
现在已经刷到了 4899秒, 数据同步有延迟, 仅供参考
现在已经刷到了 5003秒, 数据同步有延迟, 仅供参考
现在已经刷到了 5101秒, 数据同步有延迟, 仅供参考
现在已经刷到了 5209秒, 数据同步有延迟, 仅供参考
现在已经刷到了 5316秒, 数据同步有延迟, 仅供参考
现在已经刷到了 5380秒, 数据同步有延迟, 仅供参考
现在已经刷到了 5477秒, 数据同步有延迟, 仅供参考
现在已经刷到了 5543秒, 数据同步有延迟, 仅供参考
现在已经刷到了 5647秒, 数据同步有延迟, 仅供参考
现在已经刷到了 5755秒, 数据同步有延迟, 仅供参考
现在已经刷到了 5862秒, 数据同步有延迟, 仅供参考
现在已经刷到了 5950秒, 数据同步有延迟, 仅供参考
现在已经刷到了 6050秒, 数据同步有延迟, 仅供参考
现在已经刷到了 6126秒, 数据同步有延迟, 仅供参考
现在已经刷到了 6245秒, 数据同步有延迟, 仅供参考
现在已经刷到了 6356秒, 数据同步有延迟, 仅供参考
第 1 个账号: ❌❌❌❌❌
('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
