### ISSUE TITLE
[Bug] 爱奇艺签到风险

### ISSUE THREAD

**Issue by 1934103887** [Sitoi/dailycheckin#420]
### 💻 系统环境

Other Linux

### 📦 部署环境

Docker

### 🐛 问题描述

![微信截图_20240802172305](https://github.com/user-attachments/assets/3d0f6d26-7186-4b2e-be62-4d3630b1f3bc)

### 📝 运行日志

----------开始执行「爱奇艺」签到----------
{'code': 'Q00393', 'msg': '超过次数赠送限额', 'data': None}
{'code': 'Q00393', 'msg': '超过次数赠送限额', 'data': None}
{'code': 'Q00393', 'msg': '超过次数赠送限额', 'data': None}
现在已经刷到了 8575秒, 数据同步有延迟, 仅供参考
第 1 个账号: ✅✅✅✅✅

**Comment by Sitoi** [comment]
换手机的cookie 试试看
