### ISSUE TITLE
[Bug] 哔哩哔哩签到投币给未关注UP

### ISSUE THREAD

**Issue by ShiroganeMiyuki** [Sitoi/dailycheckin#424]
### 💻 系统环境

Other Linux

### 📦 部署环境

青龙

### 🐛 问题描述

部署环境为爱快中的Dockers，青龙面板，今日查看签到日志发现给一绝区0UP投币，搜索发现本人并未关注此UP，请解释一下，谢谢！
![QQ图片20240815150156](https://github.com/user-attachments/assets/18533a36-a76e-439b-a1ec-f98b223841d4)
![QQ图片20240815150214](https://github.com/user-attachments/assets/97294f1c-d9cd-4bd9-a697-005dac196793)
![QQ图片20240815150336](https://github.com/user-attachments/assets/ff34f88d-d708-4029-aeb3-84008312815e)

## 开始执行... 2024-08-15 14:51:57

当前时间: 2024-08-15 14:51:58
当前版本: 24.5.15
使用配置文件路径: /ql/data/scripts/config.json

---------- 本次执行签到任务如下 ----------

「Bilibili」账号数 : 1
「什么值得买」账号数 : 1
「V2EX 论坛」账号数 : 1

----------开始执行「Bilibili」签到----------
{'aid': 112957992208250, 'cid': 500001650130506, 'title': '【绝区零剧场】绝对不要和青衣“作对”', 'owner': '复色点映室'}
{'aid': 1306338937, 'cid': 1631408105, 'title': '斑:本以为是真爱粉，没想到是小黑子...', 'owner': '戏志才PPT'}
{'aid': 112959871256453, 'cid': 500001649291792, 'title': '一弘 漫画合集', 'owner': '漫画动漫电影'}
{'aid': 1856418463, 'cid': 1620573988, 'title': '声援，拒绝烂梗', 'owner': '虾饺剪辑'}
{'aid': 112863905580213, 'cid': 500001630336321, 'title': '再给2.5次机会，我还是会选你', 'owner': '我就是要那个土豆ya'}
{'aid': 1806374185, 'cid': 1649385370, 'title': '精致变种人第一次坐高铁都干些什么', 'owner': '动画-小子'}
成功给【绝区零剧场】绝对不要和青衣“作对”投一个币
成功给斑:本以为是真爱粉，没想到是小黑子...投一个币
成功给一弘 漫画合集投一个币
成功给声援，拒绝烂梗投一个币
第 1 个账号: ✅✅✅✅✅
----------开始执行「什么值得买」签到----------
第 1 个账号: ✅✅✅✅✅
----------开始执行「V2EX 论坛」签到----------
第 1 个账号: ✅✅✅✅✅

server 酱 Turbo 推送开始
server 酱 Turbo 推送开始
server 酱 Turbo 推送开始
server 酱 Turbo 推送开始

## 执行结束...   耗时 11 秒

**Comment by xlenco** [comment]
我的也有这个问题

**Comment by Sitoi** [comment]
Bilibili 投币方式 默认为 0 ；1: 为关注用户列表视频投币 0: 为随机投币。如果关注用户发布的视频不足配置的投币数，则剩余部分使用随机投币
