### ISSUE TITLE
[Bug] 飞书通知失败

### ISSUE THREAD

**Issue by xlenco** [Sitoi/dailycheckin#425]
### 💻 系统环境

Linux

### 📦 部署环境

青龙

### 🐛 问题描述

已在 config.json中配置飞书FSKEY（可用），日志中
```
显示飞书 推送开始

## 执行结束... 2024-08-15 17:17:54  耗时 48 秒　　　　　
```
但飞书中无消息

## 开始执行... 2024-08-15 17:17:06

当前时间: 2024-08-15 17:17:07
当前版本: 24.5.15
使用配置文件路径: /ql/data/scripts/config.json

---------- 本次执行签到任务如下 ----------

「奥拉星」账号数 : 1
「Bilibili」账号数 : 1
「有道云笔记」账号数 : 1

----------开始执行「奥拉星」签到----------
开始任务：《奥拉星2》手游预约
返回状态：任务还没有完成喔！
开始任务：邀请3人预约《奥拉星2》
返回状态：任务还没完成哦
开始任务：邀请1人预约《奥拉星2》
返回状态：任务还没完成哦
开始任务：奥奇手游公测下载
返回状态：success
开始任务：每日查看最新预告
返回状态：success
第 1 个账号: ✅✅✅✅✅
----------开始执行「Bilibili」签到----------
{'code': 6034010, 'message': '会员状态异常，暂时无法领取~', 'ttl': 1, 'data': None}
{'code': 6034010, 'message': '会员状态异常，暂时无法领取~', 'ttl': 1, 'data': None}
{'code': 6034010, 'message': '会员状态异常，暂时无法领取~', 'ttl': 1, 'data': None}
{'code': 6034010, 'message': '会员状态异常，暂时无法领取~', 'ttl': 1, 'data': None}
{'code': 6034010, 'message': '会员状态异常，暂时无法领取~', 'ttl': 1, 'data': None}
{'code': 6034010, 'message': '会员状态异常，暂时无法领取~', 'ttl': 1, 'data': None}
{'code': 6034010, 'message': '会员状态异常，暂时无法领取~', 'ttl': 1, 'data': None}
{'code': 0, 'message': '0', 'ttl': 1, 'data': {'privilege': {'type': 0, 'state': 0, 'expire_time': 0, 'vip_type': 0, 'next_receive_days': 0, 'period_end_unix': 0, 'is_count': False, 'name': '', 'coupon_code': '', 'app_describe': '', 'recive_state': 0, 'salary_type': 0, 'exp_params': None}}}
{'code': 6034010, 'message': '会员状态异常，暂时无法领取~', 'ttl': 1, 'data': None}
已获取足够关注用户的视频
{'aid': 1656482937, 'cid': 1649294563, 'title': '恶搞之家种族歧视，布莱恩侮辱黑人遭驱逐，皮特平安夜悄悄去世', 'owner': '毒邪动漫'}
{'aid': 1456407225, 'cid': 1629087512, 'title': '【13小时爽看】一口气看完沙雕动画【虾仁如意小郎君】蹲坑版！', 'owner': '老周沙雕动画'}
{'aid': 112949637287922, 'cid': 500001648375869, 'title': '『怪兽娘』银河☆日常 第一卷番外篇', 'owner': '小泽放映厅'}
{'aid': 1354086806, 'cid': 1532471190, 'title': '《大梦千年》第51集，冠军侯霍去病', 'owner': '虾仁饭动画'}
{'aid': 112954066338877, 'cid': 500001648105355, 'title': '【OC】这个是遭受虐待的手势', 'owner': 'Un_4tu9te'}
{'aid': 1706373628, 'cid': 1630826778, 'title': '【补档】看新番后悔三个月，不看新番后悔一辈子！2024年7月新番吐槽！', 'owner': 'ShinO_opin'}
成功给恶搞之家种族歧视，布莱恩侮辱黑人遭驱逐，皮特平安夜悄悄去世投一个币
成功给【13小时爽看】一口气看完沙雕动画【虾仁如意小郎君】蹲坑版！投一个币
第 1 个账号: ❌❌❌❌❌
'NoneType' object is not iterable
----------开始执行「有道云笔记」签到----------
第 1 个账号: ✅✅✅✅✅

飞书 推送开始

## 执行结束... 2024-08-15 17:17:54  耗时 48 秒

**Comment by JamKing7** [comment]
是不是跟我一样配置了前面的公共地址 https://open.larksuite.com/open-apis/bot/v2/hook/xxxx
仅保留最后的一串字符 xxxx 就可以了
