### ISSUE TITLE
[Bug] 小米运动报错

### ISSUE THREAD

**Issue by stoneliulei** [Sitoi/dailycheckin#428]
### 💻 系统环境

Other Linux

### 📦 部署环境

Docker

### 🐛 问题描述

HTTPSConnectionPool(host='api-user.huami.com', port=443): Max retries exceeded with url: /registrations/+8615874224715/tokens (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe94ee9d520>: Failed to establish a new connection: [Errno -3] Try again'))

### 📝 运行日志

当前时间: 2024-08-18 23:48:20
当前版本: 24.2.27

另：请问怎么更新到最新版本

**Comment by Sitoi** [comment]
网络问题，更新到最新版本需要 python3.9
