### ISSUE TITLE
爱奇艺获取的COOKIE问题

### ISSUE THREAD

**Issue by ZHENGZENGQIU** [Sitoi/dailycheckin#43]
## 1.关于你要提交的问题

Q：是否搜索了 issue（包括已关闭的issue）

- [ ] 没有类似的 issue 

Q：是否仔细阅读了教程

- [X ] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装 Python
- [ ] 方法二：Docker
- [ ] 方法三：腾讯云函数
- [X ] 方法四：GitHub Actions

### (1) 具体问题

A：在爱奇艺获取的COOKIE无法使用，总有一段无法解析，QYABEX={"x":"x","x":{"value":"x","x":"x"}}，同样的操作，哔哩哔哩几个就正常，无痕模式获取的也无法使用

### (2) 详细日志

A：Expecting value: line 3 column 1633 (char 1640)

**Comment by Sitoi** [comment]
把有问题的字段删了吧

**Comment by ZHENGZENGQIU** [comment]
> 把有问题的字段删了吧

已解决，谢谢！！！
