### ISSUE TITLE
v2ex签到报错

### ISSUE THREAD

**Issue by zlhdd108** [Sitoi/dailycheckin#43]
![image](https://user-images.githubusercontent.com/16465666/134789667-690838a0-5d25-4f4e-969a-b1ecfacdd29b.png)
cookie相关的双引号已经用了转义符，代理也配置了

**Comment by Sitoi** [comment]
重新获取 cookie 试试

**Comment by monkey-sking** [comment]
同样的问题

**Comment by liberize** [comment]
+1
