### ISSUE TITLE
[Request] 怎么更新

### ISSUE THREAD

**Issue by stoneliulei** [Sitoi/dailycheckin#430]
### 🥰 需求描述

当前版本: 24.2.27
最新版本: 24.5.15
项目地址: https://github.com/Sitoi/dailycheckin

### 🧐 解决方案

当前版本: 24.2.27
最新版本: 24.5.15
项目地址: https://github.com/Sitoi/dailycheckin

### 📝 补充信息

当前版本: 24.2.27
最新版本: 24.5.15
项目地址: https://github.com/Sitoi/dailycheckin

**Comment by Sitoi** [comment]
python 更新到3.9 及以上
