### ISSUE TITLE
[Request] 您使用的软件调用了废弃域名

### ISSUE THREAD

**Issue by LiuYiLin-CA** [Sitoi/dailycheckin#431]
### 🥰 需求描述

您使用的软件调用了废弃域名 sc.ftqq.com ，即将下线。请尽快联系软件开发者（注意不是sct.ftqq.com）将其更换为 sctapi.ftqq.com。

### 🧐 解决方案

将推送通知服务 sc.ftqq.com替换为sctapi.ftqq.com

**Comment by starsink-d** [comment]
![image](https://github.com/user-attachments/assets/a7544740-399d-45b8-a80a-c7a880aa0ac7)

**Comment by PDxtXHd** [comment]
你配置文件里填server 酱 Turbo的key就是调的新接口
