### ISSUE TITLE
[Bug] 小米运动，淘宝时间戳获取接口常见异常

### ISSUE THREAD

**Issue by FDrag0n** [Sitoi/dailycheckin#433]
### 💻 系统环境

Other Linux

### 📦 部署环境

青龙

### 🐛 问题描述

<img width="981" alt="image" src="https://github.com/user-attachments/assets/06d82e50-4c6f-4060-8ba9-cc47150ab321">

淘宝获取时间戳的地方应该是加了风控，访问常见超时或者拒绝，可以用本地时间戳作备用

参考逻辑
`str(int(time.time()) * 1000)`

### 📝 运行日志

HTTPConnectionPool(host='api.m.taobao.com', port=80): Max retries exceeded with url: /rest/api3.do?api=mtop.common.getTimestamp (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff35159cd50>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by lg469** [comment]
时间戳可以换这个接口https://acs.m.taobao.com/gw/mtop.common.getTimestamp/

**Comment by Cuigd** [comment]
怎么换啊

> 时间戳可以换这个接口https://acs.m.taobao.com/gw/mtop.common.getTimestamp/

**Comment by FDrag0n** [comment]
> 怎么换啊
> 
> > 时间戳可以换这个接口https://acs.m.taobao.com/gw/mtop.common.getTimestamp/

https://github.com/Sitoi/dailycheckin/blob/main/dailycheckin/mimotion/main.py#L22

**Comment by Cuigd** [comment]
> > 怎么换啊
> > > 时间戳可以换这个接口https://acs.m.taobao.com/gw/mtop.common.getTimestamp/
> 
> https://github.com/Sitoi/dailycheckin/blob/main/dailycheckin/mimotion/main.py#L22

Traceback (most recent call last):
  File "/ql/data/scripts/Sitoi_dailycheckin/dailycheckin/mimotion/main.swap.py", line 127, in <module>
    print(MiMotion(check_item=item).main())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ql/data/scripts/Sitoi_dailycheckin/dailycheckin/mimotion/main.swap.py", line 88, in main
    login_token, userid = self.login(phone, password)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ql/data/scripts/Sitoi_dailycheckin/dailycheckin/mimotion/main.swap.py", line 51, in login
    location = r1.headers["Location"]
               ~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'location'
这种怎么解决啊
