### ISSUE TITLE
更新dailycheckin问题

### ISSUE THREAD

**Issue by taichao1** [Sitoi/dailycheckin#437]
作者你好，我的青龙面板部署后死活更新不了，能不能告诉我该怎么解决呢？谢谢。
![1725680883861](https://github.com/user-attachments/assets/21cc6961-2e17-4ebe-a410-f6a63af0acb7)

**Comment by PDxtXHd** [comment]
你网络太差了，你没发现报错全都是在下载文件的地方吗

**Comment by taichao1** [comment]
谢谢，我已经解决了，是网络问题。
