### ISSUE TITLE
企业微信应用推送失效

### ISSUE THREAD

**Issue by wzgrx** [Sitoi/dailycheckin#44]
企业微信应用消息推送开始

Starting new HTTPS connection (1): qyapi.weixin.qq.com:443

https://qyapi.weixin.qq.com:443 "GET /cgi-bin/gettoken?corpid=ww9c940dc324asdc32&corpsecret=n9Znw0gE9AVWWFpsabcdMCbBKvaA_ivI08mGZHQW4Mk HTTP/1.1" 200 196

Starting new HTTPS connection (1): qyapi.weixin.qq.com:443

https://qyapi.weixin.qq.com:443 "POST /cgi-bin/message/send?access_token=False HTTP/1.1" 200 49

Response RequestId:ef9414a7-8cb6-42ae-806c-60ab54ecefa1 RetMsg:null

END RequestId:ef9414a7-8cb6-42ae-806c-60ab54ecefa1

Report RequestId:ef9414a7-8cb6-42ae-806c-60ab54ecefa1 Duration:158117ms Memory:128MB MemUsage:44.546875MB

**Comment by iwakaka** [comment]
corpsecret 不对吧 有四段  _ 分开的
