### ISSUE TITLE
[Bug] 更新报错 卸载依赖后无法安装

### ISSUE THREAD

**Issue by McdullD** [Sitoi/dailycheckin#444]
### 💻 系统环境

Other Linux

### 📦 部署环境

青龙

### 🐛 问题描述

开始安装依赖 dailycheckin，开始时间 2024-09-29 13:52:42

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f0749195310>: Failed to establish a new connection: [Errno -3] Try again')': /simple/dailycheckin/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f0749195ad0>: Failed to establish a new connection: [Errno -3] Try again')': /simple/dailycheckin/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f0749196790>: Failed to establish a new connection: [Errno -3] Try again')': /simple/dailycheckin/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f0749197150>: Failed to establish a new connection: [Errno -3] Try again')': /simple/dailycheckin/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f0749197bd0>: Failed to establish a new connection: [Errno -3] Try again')': /simple/dailycheckin/
ERROR: Could not find a version that satisfies the requirement dailycheckin (from versions: none)
ERROR: No matching distribution found for dailycheckin

依赖安装失败，结束时间 2024-09-29 13:53:20，耗时 38 秒

**Comment by Sitoi** [comment]
检测自己网络问题，更换合适的 pypi 源
