### ISSUE TITLE
[Bug] 哔哩哔哩签到投币给未关注UP

### ISSUE THREAD

**Issue by megumiss** [Sitoi/dailycheckin#445]
### 💻 系统环境

Other Linux

### 📦 部署环境

青龙

### 🐛 问题描述

cron_type 设置为1，仍然会投币给未关注up
![image](https://github.com/user-attachments/assets/3056138d-1bb5-430e-99e4-338fe1aabbc2)
![image](https://github.com/user-attachments/assets/6551f9e9-4e10-49ed-a318-906829258c26)
所有的up都没关注
![image](https://github.com/user-attachments/assets/7dc427f5-c04a-4f61-9747-45e83789b62d)

**Comment by Sitoi** [comment]
Bilibili 投币方式 默认为 0 ；1: 为关注用户列表视频投币 0: 为随机投币。如果关注用户发布的视频不足配置的投币数，则剩余部分使用随机投币

**Comment by megumiss** [comment]
> Bilibili 投币方式 默认为 0 ；1: 为关注用户列表视频投币 0: 为随机投币。如果关注用户发布的视频不足配置的投币数，则剩余部分使用随机投币

![image](https://github.com/user-attachments/assets/bb93044d-f267-447d-831b-fc191c2b697c)
coin_type是1
不是因为接口更新了么，现在页面的接口看到的是https://api.bilibili.com/x/space/wbi/arc/search，不是https://api.bilibili.com/x/space/arc/search
![image](https://github.com/user-attachments/assets/ad9f5234-a536-4cd0-b295-c6e049bc094f)
