### ISSUE TITLE
什么值得买签到报错'latin-1' codec can't encode characters in position 994-997: ordinal not in range(256) 签到失败

### ISSUE THREAD

**Issue by hot012** [Sitoi/dailycheckin#45]
我是在docker中配置的服务
我把什么值得买的cookie全部复制出来了，把双引号和斜线前面都加了反斜线后，都粘到了config.json 对应的cookie下
![image](https://user-images.githubusercontent.com/77259469/135702393-cc352fe8-9ab8-4b53-8307-716fc71572dd.png)
手动执行后界面没什么提示，但是推送的消息中提示签到失败'latin-1' codec can't encode characters in position 994-997: ordinal not in range(256)

![image](https://user-images.githubusercontent.com/77259469/135702441-914842f5-88f7-4f63-a6f5-036bdc2cb29e.png)
![image](https://user-images.githubusercontent.com/77259469/135702486-9ed87bb2-4baf-478f-8e93-ee0ce0f0c3b4.png)

这是什么原因导致的呢？是因为cookie 中有中文？该怎么处理一下呢？辛苦各位大佬帮忙解答一下,感谢~
![image](https://user-images.githubusercontent.com/77259469/135702559-3d7d1e4b-8cce-4534-b816-0308ca6bfc3c.png)

**Comment by ydbdyds** [comment]
cookie里面的中文直接删了就行

**Comment by hot012** [comment]
> cookie里面的中文直接删了就行

没想到这么简单的方法就解决了，感谢~
