### ISSUE TITLE
哔咔漫画签到每天都是重复签到

### ISSUE THREAD

**Issue by lfscqk67** [Sitoi/dailycheckin#46]
![IMG_20211003_005024](https://user-images.githubusercontent.com/37235589/135725493-4855012c-ff26-4856-b880-4591f0f7c8b3.jpg)

**Comment by Sitoi** [comment]
重新获取 cookie 试试

**Comment by lfscqk67** [comment]
> 重新获取 cookie 试试
哔咔是账号密码
