### ISSUE TITLE
联通营业厅的登录返回参数变了

### ISSUE THREAD

**Issue by BillScott1024** [Sitoi/dailycheckin#48]
## 1.关于你要提交的问题

Q：是否搜索了 issue（包括已关闭的issue）

- [x] 没有类似的 issue 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装 Python
- [ ] 方法二：Docker
- [x] 方法三：腾讯云函数
- [ ] 方法四：GitHub Actions

### (1) 具体问题

A：联通营业厅抓包登录的返回参数变了，没有simCount那些内容了

### (2) 详细日志

A：抓包记录

**Comment by Sitoi** [comment]
刚测试 没变依旧在，请详细阅读文档
