### ISSUE TITLE
fm米家的cookie找不到

### ISSUE THREAD

**Issue by yyznw** [Sitoi/dailycheckin#49]
blackbox、device_id、token什么的都没问题，看了抓的包，就是找不到cookie，谁能指点下

**Comment by Sitoi** [comment]
安卓好像是这样 我今晚回去试试

**Comment by yyznw** [comment]
感谢，取值还需指点下

**Comment by Hellogu** [comment]
俺也是，ios下抓包找不到cookie
Host: fmapp.chinafamilymart.com.cn
Content-Type: application/json
Accept: */*
loginChannel: app
os: ios
Accept-Language: zh-Hans-CN;q=1.0
token: ***
Accept-Encoding: br;q=1.0, gzip;q=0.9, deflate;q=0.8
deviceId: ***
User-Agent: Fa
Content-Length: 36
Connection: keep-alive
fmVersion: 2.6.4
blackBox: ***
