### ISSUE TITLE
天翼云盘无法签到

### ISSUE THREAD

**Issue by Agameadream** [Sitoi/dailycheckin#49]
## 1.关于你要提交的问题

Q：是否搜索了 issue（包括已关闭的issue）

- [x] 没有类似的 issue 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装 Python
- [ ] 方法二：Docker
- [x] 方法三：腾讯云函数
- [ ] 方法四：GitHub Actions

### (1) 具体问题

A：
没有自动签到，其他都正常。
### (2) 详细日志

A：

**Comment by Sitoi** [comment]
有日志信息吗？检查下账号是否正确，脚本理论没问题
