### ISSUE TITLE
使用 Docker教程 没有自动运行 也没有生成日志。  确认容器安装好了的。   

### ISSUE THREAD

**Issue by 50733364** [Sitoi/dailycheckin#5]
## 1.关于你要提交的问题

Q：是否搜索了 issue（包括已关闭的issue）

- [ X] 没有类似的 issue 

Q：是否仔细阅读了教程

- [ X] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装 Python
- [ X] 方法二：Docker
- [ ] 方法三：腾讯云函数
- [ ] 方法四：GitHub Actions

### (1) 具体问题

A：使用 Docker教程 文件与文件夹建好了 也配置好了  也输入了 启动容器。 但脚本没有自动运行 也没有生成日志。  确认容器安装好了的。   

### (2) 详细日志

A：使用 Docker教程 文件与文件夹建好了 也配置好了  也输入了 启动容器。 但脚本没有自动运行 也没有生成日志。  确认容器安装好了的。

**Comment by Sitoi** [comment]
config.json 配置好了吗

**Comment by Sitoi** [comment]
因为是定时任务 立即启动没有日志是正常的

**Comment by 50733364** [comment]
配置好了哦.   我大概放他运行了 两小时左右 也没有日志。 嗯  之前装过一次。 也是同样流程  大概半小时 喜马拉雅跟企鹅读书都有日志。

**Comment by 50733364** [comment]
我现在重新装一次试试。

**Comment by Sitoi** [comment]
企鹅是11分钟 应该最多11分钟 如果你企鹅配置好的话

**Comment by 50733364** [comment]
对的 我知道是11分钟。   脚本有 手动执行的命令吗？ 这样子可以方便测试。

**Comment by Sitoi** [comment]
> 对的 我知道是11分钟。   脚本有 手动执行的命令吗？ 这样子可以方便测试。

你可以运行。docker exec 相关命令 进入 docker 运行 对应的脚本

**Comment by 50733364** [comment]
你好  我想问下 我执行完启动后 显示这个是安装好了对吧？
Creating network "dailycheckin_default" with the default driver
Pulling dailycheckin (sitoi/dailycheckin:latest)...
latest: Pulling from sitoi/dailycheckin
801bfaa63ef2: Pull complete
7678dd7631a2: Pull complete
4c6139ab40d8: Pull complete
ff5ef8cd8062: Pull complete
73dee1f700a1: Pull complete
1f680c13ffea: Pull complete
00b9006466dd: Pull complete
e1f31275b6f0: Pull complete
Digest: sha256:2a2d7e5162dc0d1cea0f5d4a35be2acb75a680e0e4b990433eb36dde4e047c20
Status: Downloaded newer image for sitoi/dailycheckin:latest
Creating dailycheckin ... done

**Comment by Sitoi** [comment]
对的呀

**Comment by 50733364** [comment]
可以运行了  打扰作者老哥了。

**Comment by 50733364** [comment]
老哥问下。  我设置了钉钉推送  它是多少次推送 还是每次都推送？    然后我现在也没有收到推送。
打扰老哥了

**Comment by Sitoi** [comment]
> 老哥问下。 我设置了钉钉推送 它是多少次推送 还是每次都推送？ 然后我现在也没有收到推送。
> 打扰老哥了

现在是死的 常规签到是 8：45 然后 阅读和 喜马拉雅 都是 每天 9点 和 18点 两次
