### ISSUE TITLE
【每日支付宝红包】

### ISSUE THREAD

**Issue by Sitoi** [Sitoi/dailycheckin#50]
复制本通知，打开支付宝搜索 712364010 或点击链接扫描下方二维码 有大红包
![](https://user-images.githubusercontent.com/32479597/136578623-c9742953-7fbe-4fb5-b631-53c6c70e760d.png)

**Comment by Alone4869** [comment]
每条通知都发一次。。。

**Comment by h7ml** [comment]
如何关闭该通知

**Comment by geelph** [comment]
> 如何关闭该通知

改代码，....Python38\Lib\site-packages\dailycheckin\utils\message.py中的important_notice()函数发的就是这个通知

**Comment by h7ml** [comment]
> > 如何关闭该通知
> 
> 改代码，....Python38\Lib\site-packages\dailycheckin\utils\message.py中的important_notice()函数发的就是这个通知

thanks

**Comment by horryo** [comment]
一般在/usr/lib/python3.8/site-packages/dailycheckin/utils/,然后vi message.py,找到def important_notice():函数，大概在162行，然后在下面return notice上面加一行notice = None，要加空格与return notice平齐，然后esc，:wq回车保存即可，如下图
![image](https://user-images.githubusercontent.com/64786161/137513219-6f2c73d4-ede5-498d-a428-463080308c50.png)

**Comment by Alone4869** [comment]
> 一般在/usr/lib/python3.8/site-packages/dailycheckin/utils/,然后vi message.py,找到def important_notice():函数，大概在162行，然后在下面return notice上面加一行notice = None，要加空格与return notice平齐，然后esc，:wq回车保存即可，如下图
> ![image](https://user-images.githubusercontent.com/64786161/137513219-6f2c73d4-ede5-498d-a428-463080308c50.png)

👌
