### ISSUE TITLE
求问docker运行持久文件问题

### ISSUE THREAD

**Issue by wyfang** [Sitoi/dailycheckin#51]
我在服务器上运行的话，我习惯让docker文件放在 /home 下面，比如frp我就是放 /home/frp/ 这样方便管理。

这一键运行的话，是否有办法让其全部文件在 /home/dailycheckin/ 下？

**Comment by Sitoi** [comment]
可以 docker-compose down 之后，修改 docker-compose.yml 的挂载目录即可

**Comment by wyfang** [comment]
> 可以 docker-compose down 之后，修改 docker-compose.yml 的挂载目录即可

懂了，其实我直接在 /home/dailycheckin/ 下运行：
curl https://gitee.com/sitoi/dailycheckin/raw/main/docker_start.sh | bash

它文件自然就都在这目录下。
