### ISSUE TITLE
联通营业厅 BUG 反馈

### ISSUE THREAD

**Issue by BillScott1024** [Sitoi/dailycheckin#52]
我这边好像确实没有这个参数。这个是截图，关键信息已打码
抓包链接是： https://m.client.10010.com/mobileService/login.htm
请求头：
![image](https://user-images.githubusercontent.com/22955480/106453558-7852ec00-64c4-11eb-98fb-d1362d416881.png)

请求内容是：
![image](https://user-images.githubusercontent.com/22955480/106453575-7d17a000-64c4-11eb-802f-7dffb7a7383c.png)

**Comment by Sitoi** [comment]
在请求内容里 不是请求头和 返回内容

**Comment by BillScott1024** [comment]
找到了，复制填入后，签到失败了
![image](https://user-images.githubusercontent.com/22955480/106457567-1a290780-64ca-11eb-8e98-d912a449ebbf.png)

**Comment by Sitoi** [comment]
参赛还是有问题吧 好好看文档
