### ISSUE TITLE
你好，打扰了， 腾讯视频、日志问题、bark推送问题

### ISSUE THREAD

**Issue by choyung** [Sitoi/dailycheckin#54]
## 1.关于你要提交的问题

Q：是否搜索了 issue（包括已关闭的issue）

- [x ] 没有类似的 issue 

Q：是否仔细阅读了教程

- [x ] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装 Python
- [x ] 方法二：Docker
- [ ] 方法三：腾讯云函数
- [ ] 方法四：GitHub Actions

### (1) 具体问题
腾讯视频不知道是不是没有签到，我看app详情里面昨天喝前天都是定时的8.45有数据
然后，日志怎么显示的这样呀？已附
最后：已经设置了bark推送，好像一直没有接到过
![image](https://user-images.githubusercontent.com/22350269/107105979-27484c80-6864-11eb-8532-288d701ca620.png)

多谢分享docker，幸苦了。
A：

### (2) 详细日志

A：
Feb 06 08:47:17 ---------- 开始执行 IQIYI_COOKIE_LIST 签到----------
Feb 06 08:47:17 list index out of range
Feb 06 08:47:17 ---------- 开始执行 VQQ_COOKIE_LIST 签到----------
Feb 06 08:47:17 list index out of range
Feb 06 08:47:17 ---------- 开始执行 KGQQ_COOKIE_LIST 签到----------
Feb 06 08:47:17 ---------- 开始执行 MUSIC163_ACCOUNT_LIST 签到----------
Feb 06 08:47:17 ---------- 开始执行 BILIBILI_COOKIE_LIST 签到----------
Feb 06 08:47:17 list index out of range
Feb 06 08:47:17 ---------- 开始执行 YOUDAO_COOKIE_LIST 签到----------
Feb 06 08:47:17 list index out of range
Feb 06 08:47:17 ---------- 开始执行 FMAPP_ACCOUNT_LIST 签到----------
Feb 06 08:47:17 错误信息 'latin-1' codec can't encode characters in position 0-1: ordinal not in range(256)
Feb 06 08:47:17 错误信息 'latin-1' codec can't encode characters in position 0-1: ordinal not in range(256)
Feb 06 08:47:17 错误信息 'latin-1' codec can't encode characters in position 0-1: ordinal not in range(256)
Feb 06 08:47:17 ---------- 开始执行 BAIDU_URL_SUBMIT_LIST 签到----------
Feb 06 08:47:17 'NoneType' object is not subscriptable
Feb 06 08:47:17 ---------- 开始执行 LIANTONG_ACCOUNT_LIST 签到----------
Feb 06 08:47:17 ---------- 开始执行 ONEPLUSBBS_COOKIE_LIST 签到----------
Feb 06 08:47:17 list index out of range
Feb 06 08:47:17 ---------- 开始执行 SMZDM_COOKIE_LIST 签到----------
Feb 06 08:47:17 list index out of range
Feb 06 08:47:17 ---------- 开始执行 TIEBA_COOKIE_LIST 签到----------
Feb 06 08:47:17 list index out of range
Feb 06 08:47:17 ---------- 开始执行 V2EX_COOKIE_LIST 签到----------
Feb 06 08:47:17 list index out of range
Feb 06 08:47:17 ---------- 开始执行 WWW2NZZ_COOKIE_LIST 签到----------
Feb 06 08:47:17 list index out of range
Feb 06 08:47:17 ---------- 开始执行 ACFUN_ACCOUNT_LIST 签到----------
Feb 06 08:47:17 ---------- 开始执行 MIMOTION_ACCOUNT_LIST 签到----------
Feb 06 08:47:17 can only concatenate str (not "int") to str
Feb 06 08:47:17 ---------- 开始执行 CLOUD189_ACCOUNT_LIST 签到----------
Feb 06 08:47:17 ---------- 开始执行 CITY_NAME_LIST 签到----------
Feb 06 08:47:17 ---------- 开始执行 XMLY_COOKIE_LIST 签到----------
Feb 06 08:47:17 Dingtalk 推送开始
Feb 06 08:47:17 server 酱推送开始
Feb 06 08:47:17 qmsg 酱推送开始
Feb 06 08:47:17 qmsg 酱推送开始
Feb 06 08:47:17 qmsg 酱推送开始
Feb 06 08:47:17 qmsg 酱推送开始
Feb 06 08:47:17 qmsg 酱推送开始
Feb 06 08:47:17 qmsg 酱推送开始
Feb 06 08:47:17 qmsg 酱推送开始
Feb 06 08:47:17 qmsg 酱推送开始
Feb 06 08:47:17 qmsg 酱推送开始
Feb 06 08:47:17 qmsg 酱推送开始
Feb 06 08:47:17 qmsg 酱推送开始
Feb 06 08:47:17 qmsg 酱推送开始
Feb 06 08:47:17 Telegram 推送开始

**Comment by Sitoi** [comment]
bark 是需要下载 iOS app 的，日志改为了只输出错误日志，腾讯的话可能是 cookie 掉了

**Comment by choyung** [comment]
> bark 是需要下载 iOS app 的，日志改为了只输出错误日志，腾讯的话可能是 cookie 掉了

bark我有下载app，填写的配置如上图那样，不过从来没接收到过bark的推送，不管是失败还是成功，不知道是不是我还有哪里没设置对呢？T.T
