### ISSUE TITLE
关于小米运动的value

### ISSUE THREAD

**Issue by Agameadream** [Sitoi/dailycheckin#55]
## 1.关于你要提交的问题

Q：是否搜索了 issue（包括已关闭的issue）

- [x] 没有类似的 issue 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装 Python
- [ ] 方法二：Docker
- [ ] 方法三：腾讯云函数
- [x] 方法四：GitHub Actions

### (1) 具体问题

A：
config配置文件中，最小步数和最大步数的值应该填整数，而不是字符串。不然产生随机数的时候，会因为没把字符串转为整数类型，然后报错。

### (2) 详细日志

A：
 File "D:\PycharmProjects\dailycheckin\mimotion\mimotion.py", line 72, in main
    step = str(random.randint(min_step, max_step))  #此处min_step, max_step类型为str
  File "D:\python\lib\random.py", line 338, in randint
    return self.randrange(a, b+1)
TypeError: can only concatenate str (not "int") to str

**Comment by Sitoi** [comment]
步数写成数字吧 我有空优化下。就是把 value 两边的引号去了

**Comment by 5axf** [comment]
> 步数写成数字吧 我有空优化下。就是把 value 两边的引号去了

小米运动的定时任务时间能不能单独设置一下，其他的签到任务早上八点四十五执行没啥问题，但是这个刷步数，大早上就上万步了，一看就很不真实，建议改成下午六七点执行小米运动的任务
