### ISSUE TITLE
腾讯视频、网易云音乐签到失败

### ISSUE THREAD

**Issue by DoveBoy** [Sitoi/dailycheckin#56]
云函数环境运行的，已经更新到最新版本了，腾讯视频和网易云音乐签到都是失败的，腾讯视频已按照教程中的方式抓取了auth_refresh和auth_refresh下的cookie
![image](https://user-images.githubusercontent.com/19201447/137301845-d591b094-5898-472c-aa53-4e986c9d7409.png)
![image](https://user-images.githubusercontent.com/19201447/137301863-9d9ed5dc-0ef0-4f9f-b327-147863ad0e91.png)

**Comment by Sitoi** [comment]
登录了不要退出

**Comment by DoveBoy** [comment]
> 登录了不要退出

没有退出，并且脚本中网易云音乐本身就是使用账号密码方式登录的，不存在退出啊
