### ISSUE TITLE
PICACOMIC签到超时

### ISSUE THREAD

**Issue by Meltryllis163** [Sitoi/dailycheckin#59]
推送信息如下：
HTTPSConnectionPool(host='picaapi.picacomic.com', port=443): Max retries exceeded with url: /auth/sign-in (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f738255ecc0>, 'Connection to picaapi.picacomic.com timed out. (connect timeout=60)'))

**Comment by Sitoi** [comment]
设置代理

**Comment by Silentely** [comment]
> 设置代理

请问config里代理变量要怎么设置？
