### ISSUE TITLE
咔叽网单无法签到

### ISSUE THREAD

**Issue by Agameadream** [Sitoi/dailycheckin#59]
## 1.关于你要提交的问题

Q：是否搜索了 issue（包括已关闭的issue）

- [x] 没有类似的 issue 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装 Python
- [ ] 方法二：Docker
- [ ] 方法三：腾讯云函数
- [x] 方法四：GitHub Actions

### (1) 具体问题

A：
1.咔叽网单无法签到，签到失败。
2.希望workflows执行时间能改为北京时间。
### (2) 详细日志

A：

**Comment by Sitoi** [comment]
咔叽网站签到正常
ac 已修改为北京时间早 8:45 执行签到，8:15 拉取最新代码

**Comment by Agameadream** [comment]
> 咔叽网站签到正常
> ac已修改为北京时间早8:45执行签到，8：15拉取最新代码

我这边确实前到不了，用户是登录成功的。
![kjwd](https://user-images.githubusercontent.com/56859734/107303737-97501000-6aba-11eb-9cb7-e0c32f5bc644.jpg)

**Comment by Sitoi** [comment]
换个 cookie 试试

**Comment by Agameadream** [comment]
> 换个 cookie 试试

尝试过好几次了，每次都是失败。

**Comment by Sitoi** [comment]
开无痕试试？

**Comment by Agameadream** [comment]
> 咔叽网站签到正常
> ac已修改为北京时间早8:45执行签到，8：15拉取最新代码



> 开无痕试试？

没法，换了几次都失败。

**Comment by Sitoi** [comment]
不清楚具体原因，不知道你是个咧还是都这样。

**Comment by Sitoi** [comment]
咔叽 已修复。
