### ISSUE TITLE
能否支持吾爱自动签到

### ISSUE THREAD

**Issue by Phoebus888** [Sitoi/dailycheckin#60]
链接:https://www.52pojie.cn/

**Comment by geelinsir** [comment]
吾爱已被[mengshouer/CheckinBox](https://github.com/mengshouer/CheckinBox)实现，相关代码[在这里](https://github.com/mengshouer/CheckinBox/tree/master/Checkin52pj)，希望 @Sitoi 能够整合

**Comment by Sitoi** [comment]
吾爱签到好想和 ip 相关 总是签到不成功。不知道解决办法

**Comment by geelinsir** [comment]
> 吾爱签到好想和 ip 相关 总是签到不成功。不知道解决办法
可以参考[mengshouer/CheckinBox](https://github.com/mengshouer/CheckinBox)，我使用时可以正常签到的
