### ISSUE TITLE
希望添加全民K歌VIP礼物领取

### ISSUE THREAD

**Issue by CrazyNutLz** [Sitoi/dailycheckin#63]
## 期望增加的功能

A：希望添加全民K歌VIP礼物领取

## 入口

A：点一下VIP的图标即可进入VIP专区领取

**Comment by Sitoi** [comment]
没有 VIP 账号

**Comment by CrazyNutLz** [comment]
https://node.kg.qq.com/webapp/proxy?t_uUid=这里是UID&ns=proto_vip_webapp&cmd=vip.get_vip_day_reward&ns_inbuf=&nocache=1613719349184&mapExt=JTdCJTIyY21kTmFtZSUyMiUzQSUyMkdldFZpcERheVJld2FyZCUyMiU3RA%3D%3D&g_tk_openkey=642424811

带cookie直接get这个API就行
后面又两个参数不知道怎么搞的

**Comment by CrazyNutLz** [comment]
已经测试上方链接只需要修改UID即可
