### ISSUE TITLE
Github上收集到的脚本，希望整合入本项目

### ISSUE THREAD

**Issue by geelinsir** [Sitoi/dailycheckin#65]
[happy888888/BiliExp](https://github.com/happy888888/BiliExp)项目，实现了更多的B站定时任务
[BlueskyClouds/My-Actions](https://github.com/BlueskyClouds/My-Actions)项目，实现了[哔咔漫画](https://github.com/BlueskyClouds/My-Actions/blob/master/function/bika.py)、[中国电信](https://github.com/BlueskyClouds/My-Actions/blob/master/function/10000.js)、[wps](https://github.com/BlueskyClouds/My-Actions/blob/master/function/wps_invitation.py)的签到
[xcqlucky/JD_Sign_Action](https://github.com/xcqlucky/JD_Sign_Action)项目，实现了京东多项定时任务
[QikaiXu/migu-sign](https://github.com/QikaiXu/migu-sign)项目，实现了咪咕爱看的签到
[QikaiXu/GLaDOS-checkin](https://github.com/QikaiXu/GLaDOS-checkin)项目，实现了GLaDOS自动续期
[18357451081/Action](https://github.com/18357451081/Action)项目，实现了SockBoom签到
[shenmishajing-script/wyycg_checkin](https://github.com/shenmishajing-script/wyycg_checkin)项目，实现了网易云游戏签到
[mengshouer/CheckinBox](https://github.com/mengshouer/CheckinBox)项目，实现了[最终幻想14积分商城](https://github.com/mengshouer/CheckinBox/tree/master/FF14Checkin)、[恩山论坛](https://github.com/mengshouer/CheckinBox/tree/master/Enshan)、[智友邦](https://github.com/mengshouer/CheckinBox/tree/master/Zhiyou)签到

**Comment by Sitoi** [comment]
大部分已实现，小部分受众太小，福利太小就不添加了。
