### ISSUE TITLE
欢太商城活动是不是有问题啊，怎么弄都是登录失败

### ISSUE THREAD

**Issue by ywjang1** [Sitoi/dailycheckin#66]

**Comment by Sitoi** [comment]
不晓得 我这边没有问题

**Comment by ywjang1** [comment]
![image](https://user-images.githubusercontent.com/66288421/140616812-56dbe70e-8674-4605-9d74-ca963c8500d0.png)
我这边就这个样子，不知道是什么原因

**Comment by ywjang1** [comment]
难道是我的cookie有问题吗？
![image](https://user-images.githubusercontent.com/66288421/140616894-8da9d0e9-c85c-488d-b742-22431cd91b20.png)
因为直接复制cookie进去会因为双引号的问题而报红所以我将她改成了单引号，难不成是他的问题？

**Comment by Caelestrasz** [comment]
我也是一样的问题，你最后解决了吗
