### ISSUE TITLE
actions运行不输出运行结果

### ISSUE THREAD

**Issue by Nemo2050** [Sitoi/dailycheckin#66]
## 1.关于你要提交的问题

Q：是否搜索了 issue（包括已关闭的issue）

- [ x] 没有类似的 issue 

Q：是否仔细阅读了教程

- [x ] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装 Python
- [ ] 方法二：Docker
- [ ] 方法三：腾讯云函数
- [ x] 方法四：GitHub Actions

### (1) 具体问题

A：
我配置了3个账号，网易云音乐，张大妈和天翼云，actions输出到已检测到正确配置，开始运行天翼云语句时，就没有后面的结果了，每次运行30s左右结束，我查看了下py文件是有写明输出日志的。估计没运行成功。
### (2) 详细日志

A：
[https://github.com/Nemo2050/dailycheckin/blob/main/Snipaste_2021-02-16_23-13-02.png](url)

**Comment by geelinsir** [comment]
建议配置SCKEY（server 酱推送），我通过推送可以看到执行情况，天翼网盘工作正常

**Comment by Sitoi** [comment]
配置相关推送 或者 手动检查是否完成签到
