### ISSUE TITLE
青龙报错 如图所示 谢谢

### ISSUE THREAD

**Issue by isslower** [Sitoi/dailycheckin#67]
timeout: failed to run command ‘dailycheckin’: No such file or directory，提示超时：无法运行命令“dailycheckin”：没有这样的文件或目录
pip3 install cryptography~=3.2.1 后报错如截图
![微信截图_20211106162237](https://user-images.githubusercontent.com/45580748/140603244-49de08af-5365-4ee4-98ce-2078da0e3cd5.png)

**Comment by wzwcc** [comment]
@isslower 是容器中运行的吗

**Comment by LiHang941** [comment]
请问解决了吗

**Comment by WowYiJiu** [comment]
pip安装命令后加-i http://pypi.douban.com/simple --trusted-host pypi.douban.com

**Comment by Sitoi** [comment]
不行就换方法

**Comment by 7214978** [comment]
将第一步安装依赖改成apk add --no-cache gcc g++ python3 python3-dev py-pip mysql-dev linux-headers libffi-dev openssl-dev

**Comment by isslower** [comment]
好的好的 谢谢
