### ISSUE TITLE
关于小米运动的建议

### ISSUE THREAD

**Issue by DoveBoy** [Sitoi/dailycheckin#68]
## 期望增加的功能

A：期望增加单独的小米运动环境变量，控制脚本运行时间，或者单独把小米运动配置别的时间运行。实际测试22点后刷小米运动的步数不会封号。之前用的都是早上刷小米运动，大概率会封号。希望开发者考虑一下。另外一个问题是，腾讯视频签到脚本似乎有问题，cookie是用网页端新抓取的，但是提示已签到或过期，实际没有签到成功

## 入口

A：

**Comment by Sitoi** [comment]
小米步数 连续一个多月 8:45 签到无异常。docker 用户可以配置 自定义 crontab 文件

**Comment by DoveBoy** [comment]
@Sitoi Ac怎么办？加个环境变量能实现吗？
