### ISSUE TITLE
K歌失败

### ISSUE THREAD

**Issue by hacken156026692** [Sitoi/dailycheckin#69]
## 1.关于你要提交的问题

Q：是否搜索了 issue（包括已关闭的issue）

- [x] 没有类似的 issue 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装 Python
- [ ] 方法二：Docker
- [ ] 方法三：腾讯云函数
- [x] 方法四：GitHub Actions

### (1) 具体问题

A：fork后，在secret里设置了KGQQ_COOKIE_LIST，具体值写的的用小黄鸟抓包的内容，直接把相关内容复制进去，见下方。
openkey=JxXXX; seclaunchsource=; NetworkInfo=1; openid=ocXXXX; extroInfo=1|0|2|0|-1; launchsource=deskicon|unknown|unknown|unknown|unknown; uid=XXXX; launchid=3512XXX_XXX_deskicon_unknown_5XXX4; schemaStr=; midasPfKey=pfKey; midasPf=wechat_wx-2001-android-2011; seclaunchid=; midasSessionId=hy_gameid; midasSessionType=wc_actoken; masteruid=0; udid=25XXXXXX; midasPayToken=; opentype=1
然后actions里，发现出错。

### (2) 详细日志

A：Run python3 index.py
Expecting value: line 1 column 1 (char 0)
----------未检测到正确的配置，并跳过执行 IQIYI_COOKIE_LIST 签到----------
----------未检测到正确的配置，并跳过执行 VQQ_COOKIE_LIST 签到----------
----------未检测到正确的配置，并跳过执行 KGQQ_COOKIE_LIST 签到----------
----------未检测到正确的配置，并跳过执行 MUSIC163_ACCOUNT_LIST 签到----------
----------未检测到正确的配置，并跳过执行 BILIBILI_COOKIE_LIST 签到----------
----------未检测到正确的配置，并跳过执行 YOUDAO_COOKIE_LIST 签到----------
----------未检测到正确的配置，并跳过执行 FMAPP_ACCOUNT_LIST 签到----------
----------未检测到正确的配置，并跳过执行 BAIDU_URL_SUBMIT_LIST 签到----------
----------未检测到正确的配置，并跳过执行 LIANTONG_ACCOUNT_LIST 签到----------
----------未检测到正确的配置，并跳过执行 ONEPLUSBBS_COOKIE_LIST 签到----------
----------未检测到正确的配置，并跳过执行 SMZDM_COOKIE_LIST 签到----------
----------未检测到正确的配置，并跳过执行 TIEBA_COOKIE_LIST 签到----------
----------未检测到正确的配置，并跳过执行 V2EX_COOKIE_LIST 签到----------
----------未检测到正确的配置，并跳过执行 WWW2NZZ_COOKIE_LIST 签到----------
----------未检测到正确的配置，并跳过执行 ACFUN_ACCOUNT_LIST 签到----------
----------未检测到正确的配置，并跳过执行 MIMOTION_ACCOUNT_LIST 签到----------
----------未检测到正确的配置，并跳过执行 CLOUD189_ACCOUNT_LIST 签到----------
----------未检测到正确的配置，并跳过执行 CITY_NAME_LIST 签到----------
0s
Post job cleanup.
/usr/bin/git version
git version 2.30.0
/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :
/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
http.https://github.com/.extraheader
/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :

**Comment by Sitoi** [comment]
配置有问题，请检查配置信息
