### ISSUE TITLE
网易音乐合伙人，每天评分可以获得终生黑胶VIP

### ISSUE THREAD

**Issue by BillScott1024** [Sitoi/dailycheckin#69]
大大考虑增加一个网易合伙人的评分脚本吗？之前用过一个在线的接口，但是不是很方便：
这个是接口的信息：
网站： https://www.shoubiao68.com/33658.html

网易云音乐合伙人自动评分接口版
接口地址：http://test.imz.xyz/pingfen.php 参数user/pwd

图片为最新一期结算的积分

过320分即可续费会员还有合伙人身份。

别问在哪。问就去网易云搜索音乐合伙人

官方发放的资格。

有兴趣的我也可以放源码出来。

接口保证不偷cookie 不保存账号密码

只关注了作者网易云

![image](https://user-images.githubusercontent.com/22955480/141485840-83db7efe-558a-41d6-b62e-ab7d84957321.png)

**Comment by SpoonerCakes** [comment]
同求

**Comment by KotoriMinami** [comment]
> 同求

https://github.com/KotoriMinami/qinglong-sign

**Comment by yz9999** [comment]
接口要备案了
