### ISSUE TITLE
请问大佬，qqread多账户如何设置

### ISSUE THREAD

**Issue by lingyle** [Sitoi/dailycheckin#7]
## 期望增加的功能

A：

## 入口

A：

**Comment by Sitoi** [comment]
配置文件里面样例已经写了呀

**Comment by lingyle** [comment]
我照配置里设置了4个账号的4组资料，只有第1个有正常log，是否需要重启docker?

**Comment by lingyle** [comment]
我重启试试，再等几分钟看看

**Comment by Sitoi** [comment]
docker-compose down 
再
docker-compose up

**Comment by lingyle** [comment]
重启有效，谢谢大佬
