### ISSUE TITLE
Qmsg推送提示消息违规

### ISSUE THREAD

**Issue by fengyec2** [Sitoi/dailycheckin#70]
Qmsg推送提示消息违规，原因恶意推广（https://github.com/sitoi/dailycheckin）

![Screenshot_20211114_112245_mark via_edit_282298687578797](https://user-images.githubusercontent.com/85821538/141666247-adbf649b-46db-4390-95fe-4e4f26ea685d.jpg)

**Comment by Sitoi** [comment]
换方式
