### ISSUE TITLE
什么值得买无法执行

### ISSUE THREAD

**Issue by renffy** [Sitoi/dailycheckin#72]
## 1.关于你要提交的问题

Q：是否搜索了 issue（包括已关闭的issue）

- [x] 没有类似的 issue 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装 Python
- [ ] 方法二：Docker
- [ ] 方法三：腾讯云函数
- [x] 方法四：GitHub Actions

### (1) 具体问题

A：已经填写SMZDM_COOKIE和SMZDM_COOKIE_LIST，执行时提示未找到正确的配置

### (2) 详细日志

A：Expecting value: line 1 column 1 (char 0)
----------未检测到正确的配置，并跳过执行 IQIYI_COOKIE_LIST 签到----------
----------未检测到正确的配置，并跳过执行 VQQ_COOKIE_LIST 签到----------
----------未检测到正确的配置，并跳过执行 KGQQ_COOKIE_LIST 签到----------
----------未检测到正确的配置，并跳过执行 MUSIC163_ACCOUNT_LIST 签到----------
----------未检测到正确的配置，并跳过执行 BILIBILI_COOKIE_LIST 签到----------
----------未检测到正确的配置，并跳过执行 YOUDAO_COOKIE_LIST 签到----------
----------未检测到正确的配置，并跳过执行 FMAPP_ACCOUNT_LIST 签到----------
----------未检测到正确的配置，并跳过执行 BAIDU_URL_SUBMIT_LIST 签到----------
----------未检测到正确的配置，并跳过执行 LIANTONG_ACCOUNT_LIST 签到----------
----------未检测到正确的配置，并跳过执行 ONEPLUSBBS_COOKIE_LIST 签到----------
**----------未检测到正确的配置，并跳过执行 SMZDM_COOKIE_LIST 签到----------**
----------未检测到正确的配置，并跳过执行 TIEBA_COOKIE_LIST 签到----------
----------未检测到正确的配置，并跳过执行 V2EX_COOKIE_LIST 签到----------
----------未检测到正确的配置，并跳过执行 WWW2NZZ_COOKIE_LIST 签到----------
----------未检测到正确的配置，并跳过执行 ACFUN_ACCOUNT_LIST 签到----------
----------未检测到正确的配置，并跳过执行 MIMOTION_ACCOUNT_LIST 签到----------
----------未检测到正确的配置，并跳过执行 CLOUD189_ACCOUNT_LIST 签到----------
----------未检测到正确的配置，并跳过执行 CITY_NAME_LIST 签到----------
server 酱 Turbo 推送开始

**Comment by Sitoi** [comment]
说明你配置的不正确

**Comment by renffy** [comment]
需要怎么配置呢？根据https://sitoi.github.io/dailycheckin/settings/#web填的SMZDM_COOKIE_LIST，cookie，还请帮忙看看指导下，谢谢~

**Comment by renffy** [comment]
secrets配置 https://imgchr.com/i/yHGhlR
