### ISSUE TITLE
增加飞客茶馆论坛的签到

### ISSUE THREAD

**Issue by xucongwei** [Sitoi/dailycheckin#75]
## 期望增加的功能

A：
飞客茶馆论坛：https://www.flyertea.com/sign.php
discuz论坛，跟52pojie一样的签到方式。ck有效期应该有3个多月，适合新增签到。
每日签到 基础奖励: 1~3 威望

## 入口
https://www.flyertea.com/sign.php

A：

**Comment by xucongwei** [comment]
另外想再请教下大佬，喜马拉雅极速版index.py xmly 是不是和 index.py 都要各自独立执行一次命令?
喜马拉雅极速版每半小时执行一次，命令是执行一次 index.py xmly 就行了还是每隔半小时执行一次命令？
![QQ截图20210224004108](https://user-images.githubusercontent.com/60318629/108876325-13a92e00-7639-11eb-8803-3abd6f6d5145.jpg)

**Comment by Sitoi** [comment]
> 另外想再请教下大佬，喜马拉雅极速版index.py xmly 是不是和 index.py 都要各自独立执行一次命令?
> 喜马拉雅极速版每半小时执行一次，命令是执行一次 index.py xmly 就行了还是每隔半小时执行一次命令？
> ![QQ截图20210224004108](https://user-images.githubusercontent.com/60318629/108876325-13a92e00-7639-11eb-8803-3abd6f6d5145.jpg)

其他的签到 每天执行一次即可。
xmly 每隔半小时执行一次命令
