### ISSUE TITLE
群晖docker搭建有的任务想运行再次，修改了cron，好像会自动还原

### ISSUE THREAD

**Issue by jjss520** [Sitoi/dailycheckin#75]
请问一下，怎么解决

**Comment by Sitoi** [comment]
看视频教程

**Comment by reY2ox** [comment]
我也遇到了这个问题。最终我发现是通过阿里的镜像源拉取的docker是21年封装的，即使作者做到了镜像内的pip更新程序，但是启动程序的脚本还是旧的，所以导致最新的挂载方法无法正确的使用。建议删掉镜像切换源后重新下载镜像。
