### ISSUE TITLE
Docker 配置文件目录迁移

### ISSUE THREAD

**Issue by Sitoi** [Sitoi/dailycheckin#76]
影响用户：docker 部署方式。
更新内容：config.json 配置文件位置由原先的 dailycheckin/config.json 更改为 dailycheckin/config/config.json。
解决方案：停止并删除旧版本容器 >> 拉取最新的 docker 镜像 >> 备份旧版本 config.json 文件 >> 运行一键启动并创建服务命令 >> 待容器启动完成，替换 config 文件夹下的 config.json 文件即可 >> 手动立即执行一次查看签到脚本。
详细文档：https://sitoi.github.io/dailycheckin/docker/

**Comment by 5axf** [comment]
大佬，运行一键启动并创建服务命令 提示权限不足，加了sudo也不行，不是root用户，有什么解决方法吗？

**Comment by Sitoi** [comment]
> 大佬，运行一键启动并创建服务命令 提示权限不足，加了sudo也不行，不是root用户，有什么解决方法吗？

报错信息是什么？

**Comment by 5axf** [comment]
![image](https://user-images.githubusercontent.com/46812012/108931887-67d90000-7683-11eb-9e17-691b2a92bf35.png)

**Comment by Sitoi** [comment]
目录应该创建成功了吧，你可以手动 docker-compose up -d 试试

**Comment by 5axf** [comment]
> 目录应该创建成功了吧，你可以手动 docker-compose up -d 试试

目录创建成功了，手动docker-compose up -d 下载贼慢，几十k每秒...

**Comment by Sitoi** [comment]
> > 目录应该创建成功了吧，你可以手动 docker-compose up -d 试试
> 
> 目录创建成功了，手动docker-compose up -d 下载贼慢，几十k每秒...

应该是第一次拉取镜像的原因吧。

**Comment by 5axf** [comment]
> > > 目录应该创建成功了吧，你可以手动 docker-compose up -d 试试
> > 
> > 
> > 目录创建成功了，手动docker-compose up -d 下载贼慢，几十k每秒...
> 
> 应该是第一次拉取镜像的原因吧。

我把之前的镜像删除了，应该是这个原因
