### ISSUE TITLE
吾爱出现 list index out of range

### ISSUE THREAD

**Issue by taylorSZSS** [Sitoi/dailycheckin#76]
cookie为网页F12复制，对/进行转义成\/   去掉COOKie尾巴%09plugin.php%09    ，测试结果为
![image](https://user-images.githubusercontent.com/30972646/142816575-963525ce-545e-486e-ba51-260c009f99f4.png)

**Comment by zhxingway** [comment]
不行了吗，今天刚遇到这个问题
也是list index out of range
![image](https://user-images.githubusercontent.com/43720357/151995851-1915410d-c960-4f33-8e97-f5aced93ac9b.png)
