### ISSUE TITLE
腾讯视频是不是已经失效了啊

### ISSUE THREAD

**Issue by Nshandeshu** [Sitoi/dailycheckin#77]
「腾讯视频」
签到奖励1: 签到失败(可能已签到)
签到失败: 自行在腾讯视频APP内登录网址签到 http://v.qq.com/x/bu/mobile_checkin (基本每周都需要手动签到一次才可以)
签到奖励2: 成长值x0
观看视频60min: 任务未完成，需手动完成任务
使用弹幕特权: 任务未完成，需手动完成任务
使用赠片特权: 任务未完成，需手动完成任务
使用下载特权: 任务未完成，需手动完成任务

两处地址填写好，推送出现这个

**Comment by FENGYINYUANYOU** [comment]
同问  我的也是这样   爱奇艺也不行  只显示 'daily'  没了. 请问什么原因呢

**Comment by TurboJerry** [comment]
好像要VIP用户才能签到

**Comment by FENGYINYUANYOU** [comment]
好吧,腾讯和爱奇艺都不是会员.........

**Comment by FENGYINYUANYOU** [comment]
只有优酷会员

**Comment by shilinjin** [comment]
我是会员也这样显示。。。。

**Comment by canadancing** [comment]
http://v.qq.com/x/bu/mobile_checkin 这个链接也是过期的.没有这个链接了. 我是会员.
