### ISSUE TITLE
能否增加腾讯云函数签到,一天5积分,10天白嫖5元

### ISSUE THREAD

**Issue by acc20777** [Sitoi/dailycheckin#8]
![photo_2021-06-17_10-31-43](https://user-images.githubusercontent.com/77967929/122322238-c0e0e280-cf57-11eb-81c9-da016e686c15.jpg)
![photo_2021-06-17_10-31-45](https://user-images.githubusercontent.com/77967929/122322247-c3433c80-cf57-11eb-9bd3-f6cb0dddfe1a.jpg)

腾讯云函数的签到,可以白嫖积分

**Comment by mmkkllpp** [comment]
用腾讯云函数白嫖云函数？？？？

**Comment by cc123687** [comment]
[https://serverlesscs.cloud.tencent.com/api/workspace/zfqdtm/heartbeat](url)

**Comment by cc123687** [comment]
给个get或者post请求，把登录好的浏览器cookie加上，就可以试一下



>

**Comment by cc123687** [comment]
[https://sunete.github.io/tutorial/discuz-auto-check-in/](url)

**Comment by cc123687** [comment]
[https://sunete.github.io/tutorial/discuz-auto-check-in/](url)

**Comment by cc123687** [comment]
https://sunete.github.io/tutorial/discuz-auto-check-in/

**Comment by cc123687** [comment]
www.bilibili.com/read/cv2907983
