### ISSUE TITLE
qqread宝箱间隔时间已发生变化

### ISSUE THREAD

**Issue by lingyle** [Sitoi/dailycheckin#8]
## 期望增加的功能

A：

## 入口

A：

**Comment by Sitoi** [comment]
变成什么了

**Comment by lingyle** [comment]
09:02:53   【宝箱任务24】:15分钟后领取
09:11:36 【宝箱任务24】:4分钟后领取
09:33:34 【宝箱任务25】:9分钟后领取
09:55:35 【宝箱任务26】:9分钟后领取
10:22:34 【宝箱任务27】:9分钟后领取
10:44:34 【宝箱任务28】:9分钟后领取
11:00:36 【宝箱任务29】:15分钟后领取
11:11:35 【宝箱任务29】:4分钟后领取
11:33:34 【宝箱任务30】:9分钟后领取
11:55:35 【宝箱任务31】:9分钟后领取
12:00:36 【宝箱任务31】:4分钟后领取
12:22:35 【宝箱任务32】:9分钟后领取
12:44:36 【宝箱任务33】:9分钟后领取
13:00:36 【宝箱任务34】:15分钟后领取
13:11:35 【宝箱任务34】:4分钟后领取
13:33:35 【宝箱任务35】:9分钟后领取
13:55:35 【宝箱任务36】:9分钟后领取
14:00:35 【宝箱任务36】:4分钟后领取
14:22:35 【宝箱任务37】:9分钟后领取
14:44:35 【宝箱任务38】:9分钟后领取
15:00:36 【宝箱任务39】:15分钟后领取
15:11:35 【宝箱任务39】:4分钟后领取
15:33:35 【宝箱任务40】:9分钟后领取
15:55:36 【宝箱任务41】:9分钟后领取
16:00:36 【宝箱任务41】:4分钟后领取
16:22:36 【宝箱任务42】:9分钟后领取
16:44:34 【宝箱任务43】:9分钟后领取
17:00:35 【宝箱任务44】:15分钟后领取
17:11:35 【宝箱任务44】:4分钟后领取
17:33:36 【宝箱任务45】:9分钟后领取
17:55:36 【宝箱任务46】:9分钟后领取
18:02:57 【宝箱任务46】:4分钟后领取
18:22:38 【宝箱任务47】:9分钟后领取
18:44:34 【宝箱任务48】:9分钟后领取
19:00:35 【宝箱任务49】:15分钟后领取
19:11:37 【宝箱任务49】:4分钟后领取
19:33:36 【宝箱任务50】:9分钟后领取
19:55:35 【宝箱任务51】:9分钟后领取
20:00:35 【宝箱任务51】:4分钟后领取
20:22:37 【宝箱任务52】:9分钟后领取
20:44:36 【宝箱任务53】:9分钟后领取

**Comment by lingyle** [comment]
这是早上到刚才的记录
