### ISSUE TITLE
希望支持amd64的docker

### ISSUE THREAD

**Issue by tangli159** [Sitoi/dailycheckin#80]
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

**Comment by tangli159** [comment]
另外，喜马拉雅极速版的推送通知是不是没有开呀？我的每日签到合集能正常推送 但是喜马拉雅极速版的每30分钟那个没有推送

**Comment by Sitoi** [comment]
没有 arm 的设备进行测试
喜马拉雅是每天早上9点和晚上6点通知，其他时间不通知
