### ISSUE TITLE
【盖乐世社区】Cookie 单天失效

### ISSUE THREAD

**Issue by xucongwei** [Sitoi/dailycheckin#82]
## 1.关于你要提交的问题

Q：是否搜索了 issue（包括已关闭的issue）

- [ ] 没有类似的 issue 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [x] 方法一：本地安装 Python
- [ ] 方法二：Docker
- [ ] 方法三：腾讯云函数
- [ ] 方法四：GitHub Actions

### (1) 具体问题

A：盖乐世社区的ck是不是一天失效，都没信心获取了。

### (2) 详细日志

A：

**Comment by Sitoi** [comment]
是的 因为有效的参数在 会话里 一天不到就失效了。有空看看账号密码加密登录吧。
