### ISSUE TITLE
青龙内无法安装cryptography

### ISSUE THREAD

**Issue by lupohan44** [Sitoi/dailycheckin#82]
安装3.2.1得到如下错误

> root@qinglong:/ql $ pip3 install cryptography~=3.2.1
> Collecting cryptography~=3.2.1
>   Using cached cryptography-3.2.1.tar.gz (540 kB)
>   Installing build dependencies ... error
>   ERROR: Command errored out with exit status 1:
>    command: /usr/bin/python3 /tmp/pip-standalone-pip-2qjox1ip/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-kbr2ri_m/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.6.0' wheel 'cffi>=1.8,!=1.11.3; platform_python_implementation != '"'"'PyPy'"'"''
>        cwd: None
>   Complete output (78 lines):
>   Collecting setuptools>=40.6.0
>     Using cached setuptools-59.3.0-py3-none-any.whl (952 kB)
>   Collecting wheel
>     Using cached wheel-0.37.0-py2.py3-none-any.whl (35 kB)
>   Collecting cffi!=1.11.3,>=1.8
>     Using cached cffi-1.15.0.tar.gz (484 kB)
>     Preparing metadata (setup.py): started
>     Preparing metadata (setup.py): finished with status 'done'
>   Collecting pycparser
>     Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
>   Using legacy 'setup.py install' for cffi, since package 'wheel' is not installed.
>   Installing collected packages: pycparser, wheel, setuptools, cffi
>       Running setup.py install for cffi: started
>       Running setup.py install for cffi: finished with status 'error'
>       ERROR: Command errored out with exit status 1:
>        command: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-p8h05kbn/cffi_8d01f43141f447d5987116e4dba178ea/setup.py'"'"'; __file__='"'"'/tmp/pip-install-p8h05kbn/cffi_8d01f43141f447d5987116e4dba178ea/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-l1ova7y1/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-kbr2ri_m/overlay --compile --install-headers /tmp/pip-build-env-kbr2ri_m/overlay/include/python3.9/cffi
>            cwd: /tmp/pip-install-p8h05kbn/cffi_8d01f43141f447d5987116e4dba178ea/
>       Complete output (58 lines):
>       Package libffi was not found in the pkg-config search path.
>       Perhaps you should add the directory containing `libffi.pc'
>       to the PKG_CONFIG_PATH environment variable
>       Package 'libffi', required by 'virtual:world', not found
>       Package libffi was not found in the pkg-config search path.
>       Perhaps you should add the directory containing `libffi.pc'
>       to the PKG_CONFIG_PATH environment variable
>       Package 'libffi', required by 'virtual:world', not found
>       Package libffi was not found in the pkg-config search path.
>       Perhaps you should add the directory containing `libffi.pc'
>       to the PKG_CONFIG_PATH environment variable
>       Package 'libffi', required by 'virtual:world', not found
>       Package libffi was not found in the pkg-config search path.
>       Perhaps you should add the directory containing `libffi.pc'
>       to the PKG_CONFIG_PATH environment variable
>       Package 'libffi', required by 'virtual:world', not found
>       Package libffi was not found in the pkg-config search path.
>       Perhaps you should add the directory containing `libffi.pc'
>       to the PKG_CONFIG_PATH environment variable
>       Package 'libffi', required by 'virtual:world', not found
>       running install
>       /usr/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
>         warnings.warn(
>       running build
>       running build_py
>       creating build
>       creating build/lib.linux-x86_64-3.9
>       creating build/lib.linux-x86_64-3.9/cffi
>       copying cffi/vengine_gen.py -> build/lib.linux-x86_64-3.9/cffi
>       copying cffi/vengine_cpy.py -> build/lib.linux-x86_64-3.9/cffi
>       copying cffi/commontypes.py -> build/lib.linux-x86_64-3.9/cffi
>       copying cffi/cffi_opcode.py -> build/lib.linux-x86_64-3.9/cffi
>       copying cffi/setuptools_ext.py -> build/lib.linux-x86_64-3.9/cffi
>       copying cffi/model.py -> build/lib.linux-x86_64-3.9/cffi
>       copying cffi/cparser.py -> build/lib.linux-x86_64-3.9/cffi
>       copying cffi/__init__.py -> build/lib.linux-x86_64-3.9/cffi
>       copying cffi/backend_ctypes.py -> build/lib.linux-x86_64-3.9/cffi
>       copying cffi/api.py -> build/lib.linux-x86_64-3.9/cffi
>       copying cffi/error.py -> build/lib.linux-x86_64-3.9/cffi
>       copying cffi/pkgconfig.py -> build/lib.linux-x86_64-3.9/cffi
>       copying cffi/recompiler.py -> build/lib.linux-x86_64-3.9/cffi
>       copying cffi/ffiplatform.py -> build/lib.linux-x86_64-3.9/cffi
>       copying cffi/lock.py -> build/lib.linux-x86_64-3.9/cffi
>       copying cffi/verifier.py -> build/lib.linux-x86_64-3.9/cffi
>       copying cffi/_cffi_include.h -> build/lib.linux-x86_64-3.9/cffi
>       copying cffi/parse_c_type.h -> build/lib.linux-x86_64-3.9/cffi
>       copying cffi/_embedding.h -> build/lib.linux-x86_64-3.9/cffi
>       copying cffi/_cffi_errors.h -> build/lib.linux-x86_64-3.9/cffi
>       running build_ext
>       building '_cffi_backend' extension
>       creating build/temp.linux-x86_64-3.9
>       creating build/temp.linux-x86_64-3.9/c
>       gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -DTHREAD_STACK_SIZE=0x100000 -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python3.9 -c c/_cffi_backend.c -o build/temp.linux-x86_64-3.9/c/_cffi_backend.o
>       c/_cffi_backend.c:15:10: fatal error: ffi.h: No such file or directory
>          15 | #include <ffi.h>
>             |          ^~~~~~~
>       compilation terminated.
>       error: command '/usr/bin/gcc' failed with exit code 1
>       ----------------------------------------
>   ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-p8h05kbn/cffi_8d01f43141f447d5987116e4dba178ea/setup.py'"'"'; __file__='"'"'/tmp/pip-install-p8h05kbn/cffi_8d01f43141f447d5987116e4dba178ea/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-l1ova7y1/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-kbr2ri_m/overlay --compile --install-headers /tmp/pip-build-env-kbr2ri_m/overlay/include/python3.9/cffi Check the logs for full command output.
> 
> WARNING: Discarding https://files.pythonhosted.org/packages/94/5c/42de91c7fbdb817b2d9a4e64b067946eb38a4eb36c1a09c96c87a0f86a82/cryptography-3.2.1.tar.gz#sha256=d3d5e10be0cf2a12214ddee45c6bd203dab435e3d83b4560c03066eda600bfe3 (from https://pypi.org/simple/cryptography/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*). Command errored out with exit status 1: /usr/bin/python3 /tmp/pip-standalone-pip-2qjox1ip/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-kbr2ri_m/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.6.0' wheel 'cffi>=1.8,!=1.11.3; platform_python_implementation != '"'"'PyPy'"'"'' Check the logs for full command output.
> ERROR: Could not find a version that satisfies the requirement cryptography~=3.2.1 (from versions: 0.1, 0.2, 0.2.1, 0.2.2, 0.3, 0.4, 0.5, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.6, 0.6.1, 0.7, 0.7.1, 0.7.2, 0.8, 0.8.1, 0.8.2, 0.9, 0.9.1, 0.9.2, 0.9.3, 1.0, 1.0.1, 1.0.2, 1.1, 1.1.1, 1.1.2, 1.2, 1.2.1, 1.2.2, 1.2.3, 1.3, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.4, 1.5, 1.5.1, 1.5.2, 1.5.3, 1.6, 1.7, 1.7.1, 1.7.2, 1.8, 1.8.1, 1.8.2, 1.9, 2.0, 2.0.1, 2.0.2, 2.0.3, 2.1, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.2, 2.2.1, 2.2.2, 2.3, 2.3.1, 2.4, 2.4.1, 2.4.2, 2.5, 2.6, 2.6.1, 2.7, 2.8, 2.9, 2.9.1, 2.9.2, 3.0, 3.1, 3.1.1, 3.2, 3.2.1, 3.3, 3.3.1, 3.3.2, 3.4, 3.4.1, 3.4.2, 3.4.3, 3.4.4, 3.4.5, 3.4.6, 3.4.7, 3.4.8, 35.0.0, 36.0.0)
> ERROR: No matching distribution found for cryptography~=3.2.1

不指定版本得到如下错误

> root@qinglong:/ql $ pip3 install cryptography
> Collecting cryptography
>   Using cached cryptography-36.0.0-cp36-abi3-musllinux_1_1_x86_64.whl (3.8 MB)
> Collecting cffi>=1.12
>   Using cached cffi-1.15.0.tar.gz (484 kB)
>   Preparing metadata (setup.py) ... done
> Requirement already satisfied: pycparser in /usr/lib/python3.9/site-packages (from cffi>=1.12->cryptography) (2.21)
> Using legacy 'setup.py install' for cffi, since package 'wheel' is not installed.
> Installing collected packages: cffi, cryptography
>     Running setup.py install for cffi ... error
>     ERROR: Command errored out with exit status 1:
>      command: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-i739kzlc/cffi_9c332cdaf56e4012917f9209109fc7d5/setup.py'"'"'; __file__='"'"'/tmp/pip-install-i739kzlc/cffi_9c332cdaf56e4012917f9209109fc7d5/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ejykiesc/install-record.txt --single-version-externally-managed --compile --install-headers /usr/include/python3.9/cffi
>          cwd: /tmp/pip-install-i739kzlc/cffi_9c332cdaf56e4012917f9209109fc7d5/
>     Complete output (58 lines):
>     Package libffi was not found in the pkg-config search path.
>     Perhaps you should add the directory containing `libffi.pc'
>     to the PKG_CONFIG_PATH environment variable
>     Package 'libffi', required by 'virtual:world', not found
>     Package libffi was not found in the pkg-config search path.
>     Perhaps you should add the directory containing `libffi.pc'
>     to the PKG_CONFIG_PATH environment variable
>     Package 'libffi', required by 'virtual:world', not found
>     Package libffi was not found in the pkg-config search path.
>     Perhaps you should add the directory containing `libffi.pc'
>     to the PKG_CONFIG_PATH environment variable
>     Package 'libffi', required by 'virtual:world', not found
>     Package libffi was not found in the pkg-config search path.
>     Perhaps you should add the directory containing `libffi.pc'
>     to the PKG_CONFIG_PATH environment variable
>     Package 'libffi', required by 'virtual:world', not found
>     Package libffi was not found in the pkg-config search path.
>     Perhaps you should add the directory containing `libffi.pc'
>     to the PKG_CONFIG_PATH environment variable
>     Package 'libffi', required by 'virtual:world', not found
>     running install
>     /usr/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
>       warnings.warn(
>     running build
>     running build_py
>     creating build
>     creating build/lib.linux-x86_64-3.9
>     creating build/lib.linux-x86_64-3.9/cffi
>     copying cffi/vengine_gen.py -> build/lib.linux-x86_64-3.9/cffi
>     copying cffi/vengine_cpy.py -> build/lib.linux-x86_64-3.9/cffi
>     copying cffi/commontypes.py -> build/lib.linux-x86_64-3.9/cffi
>     copying cffi/cffi_opcode.py -> build/lib.linux-x86_64-3.9/cffi
>     copying cffi/setuptools_ext.py -> build/lib.linux-x86_64-3.9/cffi
>     copying cffi/model.py -> build/lib.linux-x86_64-3.9/cffi
>     copying cffi/cparser.py -> build/lib.linux-x86_64-3.9/cffi
>     copying cffi/__init__.py -> build/lib.linux-x86_64-3.9/cffi
>     copying cffi/backend_ctypes.py -> build/lib.linux-x86_64-3.9/cffi
>     copying cffi/api.py -> build/lib.linux-x86_64-3.9/cffi
>     copying cffi/error.py -> build/lib.linux-x86_64-3.9/cffi
>     copying cffi/pkgconfig.py -> build/lib.linux-x86_64-3.9/cffi
>     copying cffi/recompiler.py -> build/lib.linux-x86_64-3.9/cffi
>     copying cffi/ffiplatform.py -> build/lib.linux-x86_64-3.9/cffi
>     copying cffi/lock.py -> build/lib.linux-x86_64-3.9/cffi
>     copying cffi/verifier.py -> build/lib.linux-x86_64-3.9/cffi
>     copying cffi/_cffi_include.h -> build/lib.linux-x86_64-3.9/cffi
>     copying cffi/parse_c_type.h -> build/lib.linux-x86_64-3.9/cffi
>     copying cffi/_embedding.h -> build/lib.linux-x86_64-3.9/cffi
>     copying cffi/_cffi_errors.h -> build/lib.linux-x86_64-3.9/cffi
>     running build_ext
>     building '_cffi_backend' extension
>     creating build/temp.linux-x86_64-3.9
>     creating build/temp.linux-x86_64-3.9/c
>     gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -DTHREAD_STACK_SIZE=0x100000 -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python3.9 -c c/_cffi_backend.c -o build/temp.linux-x86_64-3.9/c/_cffi_backend.o
>     c/_cffi_backend.c:15:10: fatal error: ffi.h: No such file or directory
>        15 | #include <ffi.h>
>           |          ^~~~~~~
>     compilation terminated.
>     error: command '/usr/bin/gcc' failed with exit code 1
>     ----------------------------------------
> ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-i739kzlc/cffi_9c332cdaf56e4012917f9209109fc7d5/setup.py'"'"'; __file__='"'"'/tmp/pip-install-i739kzlc/cffi_9c332cdaf56e4012917f9209109fc7d5/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ejykiesc/install-record.txt --single-version-externally-managed --compile --install-headers /usr/include/python3.9/cffi Check the logs for full command output.

**Comment by lupohan44** [comment]
需要额外apk add libffi libffi-dev openssl openssl-dev
请更新文档

**Comment by Congee31** [comment]
> 需要额外apk add libffi libffi-dev openssl openssl-dev 请更新文档

不止，还缺几个依赖！！！

**Comment by lupohan44** [comment]
> > 需要额外apk add libffi libffi-dev openssl openssl-dev 请更新文档
> 
> 不止，还缺几个依赖！！！

还有缺什么吗 我加上这几个就正常了

**Comment by aiwandexiaoer** [comment]
root@ql:/ql $ apk add libffi libffi-dev openssl openssl-dev
fetch https://mirrors.tuna.tsinghua.edu.cn/alpine/v3.14/main/x86_64/APKINDEX.tar.gz
fetch https://mirrors.tuna.tsinghua.edu.cn/alpine/v3.14/community/x86_64/APKINDEX.tar.gz
ERROR: unable to select packages:
  bizCode (no such package):
    required by: world[bizCode]
  bizMsg (no such package):
    required by: world[bizMsg]
  lxml (no such package):
    required by: world[lxml]
你好，我安装的时候出现这个错误是什么原因呢

**Comment by lupohan44** [comment]
> root@ql:/ql $ apk add libffi libffi-dev openssl openssl-dev fetch https://mirrors.tuna.tsinghua.edu.cn/alpine/v3.14/main/x86_64/APKINDEX.tar.gz fetch https://mirrors.tuna.tsinghua.edu.cn/alpine/v3.14/community/x86_64/APKINDEX.tar.gz ERROR: unable to select packages: bizCode (no such package): required by: world[bizCode] bizMsg (no such package): required by: world[bizMsg] lxml (no such package): required by: world[lxml] 你好，我安装的时候出现这个错误是什么原因呢

你用的是最新的docker image吗

**Comment by aiwandexiaoer** [comment]
2.10.11  目前用的是这个版本的，那我升级一下最新的再试一试

**Comment by aiwandexiaoer** [comment]
更新了最新的还是报这个错误，我是不是要重新安装一下面板

**Comment by Congee31** [comment]
> 

和面板没关系，和服务器有关系，换句话说，你的服务器连接不到相应的包的所在；如果你用宝塔面板，里面有自带本地版终端，直接用那个跑就行了！！！

**Comment by lupohan44** [comment]
> 和面板没关系，和服务器有关系，换句话说，你的服务器连接不到相应的包的所在；如果你用宝塔面板，里面有自带本地版终端，直接用那个跑就行了！！！

青龙面板是一个docker镜像 基于Alpine制作的 我们所说的青龙面板都是指这个docker镜像里面的环境

**Comment by Sitoi** [comment]
```bash
apk add --no-cache --virtual .build-deps gcc musl-dev python2-dev python3-dev libffi libffi-dev openssl openssl-dev
pip3 install pip setuptools --upgrade
pip3 install cryptography~=3.2.1
```

**Comment by aiwandexiaoer** [comment]
root@ql:/ql $ apk add --no-cache --virtual .build-deps gcc musl-dev python2-dev python3-dev libffi libffi-dev openssl openssl-dev
fetch https://mirrors.tuna.tsinghua.edu.cn/alpine/v3.14/main/x86_64/APKINDEX.tar.gz
fetch https://mirrors.tuna.tsinghua.edu.cn/alpine/v3.14/community/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/latest-stable/community/x86_64/APKINDEX.tar.gz
ERROR: unable to select packages:
  bizCode (no such package):
    required by: world[bizCode]
  bizMsg (no such package):
    required by: world[bizMsg]
  lxml (no such package):
    required by: world[lxml]
  so:libffi.so.8 (no such package):
    required by: python2-2.7.18-r4[so:libffi.so.8]


我用的宝塔里面的终端还是这个错误

**Comment by Congee31** [comment]
使用宝塔就直接在宝塔里跑命令就行了！

发自我的iPad

**Comment by dwzrlp** [comment]
> 

解决了吗？我也是这个错误

**Comment by lupohan44** [comment]
> > 
> 
> 解决了吗？我也是这个错误

如果上述命令仍然安装失败先运行下面的命令

apk add --no-cache --virtual .build-deps gcc musl-dev python2-dev python3-dev libffi libffi-dev openssl openssl-dev
pip3 install pip setuptools --upgrade
pip3 install cryptography~=3.2.1
pip3 install dailycheckin --upgrade

**Comment by Toodow** [comment]
我也是一样的，在宝塔里也解决不了
root@ql:/ql $ apk add --no-cache --virtual .build-deps gcc musl-dev python2-dev python3-dev libffi libffi-dev openssl openssl-dev
fetch http://mirrors.tuna.tsinghua.edu.cn/alpine/v3.14/main/x86_64/APKINDEX.tar.gz
fetch http://mirrors.tuna.tsinghua.edu.cn/alpine/v3.14/community/x86_64/APKINDEX.tar.gz
ERROR: unable to select packages:
  ds (no such package):
    required by: world[ds]

**Comment by Hellager** [comment]
```bash
# 包管理器换源
sed -i 's#https\?://dl-cdn.alpinelinux.org/alpine#https://mirrors.tuna.tsinghua.edu.cn/alpine#g' /etc/apk/repositories

# 添加相关包
apk add --no-cache --virtua gcc musl-dev python3-dev libffi libffi-dev openssl openssl-dev

# python 换源
pip config set global.index-url https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple

# 安装 cryptography
pip3 install cryptography
```
