### ISSUE TITLE
【iqiyi】cookie问题

### ISSUE THREAD

**Issue by RockZhou8** [Sitoi/dailycheckin#83]
## 1.关于你要提交的问题

Q：是否搜索了 issue（包括已关闭的issue）

- [ x] 没有类似的 issue 

Q：是否仔细阅读了教程

- [x ] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装 Python
- [ ] 方法二：Docker
- [ ] 方法三：腾讯云函数
- [ x] 方法四：GitHub Actions

### (1) 具体问题
iqiyi 的cookie问题，按照https://sitoi.github.io/dailycheckin/settings/ 教程，直接对iqiyi开刀，没想到卡在cookie这里了，全选的cookie，但是json验证就报错，跑action返回了一个'data'
cookie里有这么一个参数
 QYABEX={"mergedAbtest":"1707_B,1550_B","PCW-Home-List":{"value":"1","abtest":"1707_B"},"pcw_home_hover":{"value":"1","abtest":"1550_B"}}; 
A：

### (2) 详细日志
json验证报错的也是这个：
Error: 在第3行发生解析错误 :
...; QC170=0; QYABEX={"mergedAbtest":"1707_
                  
此处缺少'EOF', '}', ':', ',', ']'字符, 实际上是一个 'undefined'

action的结果：
----------已检测到正确的配置，并开始执行 IQIYI_COOKIE_LIST 签到----------
'data'

进入iqiyi的个人中心，发现签到还是0/1

A：

PS:添加了小米运动账密测试，小米运动是OK的。
iqiyi的删掉QYABEX那段（删掉就json格式不报错了），还是没用效果。手动签到和每日任务是可以的，难道因为我不是VIP就用不了这个每日签到脚本吗？

**Comment by Sitoi** [comment]
不是 vip 签到是没用的 针对 VIP 获取的成长值。

**Comment by RockZhou8** [comment]
> 不是 vip 签到是没用的 针对 VIP 获取的成长值。

ok 懂了 这就删掉吧，没意义了
