### ISSUE TITLE
V2EX签到失败

### ISSUE THREAD

**Issue by lupohan44** [Sitoi/dailycheckin#84]
不使用Proxy:

> ----------开始执行「V2EX 论坛」签到----------
> 第 1 个账号: ❌❌❌❌❌
> 'str' object has no attribute 'get'

使用Proxy:

> ----------开始执行「V2EX 论坛」签到----------
> 第 1 个账号: ❌❌❌❌❌
> HTTPSConnectionPool(host='www.v2ex.com', port=443): Max retries exceeded with url: /mission/daily (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc451e975b0>: Failed to establish a new connection: [Errno 111] Connection refused')))

Proxy使用curl测试正常

**Comment by lupohan44** [comment]
https://github.com/Sitoi/dailycheckin/issues/43
已重新获取cookie测试过 结果一样

**Comment by Sitoi** [comment]
代理问题
