### ISSUE TITLE
【iqiyi、天翼云、一加论坛、bilibili】bug/功能建议

### ISSUE THREAD

**Issue by tangli159** [Sitoi/dailycheckin#84]
**一、爱奇艺cookie bug**
cookie：
XXXXXXXX; QYABEX={"mergedAbtest":"1707_B,1550_B","PCW-Home-List":{"value":"1","abtest":"1707_B"},"pcw_home_hover":{"value":"1","abtest":"1550_B"}}; XXXXXXXXXXXX; IMS=XXXXXX; QC179=XXX; XXXX; QC010=XXXX; __dfp=XXXXX; PCAU=0

1.QYABEX过不了json格式检验，删除整个QYABEX={};字段，可以检测到正确配置，但是推送信息没有爱奇艺

2.只删除QYABEX={};字段里面所有的""

**github actions**
----------已检测到正确的配置，并开始执行 IQIYI_COOKIE_LIST 签到----------
'data'
'deadline'
**推送信息**

【爱奇艺签到】
'deadline'
签到奖励: 用户不是会员
任务奖励: +0成长值
抽奖奖励: 《拆弹专家》;《拆弹专家》;《拆弹专家》;

但是手动访问爱奇艺个人中心链接：https://www.iqiyi.com/u/point ，发现每日任务里面全都没做
另外，发现其他的爱奇艺签到项目里多采用autocookie，时效性比较长，能否考虑用这个secret值？
参考：https://github.com/BlueskyClouds/My-Actions

**二、bilibili功能建议**

bilibili能否添加直播送出即将过期的礼物、给指定up主充电、年度大会员月底用B币券给自己充电等功能

参考：https://github.com/JunzhouLiu/BILIBILI-HELPER

**三、天翼云盘推送显示优化**

天翼云盘签到推送显示第一次抽奖: 获得1，第二次抽奖: 获得1。但是实际上全部都是获得50M。

**四、一加论坛推送显示优化**
当账户名为中文时，cookie中有字段为bbs_uname=%XX%XX%XX%XX%XX%XX%XX
推送信息为
【一加手机社区官方论坛】
帐号信息: %XX%XX%XX%XX%XX%XX%XX
签到信息: 恭喜你签到成功!获得随机奖励 加油 5 .
抽奖状态: 成功抽奖 10 次
抽奖结果: 获得 206 加油

可以让账号信息变成中文么？

**Comment by xucongwei** [comment]
> **一、爱奇艺cookie bug**
> cookie：
> XXXXXXXX; QYABEX={"mergedAbtest":"1707_B,1550_B","PCW-Home-List":{"value":"1","abtest":"1707_B"},"pcw_home_hover":{"value":"1","abtest":"1550_B"}}; XXXXXXXXXXXX; IMS=XXXXXX; QC179=XXX; XXXX; QC010=XXXX; __dfp=XXXXX; PCAU=0
> 
> 1.QYABEX过不了json格式检验，删除整个QYABEX={};字段，可以检测到正确配置，但是推送信息没有爱奇艺
> 
> 2.只删除QYABEX={};字段里面所有的""
> 
> **github actions**
> ----------已检测到正确的配置，并开始执行 IQIYI_COOKIE_LIST 签到----------
> 'data'
> 'deadline'
> **推送信息**
> 
> 【爱奇艺签到】
> 'deadline'
> 签到奖励: 用户不是会员
> 任务奖励: +0成长值
> 抽奖奖励: 《拆弹专家》;《拆弹专家》;《拆弹专家》;
> 
> 但是手动访问爱奇艺个人中心链接：https://www.iqiyi.com/u/point ，发现每日任务里面全都没做
> 另外，发现其他的爱奇艺签到项目里多采用autocookie，时效性比较长，能否考虑用这个secret值？
> 参考：https://github.com/BlueskyClouds/My-Actions
> 
> **二、bilibili功能建议**
> 
> bilibili能否添加直播送出即将过期的礼物、给指定up主充电、年度大会员月底用B币券给自己充电等功能
> 
> 参考：https://github.com/JunzhouLiu/BILIBILI-HELPER
> 
> **三、天翼云盘推送显示优化**
> 
> 天翼云盘签到推送显示第一次抽奖: 获得1，第二次抽奖: 获得1。但是实际上全部都是获得50M。
> 
> **四、一加论坛推送显示优化**
> 当账户名为中文时，cookie中有字段为bbs_uname=%XX%XX%XX%XX%XX%XX%XX
> 推送信息为
> 【一加手机社区官方论坛】
> 帐号信息: %XX%XX%XX%XX%XX%XX%XX
> 签到信息: 恭喜你签到成功!获得随机奖励 加油 5 .
> 抽奖状态: 成功抽奖 10 次
> 抽奖结果: 获得 206 加油
> 
> 可以让账号信息变成中文么？

支持，希望改进下

**Comment by Sitoi** [comment]
感谢提出的宝贵建议，已对上述内容进行相关优化，手头没有相关的账号，还请测试后，留下一个反馈，感谢！

1. 爱奇艺 cookie 应该是获取平台不一致的原因，至于json 多余的内容，我用的软件会自动转译。后期会在文档上添加相关说明；爱奇艺非会员签到存在的日志信息问题已修复，可以的话测试反馈一下；
2. bilibili 没有大会员，无法测试编写脚本；
3. 天翼云盘推送已优化，待明天签到测试；
4. 【一加手机社区官方论坛】用户昵称显示已优化，待测试。

**Comment by tangli159** [comment]
![image](https://user-images.githubusercontent.com/50565072/109381185-b69cc900-7913-11eb-89ba-06995af64df0.png)
今天按计划任务不知道为什么运行了四十多分钟，我只有手动取消了，再手动运行了一次，所以有的还得明天反馈。
1.爱奇艺签到，仍然采用的是去掉问题cookie的双引号 secret，签到信息为：
【爱奇艺签到】
VIP 等级: 1
当前成长值: 0
升级需成长值: 300
今日成长值: +0
VIP 到期时间: 非 VIP 用户
签到奖励: 用户不是会员
任务奖励: +0成长值
抽奖奖励: 抽奖机会不足
2.天翼云盘在运行了四十多分钟的action里面，没有收到推送信息，手动运行的时候已经是二次签到了。等待明日反馈。
3.一加手机论坛中文昵称已经恢复正常。

**Comment by tangli159** [comment]
反馈，天翼云今天推送信息正常。但github actions计划任务运行时间超长的情况仍然存在。手动触发就正常

**Comment by tangli159** [comment]
反馈 全部恢复正常。

**Comment by tangli159** [comment]
反馈：全部恢复正常。
