### ISSUE TITLE
【天翼云盘】签到日志报此错误No module named 'pyasn1'

### ISSUE THREAD

**Issue by ICEOOX** [Sitoi/dailycheckin#86]
## 1.关于你要提交的问题

Q：是否搜索了 issue（包括已关闭的issue）

- [x] 没有类似的 issue 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装 Python
- [ ] 方法二：Docker
- [x] 方法三：腾讯云函数
- [ ] 方法四：GitHub Actions

### (1) 具体问题

A：多有打扰，抱歉，今天部署到腾讯云函数中，只填写了推送和天翼云盘参数值测试。手机号和密码检查正确，又尝试了手机号后加@189.com后缀，结果依然是错误的，我又重新部署了次函数，依旧报错请您看下日志。

### (2) 详细日志

A：----------已检测到正确的配置，并开始执行 CLOUD189_ACCOUNT_LIST 签到----------

Starting new HTTPS connection (1): cloud.189.cn:443

https://cloud.189.cn:443 "GET /udb/udb_login.jsp?pageId=1&redirectURL=/main.action HTTP/1.1" 302 1177

Starting new HTTPS connection (1): open.e.189.cn:443

https://open.e.189.cn:443 "GET /api/logbox/oauth2/unifyAccountLogin.do?appId=cloud&version=v1.5&clientType=10010&format=redirect&paras=D07E36C9269BE1E9D7BC631AC2F0C09A100CE7406DCD8A1A7FAB82F0FE69FA314EB69E65F0BDE4FE3042ED803F70D8E6F739B6690599309DC9F1490FA68BC2434D10C03150D6C61344EE298E1C56921614CD26A3B4B061F7F8C80479029A571D33F4C6C403D10721A54C00ABF3AECCE7C403E7B99D3E98672CFFB1AE90B554F29F8DDA20369AE0E0DD263E7409FA15AD91A29CEB566CB74C31AB2727951B410EE38262F350149758CAEF72E42DFD612EC1018DA6EC03A5B6A7F41337F0184455686E9066F6FDB633A5A6E9C464D20FBF60B7F99B0B1586D82B83B043B6B518D6FBBD17C1C6B0CE66B9414BE647393AF9HHHHHHHHHH47E87C9527CD18B46F599A77A8EB156477EFD7CA1FC6A7281697B5DD5A875A993EC2405B516A6A9D6F7F30B3BCBE3141A73E40D6F3DF9458A5CDC56F09A452223940F00803691FB94F46D00F47A1FF6403F172CB93396BFC3EEDFC17F071DF5C7DED3B356C173AC046865C96B8969A6630A3DDD7A6BC0E06A2BD221C333BD01AF18D74E1B234779B7E71EE92FCFE734A4AAB8A796118450FF9E38A66B2F886D01A89774DBF8EB5381322ECF2225F36A670DBEB&sign=8EEC329ED27FBE7CDD5BD20235C592559B1AF3FA HTTP/1.1" 200 None

No module named 'pyasn1'

----------已检测到正确的配置，并开始执行 WPS_COOKIE_LIST 签到----------

推送错误消息中详细内容：
'latin-1' codec can't encode characters in position 0-1: ordinal not in range(256)

'latin-1' codec can't encode characters in position 0-1: ordinal not in range(256)

**Comment by Sitoi** [comment]
已修复相关依赖缺失的 BUG 重新部署即可！
