### ISSUE TITLE
有使用教程吗？不会用啊

### ISSUE THREAD

**Issue by tanchao111** [Sitoi/dailycheckin#87]
有使用教程吗？分享一下，完全不知道怎么使用！

**Comment by Sitoi** [comment]
https://sitoi.github.io/dailycheckin

**Comment by Inliang** [comment]
说实话，教程看了半天没看懂，腾讯云运行一直报错

**Comment by tanchao111** [comment]
> https://sitoi.github.io/dailycheckin

为什么打不开这个，需要翻墙吗？

**Comment by Inliang** [comment]
服务器是GitHub的国内访问还是比较慢的，翻墙可以试试


| |
零氪网络工作室
|
|
wxl1152727574@163.com
|
签名由网易邮箱大师定制
在2021年3月2日 12:24，tanchao111<notifications@github.com> 写道：

https://sitoi.github.io/dailycheckin

为什么打不开这个，需要翻墙吗？
