### ISSUE TITLE
使用教程为什么打不开？是需要翻墙吗？

### ISSUE THREAD

**Issue by tanchao111** [Sitoi/dailycheckin#88]
https://sitoi.github.io/dailycheckin  这个使用教程打不开，需要翻墙吗？

**Comment by Sitoi** [comment]
https://github.com/Sitoi/dailycheckin/tree/main/docs 看这个目录下的教程也可以

**Comment by Leon19960120** [comment]
用这个https://sitoi.gitee.io/dailycheckin
