### ISSUE TITLE
大佬们docker 怎样设置定时运行呀

### ISSUE THREAD

**Issue by johnleuang** [Sitoi/dailycheckin#89]
大佬们docker 怎样设置定时运行呀，用青龙运行完命令一直都提示找不到dailycheckin，cryptography也一直装不上，不知道是不是因为这个原因，用docker就很正常，但是怎样定时运行呀

**Comment by Sitoi** [comment]
看视频教程里面有

**Comment by HolyDomain** [comment]
> 看视频教程里面有

很感谢您无私的奉献，但是个人感觉这种步骤藏在视频里面，大家要找起来并应用，可能很不方便
