### ISSUE TITLE
【请求新增】文叔叔网盘签到

### ISSUE THREAD

**Issue by tanghengvip** [Sitoi/dailycheckin#9]
## 期望增加的功能

A：**文叔叔网盘每日签到**
官网：https://www.wenshushu.cn/
签到接口：https://www.wenshushu.cn/ap/reward/sign

**Comment by ioi32666** [comment]
请问云函数还能使用吗

**Comment by Sitoi** [comment]
加密逻辑还没找到，等假期有时间在帮你看看吧！

**Comment by tanghengvip** [comment]
> 加密逻辑还没找到，等假期有时间在帮你看看吧！

关键加密参数应该是请求header里的**a-code**，但js代码都混淆过，对我这种小白来说没办法看了，麻烦大佬有空帮忙看看啦~

**Comment by Sitoi** [comment]
已移步至 https://github.com/Sitoi/dailycheckin/discussions/77#discussioncomment-398498
