### ISSUE TITLE
【deploy.sh】json格式错误

### ISSUE THREAD

**Issue by qilin7** [Sitoi/dailycheckin#91]
## 1.关于你要提交的问题

Q：是否搜索了 issue（包括已关闭的issue）

- [ ] 没有类似的 issue 

Q：是否仔细阅读了教程

- [ ] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装 Python
- [ ] 方法二：Docker
- [x] 方法三：腾讯云函数
- [ ] 方法四：GitHub Actions

### (1) 具体问题

部署云函数生成的config.json格式错误，
麻烦大佬修改deploy.sh
59-63行代码为：

```
  \"QYWX_KEY\": \"${QYWX_KEY}\",
  \"QYWX_CORPID\": \"${QYWX_CORPID}\",
  \"QYWX_AGENTID\": \"${QYWX_AGENTID}\",
  \"QYWX_CORPSECRET\": \"${QYWX_CORPSECRET}\",
  \"QYWX_TOUSER\": \"${QYWX_TOUSER}\",
```

### (2) 详细日志

A：

**Comment by Sitoi** [comment]
感谢 已修复
