### ISSUE TITLE
联通营业厅报错

### ISSUE THREAD

**Issue by Kataick** [Sitoi/dailycheckin#91]
![image](https://user-images.githubusercontent.com/24969684/145744782-8234ae4f-f62b-4f45-ab66-51b1ae31eb21.png)

已更新过app_id

**Comment by gooelg** [comment]
这玩意 失效太快。。。跟不上

**Comment by FENGYINYUANYOU** [comment]
+1  报同样的错

**Comment by jeck5001** [comment]
+1
