### ISSUE TITLE
mgtv签到问题

### ISSUE THREAD

**Issue by DoveBoy** [Sitoi/dailycheckin#92]
## 1.关于你要提交的问题

Q：是否搜索了 issue（包括已关闭的issue）

- [x] 没有类似的 issue 

Q：是否仔细阅读了教程

- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装 Python
- [ ] 方法二：Docker
- [ ] 方法三：腾讯云函数
- [x] 方法四：GitHub Actions

### (1) 具体问题

A：Chrome下F12抓取的cookie一直不知道怎么抓取。运行后结果一直是None，请问芒果TV的cookie具体怎么抓取才是有效的ck？

### (2) 详细日志

A：
![image](https://user-images.githubusercontent.com/19201447/110084681-34a51800-7dcb-11eb-854e-5fb16faa0f25.png)

**Comment by Sitoi** [comment]
app 抓取
