### ISSUE TITLE
青龙跑文档里“如果上述命令仍然安装失败运行下面的命令”命令第二部分时，显示如下代码

### ISSUE THREAD

**Issue by Congee31** [Sitoi/dailycheckin#93]
Requirement already satisfied: six>=1.4.1 in /usr/lib/python3.8/site-packages (from cryptography~=3.2.1) (1.15.0)
Collecting cffi!=1.11.3,>=1.8
  Using cached cffi-1.15.0.tar.gz (484 kB)
  Preparing metadata (setup.py) ... done
Collecting pycparser
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Using legacy 'setup.py install' for cffi, since package 'wheel' is not installed.

并在末尾显示以下警告，要求在虚拟环境下跑，实测青龙task无法正常运行，无日志：
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

**Comment by aiwandexiaoer** [comment]
我的青龙面板跑不成功是因为cryptography这个依赖安装不成功

**Comment by xCss** [comment]
#83

**Comment by Sitoi** [comment]
```bash
apk add --no-cache --virtual .build-deps gcc musl-dev python2-dev python3-dev libffi libffi-dev openssl openssl-dev
pip3 install pip setuptools --upgrade
pip3 install cryptography~=3.2.1
```

**Comment by flatpig** [comment]
> ```shell
> apk add --no-cache --virtual .build-deps gcc musl-dev python2-dev python3-dev libffi libffi-dev openssl openssl-dev
> pip3 install pip setuptools --upgrade
> pip3 install cryptography~=3.2.1
> ```

这个可以
