### ISSUE TITLE
镜像无法启动

### ISSUE THREAD

**Issue by 9k001** [Sitoi/dailycheckin#93]
## 1.关于你要提交的问题

Q：是否搜索了 issue（包括已关闭的issue）

- [x] 没有类似的 issue 

Q：是否仔细阅读了教程

- [ ] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装 Python
- [x] 方法二：Docker
- [ ] 方法三：腾讯云函数
- [ ] 方法四：GitHub Actions

### (1) 具体问题

A：使用脚本部署，
curl https://raw.githubusercontent.com/Sitoi/dailycheckin/main/docker_start.sh | bash

镜像无法启动，找不到config.json
![image](https://user-images.githubusercontent.com/63529476/110104647-607fc800-7de2-11eb-9ed2-ba82c9a59823.png)

### (2) 详细日志

A：
Load the latest crontab task file...
加载最新的定时任务文件...
Start crontab task main process...
启动 crondtab 定时任务主进程...
chmod: /dailycheckin/config.json: No such file or directory

**Comment by Sitoi** [comment]
你没有配置文件

**Comment by 9k001** [comment]
> 你没有配置文件
按照理解，启动脚本中
创建config/config.json 并渲染。
我理解为，config.json需再配置账号密码 
是这个意思么？

**Comment by Sitoi** [comment]
你发的报错是没有配置文件，找不到 config/config.json 文件，你创建一个

**Comment by 9k001** [comment]
> 你发的报错是没有配置文件，找不到 config/config.json 文件，你创建一个

我检查了一下 确实是有的 因为你bash脚本中docker启动里面是有pwd的。
任意文件夹是Ok的。。
所以我不知道问题出在哪里

**Comment by Sitoi** [comment]
你是 docker run 启动的还是 docker-compose 启动的 ，可以的话 贴一下 目录结构吧

**Comment by 9k001** [comment]
> 你是 docker run 启动的还是 docker-compose 启动的 ，可以的话 贴一下 目录结构吧

docker启动
![image](https://user-images.githubusercontent.com/63529476/110118187-f02e7200-7df4-11eb-8061-79f301a5ace2.png)

**Comment by Sitoi** [comment]
docker 运行的命令是什么，挂载的路径需要写绝对路径

**Comment by 9k001** [comment]
> docker 运行的命令是什么，挂载的路径需要写绝对路径

这个我知道 我自己docker -v 不行之后就用了 你的部署脚本 我看有pwd 就不用 绝对路径了

**Comment by Sitoi** [comment]
日志说的是找不到 config.json 应该是你挂载的不太对

**Comment by 9k001** [comment]
> 日志说的是找不到 config.json 应该是你挂载的不太对

那为什么我用你的安装脚本也不行呢？。

**Comment by Sitoi** [comment]
你是服务器还是什么？

**Comment by tanzl** [comment]
我发现拉取latest版本的镜像居然不是最新的，然后挂载的目录跟文档上的对不上。
`$(pwd)/config:/dailycheckin/config`改成`$(pwd)/config.json:/dailycheckin/config.json`
