### ISSUE TITLE
【serverless.yml】云函数覆盖部署

### ISSUE THREAD

**Issue by qilin7** [Sitoi/dailycheckin#94]
## 1.关于你要提交的问题

Q：是否搜索了 issue（包括已关闭的issue）

- [ ] 没有类似的 issue 

Q：是否仔细阅读了教程

- [ ] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装 Python
- [ ] 方法二：Docker
- [x] 方法三：腾讯云函数
- [ ] 方法四：GitHub Actions

### (1) 具体问题

A：麻烦大佬修改下serverless.yml里的第三行的函数名字，
貌似因为函数名和触发器重名了，部署云函数时必须删除原有的云函数才能成功部署，

随便改个名就行了

### (2) 详细日志

A：报错日志dailycheckin › The specified TriggerName already exists. Please do not create again.

**Comment by Sitoi** [comment]
> ## 1.关于你要提交的问题
> Q：是否搜索了 issue（包括已关闭的issue）
> 
> * [ ]  没有类似的 issue
> 
> Q：是否仔细阅读了教程
> 
> * [ ]  已仔细阅读教程
> 
> ## 2. 你使用的哪种部署方法
> * [ ]  方法一：本地安装 Python
> * [ ]  方法二：Docker
> * [x]  方法三：腾讯云函数
> * [ ]  方法四：GitHub Actions
> 
> ## 3. 详细叙述
> ### (1) 具体问题
> A：麻烦大佬修改下serverless.yml里的第三行的函数名字，
> 貌似因为函数名和触发器重名了，部署云函数时必须删除原有的云函数才能成功部署，
> 
> 随便改个名就行了
> 
> ### (2) 详细日志
> A：报错日志dailycheckin › The specified TriggerName already exists. Please do not create again.

我好像没有这个问题，每次都会自动删除再创建的 是不是因为你是手动创建的。？？

**Comment by qilin7** [comment]
没手动创建，我再试下吧
